require("./drawPages/dashboard.js");//done//
require("./drawPages/orders.js");//done//
require("./drawPages/products.js");//done//
require("./drawPages/users.js");//done//
require("./drawPages/staff.js");//done//
require("./drawPages/design.js");//done//
require("./drawPages/settings.js");//done//
require("./drawPages/security.js");//done//
require("./drawPages/support.js");//done//
//
