<?php

namespace Database\Seeders\help_en_tuts\statistics;

use App\Models\help_en_text;
use App\Models\help_en_tut;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class tut66 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $upRates;
    protected $downRates;

    public function run()
    {
        $helpTut = help_en_tut::where('id',66)->select(['upRates','downRates'])->first();

        if($helpTut == null){
            $this->upRates = 0;
            $this->downRates = 0;

        }else{
            $this->upRates = $helpTut->upRates;
            $this->downRates = $helpTut->downRates;
        }
        help_en_text::where('help_en_tut_id',66)->delete();
        help_en_tut::where('id',66)->delete();
        $tutsTexts = [];
        help_en_tut::create([
            'id'=>66,
            'sort' => 2,
            'title_id' => 'Analyzing-your-products-performance',
            'title' => 'Analyzing your products performance',
            'description' => 'Using our statistics and analytics tool, you can thoroughly analyze the performance of your products, assisting you in knowing which food items are flourishing and which need more tweaks. In this article, you will learn how to generate an analysis.',
            'icon' => 'ico-products',
            'helpCat' => 'statistics-and-analytics',
            'keyWords' => '',
            'upRates' => $this->upRates,
            'downRates' => $this->downRates,
        ]);

        array_push($tutsTexts,[
            'sort'=>1,
            'help_en_tut_id' =>66,
            'title' => 'The importance of monitoring performance',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">Monitoring product performance allows restaurants to identify customer preferences and trends. With our statistics and analytics tool, you will gain insights into understanding which food items are preferred by your customers and which ones generate the most income to help you make informed decisions on optimizing your menu offerings and more.</div>
                <div class=\"sectionP\">To use this tool, go to the ‘Dashboard’ section of the control panel, then the ‘Statistics and Analytics’ subsection, to open a page with an overview of the statistics and analytics section.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>2,
            'help_en_tut_id' =>66,
            'title' => 'How to generate product performance analysis',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">On the statistics and analytics page, there is a 'Statistics Period' window. It lets you choose the timeframe for which you want to view your restaurant's performance. You can select a specific day, month, or year by checking the box next to the desired option and choosing a specific period of time from the date picker provided. Then, click on the 'Find' button to generate the relevant statistics.</div>
                <div class=\"sectionP\">After the statistics are generated for the specified period of time, you will be able to see a number of tabs:</div>
                <div class=\"sectionP\">Among these tabs is the ‘Products’ tab which is designed to provide insights into the performance of your restaurant's products. By clicking on this tab, a bar chart will appear, with a sidebar on the left side of the window. This sidebar is divided into two tabs: 'Income' which analyzes the product performance based on the income generated from each item, while 'Ordered' analyzes the product performance based on the frequency of customer orders.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>3,
            'help_en_tut_id' =>66,
            'title' => 'Products Income Analysis',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">Analyzing product performance based on income generated provides valuable insights into the financial viability of each food item.</div>
                <div class=\"sectionP\">In the ‘Income’ tab, you will find a list of your food items arranged in descending order of income, with the highest generating income at the top. This information is also visually presented in the bar chart displayed; by clicking on a specific food item, you can examine its profitability trend over the specified time period. </div>
                <div class=\"sectionP\">If you had selected the time period to be one month, then each bar would represent a day. When you hover over a bar in the chart, a box will display detailed information about the product for the selected day. The product details include the total income generated by the selected food item on this day, the number of orders received for the item, the preferred selections for this product (i.e. small size, large size, etc.), and any reviews related to that particular food item.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>4,
            'help_en_tut_id' =>66,
            'title' => 'Ordering Frequency Analysis',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">Knowing which products are ordered the most allows you to understand your customers' demand and preferences, this is especially useful when you’re planning to add new food items to your menu.</div>
                <div class=\"sectionP\">In the ‘Ordered’ tab, you will find a list of your food items arranged in descending order based on ordering frequency. The top of the list shows the most ordered items. Additionally, a bar chart visually presents this information. By selecting a specific food item, you can analyze its ordering frequency trend within the designated time frame.</div>
                <div class=\"tipContainer\">
                    <div class=\"ico-lamp tutTipIcon\"></div>
                    <div class=\"tutTipText\">Note that only the main account can browse the statistics and analytics.</div>
                </div>
            </div>
            ",
        ]);

        help_en_text::insert($tutsTexts);
    }
}
