<?php

namespace Database\Seeders\help_en_tuts\statistics;

use App\Models\help_en_text;
use App\Models\help_en_tut;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class tut70 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $upRates;
    protected $downRates;

    public function run()
    {
        $helpTut = help_en_tut::where('id',70)->select(['upRates','downRates'])->first();

        if($helpTut == null){
            $this->upRates = 0;
            $this->downRates = 0;

        }else{
            $this->upRates = $helpTut->upRates;
            $this->downRates = $helpTut->downRates;
        }
        help_en_text::where('help_en_tut_id',70)->delete();
        help_en_tut::where('id',70)->delete();
        $tutsTexts = [];
        help_en_tut::create([
            'id'=>70,
            'sort' => 2,
            'title_id' => 'Statistics-and-Analytics',
            'title' => 'Statistics and Analytics',
            'description' => 'For better monitoring of your business’s performance and growth, statistics and analytics tools come in handy. Learn more about how you can benefit from the tool for your restaurant.',
            'icon' => 'ico-statistics_and_analytics',
            'helpCat' => 'statistics-and-analytics',
            'keyWords' => '',
            'upRates' => $this->upRates,
            'downRates' => $this->downRates,
        ]);

        array_push($tutsTexts,[
            'sort'=>1,
            'help_en_tut_id' =>70,
            'title' => 'The importance of performance analytics',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">Analytics is the key to tracking your business growth and knowing where you stand. Using our statistics and analytics tool, you will be able to make better decisions for your restaurant and track all activities over any period of time, whether on a daily, monthly, or yearly basis.</div>
                <div class=\"sectionP\">To explore more of this tool, go to the ‘Dashboard’ section of the control panel, then the ‘Statistics and Analytics’ subsection, to open a page with an overview of the statistics and analytics section.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>2,
            'help_en_tut_id' =>70,
            'title' => 'How does the analytics tool work?',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">Our analytics tool collects data from orders placed on your website, tracking ordering patterns and trends, customer behavior and preferences for products and their options, and revenue flow from each order type and product.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>3,
            'help_en_tut_id' =>70,
            'title' => 'How can the tool be used?',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">In the statistics and analytics section, you have to first select the time period for which you want to view your performance. You can set the timeframe to be daily, monthly, or yearly using the date pickers provided. You can also (hc: compare current performance) to historical performance, which can help you determine whether your performance has been progressing or declining. </div>
                <div class=\"sectionP\">After selecting the required timeframe, all analytics will be displayed in graphs showing trends and insights.</div>
            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>4,
            'help_en_tut_id' =>70,
            'title' => 'Analytics Insights',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">The analytics are generated to give you insights into different aspects of your restaurant's performance, as shown in the displayed tabs. Each of these tabs benefits you as follows:</div>
                <ul>
                    <li style=\"margin-bottom:.5em;\"><b>The overview tab</b> allows you to view a high-level perspective on how all your restaurant aspects have been performing, all illustrated in donut charts and lists.</li>
                    <li style=\"margin-bottom:.5em;\"><b>(hc: The orders tab)</b> gives you a deep-dive view of your order patterns and trends and the income generated from each (hc: order type).</li>
                    <li style=\"margin-bottom:.5em;\"><b>(hc: The products tab)</b> demonstrates the demand for each of your products as well as the income generated by those products. This allows you to get to know your hero items and devise a strategy to maximize their performance.</li>
                    <li style=\"margin-bottom:.5em;\"><b>(hc: The users tab)</b> enables you to learn about your most profitable users. This allows you to reward your loyal customers by making personalized offers to them.</li>
                    <li style=\"margin-bottom:.5em;\"><b>(hc: The deliveries tab)</b> allows you to see your (hc: delivery accounts') performance and their activities.</li>
                </ul>

            </div>
            ",
        ]);
        array_push($tutsTexts,[
            'sort'=>5,
            'help_en_tut_id' =>70,
            'title' => 'Wrapping Up',
            'html' => "<div class=\"SectionContainer\">
                <div class=\"sectionP\">The statistics and analytics tool is available to view and use from the main accounts only and can be accessed from any device.</div>
            </div>
            ",
        ]);
        help_en_text::insert($tutsTexts);
    }
}
