<?php
namespace App\Models\templates;
///z-index
//header => 120
//popup => 120
class templates_data
{
    public static function fonts(){
        return [
            //latin
            ['name' => 'AdventPro','language' => 'latin'],
            ['name' => 'Akshar','language' => 'latin'],
            ['name' => 'Alegreya','language' => 'latin'],
            ['name' => 'Alexandria','language' => 'latin'],
            ['name' => 'AlumniSans','language' => 'latin'],
            ['name' => 'AndadaPro','language' => 'latin'],
            ['name' => 'Antonio','language' => 'latin'],
            ['name' => 'Anybody','language' => 'latin'],
            ['name' => 'Archivo','language' => 'latin'],
            ['name' => 'ArchivoNarrow','language' => 'latin'],
            ['name' => 'Assistant','language' => 'latin'],
            ['name' => 'BalooBhai2','language' => 'latin'],
            ['name' => 'BigShouldersDisplay','language' => 'latin'],
            ['name' => 'BigShouldersInlineText','language' => 'latin'],
            ['name' => 'BigShouldersText','language' => 'latin'],
            ['name' => 'Bitter','language' => 'latin'],
            ['name' => 'BodoniModa','language' => 'latin'],
            ['name' => 'Brygada1918','language' => 'latin'],
            ['name' => 'Cabin','language' => 'latin'],
            ['name' => 'Cairo','language' => 'latin'],
            ['name' => 'Changa','language' => 'latin'],
            ['name' => 'Chivo','language' => 'latin'],
            ['name' => 'Cinzel','language' => 'latin'],
            ['name' => 'Comfortaa','language' => 'latin'],
            ['name' => 'Cormorant','language' => 'latin'],
            ['name' => 'CrimsonPro','language' => 'latin'],
            ['name' => 'Domine','language' => 'latin'],
            ['name' => 'EBGaramond','language' => 'latin'],
            ['name' => 'Eczar','language' => 'latin'],
            ['name' => 'EncodeSans','language' => 'latin'],
            ['name' => 'Exo','language' => 'latin'],
            ['name' => 'Exo2','language' => 'latin'],
            ['name' => 'ExpletusSans','language' => 'latin'],
            ['name' => 'FamiljenGrotesk','language' => 'latin'],
            ['name' => 'Faustina','language' => 'latin'],
            ['name' => 'FrankRuhlLibre','language' => 'latin'],
            ['name' => 'Gelasio','language' => 'latin'],
            ['name' => 'GemunuLibre','language' => 'latin'],
            ['name' => 'Genos','language' => 'latin'],
            ['name' => 'Geologica','language' => 'latin'],
            ['name' => 'GrenzeGotisch','language' => 'latin'],
            ['name' => 'Hahmlet','language' => 'latin'],
            ['name' => 'Handjet','language' => 'latin'],
            ['name' => 'HedvigLettersSerif','language' => 'latin'],
            ['name' => 'IbarraRealNova','language' => 'latin'],
            ['name' => 'Imbue','language' => 'latin'],
            ['name' => 'Inter','language' => 'latin'],
            ['name' => 'Jaro','language' => 'latin'],
            ['name' => 'JosefinSans','language' => 'latin'],
            ['name' => 'Jura','language' => 'latin'],
            ['name' => 'Kalnia','language' => 'latin'],
            ['name' => 'Karla','language' => 'latin'],
            ['name' => 'KodeMono','language' => 'latin'],
            ['name' => 'Kreon','language' => 'latin'],
            ['name' => 'Labrada','language' => 'latin'],
            ['name' => 'Lemonada','language' => 'latin'],
            ['name' => 'Lexend','language' => 'latin'],
            ['name' => 'LexendMega','language' => 'latin'],
            ['name' => 'LibreBodoni','language' => 'latin'],
            ['name' => 'Literata','language' => 'latin'],
            ['name' => 'Lora','language' => 'latin'],
            ['name' => 'Manuale','language' => 'latin'],
            ['name' => 'Marhey','language' => 'latin'],
            ['name' => 'MarkaziText','language' => 'latin'],
            ['name' => 'MavenPro','language' => 'latin'],
            ['name' => 'MuseoModerno','language' => 'latin'],
            ['name' => 'Newsreader','language' => 'latin'],
            ['name' => 'NotoSans','language' => 'latin'],
            ['name' => 'NotoSerif','language' => 'latin'],
            ['name' => 'NotoSerifDisplay','language' => 'latin'],
            ['name' => 'Nunito','language' => 'latin'],
            ['name' => 'Ojuju','language' => 'latin'],
            ['name' => 'OpenSans','language' => 'latin'],
            ['name' => 'Orbitron','language' => 'latin'],
            ['name' => 'Oswald','language' => 'latin'],
            ['name' => 'Outfit','language' => 'latin'],
            ['name' => 'Oxanium','language' => 'latin'],
            ['name' => 'Petrona','language' => 'latin'],
            ['name' => 'Phudu','language' => 'latin'],
            ['name' => 'Piazzolla','language' => 'latin'],
            ['name' => 'PixelifySans','language' => 'latin'],
            ['name' => 'Platypi','language' => 'latin'],
            ['name' => 'Playfair','language' => 'latin'],
            ['name' => 'PlayfairDisplay','language' => 'latin'],
            ['name' => 'PlaypenSans','language' => 'latin'],
            ['name' => 'Podkova','language' => 'latin'],
            ['name' => 'PoltawskiNowy','language' => 'latin'],
            ['name' => 'Quicksand','language' => 'latin'],
            ['name' => 'RadioCanadaBig','language' => 'latin'],
            ['name' => 'Rasa','language' => 'latin'],
            ['name' => 'Recursive','language' => 'latin'],
            ['name' => 'RedRose','language' => 'latin'],
            ['name' => 'REM','language' => 'latin'],
            ['name' => 'RobotoSerif','language' => 'latin'],
            ['name' => 'Rubik','language' => 'latin'],
            ['name' => 'Saira','language' => 'latin'],
            ['name' => 'ShantellSans','language' => 'latin'],
            ['name' => 'Signika','language' => 'latin'],
            ['name' => 'Sixtyfour','language' => 'latin'],
            ['name' => 'SmoochSans','language' => 'latin'],
            ['name' => 'SometypeMono','language' => 'latin'],
            ['name' => 'SourceSerif4','language' => 'latin'],
            ['name' => 'SpaceGrotesk','language' => 'latin'],
            ['name' => 'SplineSansMono','language' => 'latin'],
            ['name' => 'StickNoBills','language' => 'latin'],
            ['name' => 'STIXTwoText','language' => 'latin'],
            ['name' => 'Syne','language' => 'latin'],
            ['name' => 'Teko','language' => 'latin'],
            ['name' => 'Tektur','language' => 'latin'],
            ['name' => 'Texturina','language' => 'latin'],
            ['name' => 'TiltNeon','language' => 'latin'],
            ['name' => 'TiltPrism','language' => 'latin'],
            ['name' => 'TiltWarp','language' => 'latin'],
            ['name' => 'Truculenta','language' => 'latin'],
            ['name' => 'UbuntuSans','language' => 'latin'],
            ['name' => 'Unbounded','language' => 'latin'],
            ['name' => 'Vollkorn','language' => 'latin'],
            ['name' => 'WixMadeforDisplay','language' => 'latin'],
            ['name' => 'Workbench','language' => 'latin'],
            ['name' => 'Yrsa','language' => 'latin'],
            ['name' => 'YsabeauOffice','language' => 'latin'],
            ['name' => 'IndieFlower','language' => 'latin'],
            ['name' => 'Arizonia','language' => 'latin'],
            ['name' => 'Cookie','language' => 'latin'],
            ['name' => 'DeliciousHandrawn','language' => 'latin'],
            ['name' => 'DeliusUnicase','language' => 'latin'],
            ['name' => 'Englebert','language' => 'latin'],
            ['name' => 'Festive','language' => 'latin'],
            ['name' => 'Flavors','language' => 'latin'],
            ['name' => 'GochiHand','language' => 'latin'],
            ['name' => 'Grandstander','language' => 'latin'],
            ['name' => 'HachiMaruPop','language' => 'latin'],
            ['name' => 'Kings','language' => 'latin'],
            ['name' => 'Kristi','language' => 'latin'],
            ['name' => 'LuckiestGuy','language' => 'latin'],
            ['name' => 'Neonderthaw','language' => 'latin'],
            ['name' => 'Qwigley','language' => 'latin'],
            ['name' => 'Rancho','language' => 'latin'],
            ['name' => 'RockSalt','language' => 'latin'],
            ['name' => 'Satisfy','language' => 'latin'],
            ['name' => 'ShadowsIntoLight','language' => 'latin'],
            ['name' => 'Updock','language' => 'latin'],
            ['name' => 'WalterTurncoat','language' => 'latin'],
            ['name' => 'ZenLoop','language' => 'latin'],
            ['name' => 'Zeyada','language' => 'latin'],
            ///chinese
            ['name' => 'MaShanZheng','language' => 'chinese'],
            ['name' => 'NotoSansHK','language' => 'chinese'],
            ['name' => 'ZCOOLQingKeHuangYou','language' => 'chinese'],
            ['name' => 'ZhiMangXing','language' => 'chinese'],
            ['name' => 'ChocolateClassicalSans','language' => 'chinese'],
            ///japanese
            ['name' => 'Murecho','language' => 'japanese'],
            ['name' => 'NotoSerifJP','language' => 'japanese'],
            ['name' => 'RampartOne','language' => 'japanese'],
            ['name' => 'MPLUS1p','language' => 'japanese'],
            //korean
            ['name' => 'NotoSerifKR','language' => 'korean'],
            ['name' => 'Hahmlet_korean','language' => 'korean'],
            //cyrillic
            ['name' => 'Caveat','language' => 'cyrillic'],
            ['name' => 'Manrope','language' => 'cyrillic'],
            ['name' => 'Nunito_cyrillic','language' => 'cyrillic'],
            ['name' => 'Oswald_cyrillic','language' => 'cyrillic'],
            ['name' => 'YanoneKaffeesatz','language' => 'cyrillic'],
            //greek
            ['name' => 'Brygada1918_greek','language' => 'greek'],
            ['name' => 'Comfortaa_greek','language' => 'greek'],
            ['name' => 'SofiaSansCondensed','language' => 'greek'],
            ['name' => 'Vollkorn_greek','language' => 'greek'],
            ///arabic
            ['name' => 'Alexandria_arabic','language' => 'arabic'],
            ['name' => 'Cairo_arabic','language' => 'arabic'],
            ['name' => 'Changa_arabic','language' => 'arabic'],
            ['name' => 'ElMessiri','language' => 'arabic'],
            ['name' => 'Kufam','language' => 'arabic'],
            ['name' => 'Lemonada_arabic','language' => 'arabic'],
            ['name' => 'Mada','language' => 'arabic'],
            ['name' => 'Marhey_arabic','language' => 'arabic'],
            ['name' => 'NotoNastaliqUrdu','language' => 'arabic'],
            ['name' => 'ReemKufi','language' => 'arabic'],
            //indian
            ['name' => 'NotoSans_indian','language' => 'indian'],
            ['name' => 'TiroDevanagariHindi','language' => 'indian'],
            ['name' => 'BalooDa2','language' => 'indian'],

        ];
    }
    public static function transitions(){
        return [
            'no_animation' => '',
            'fade' => '.fade{ animation-name: fade; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade {0%{opacity:0}100%{opacity: 1}}',
            'zoom' => '.zoom{ animation-name: zoom; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes zoom {0%{opacity:0;transform: scale(0.9);}100%{opacity: 1;transform: scale(1);}}',
            'slide_up' => '.slide_up{ animation-name: slide_up; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up {0%{opacity:0;transform: translateY(10px);}100%{opacity: 1;transform: translateY(0px);}}',
            'slide_down' => '.slide_down{ animation-name: slide_down; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down {0%{opacity:0;transform: translateY(-10px);}100%{opacity: 1;transform: translateY(0px);}}',
            'slide_left' => '.slide_left{ animation-name: slide_left; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left {0%{opacity:0;transform: translateX(10px);}100%{opacity: 1;transform: translateX(0px);}}',
            'slide_right' => '.slide_right{ animation-name: slide_right; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right {0%{opacity:0;transform: translateX(-10px);}100%{opacity: 1;transform: translateX(0px);}} ',
        ];
    }
    
    public static function scroll_animations(){
        return [
            'no_animation' => '',
            
        ];
    }

    public static function page_transitions(){
        return [
            'fade' => '.fade_out{ animation-name: fade_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade_out {0%{opacity:1}100%{opacity: 0}} .fade_in{ animation-name: fade_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade_in {0%{opacity:0}100%{opacity: 1}}',

            'slide_up_down' => '.slide_up_down_out{ animation-name: slide_up_down_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_down_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(-50px);}} .slide_up_down_in{ animation-name: slide_up_down_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_down_in {0%{opacity:0;transform: translateY(-50px);}100%{opacity: 1;transform: translateY(0px);}}',

            'slide_up_up' => '.slide_up_up_out{ animation-name: slide_up_up_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_up_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(-50px);}} .slide_up_up_in{ animation-name: slide_up_up_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_up_in {0%{opacity:0;transform: translateY(50px);}100%{opacity: 1;transform: translateY(-0px);}}',

            'slide_down_up' => '.slide_down_up_out{ animation-name: slide_down_up_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_up_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(50px);}} .slide_down_up_in{ animation-name: slide_down_up_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_up_in {0%{opacity:0;transform: translateY(50px);}100%{opacity: 1;transform: translateY(0px);}}',

            'slide_down_down' => '.slide_down_down_out{ animation-name: slide_down_down_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_down_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(50px);}} .slide_down_down_in{ animation-name: slide_down_down_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_down_in {0%{opacity:0;transform: translateY(-50px);}100%{opacity: 1;transform: translateY(-0px);}}',

            'slide_left_right' => '.slide_left_right_out{ animation-name: slide_left_right_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_right_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(-50px);}} .slide_left_right_in{ animation-name: slide_left_right_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_right_in {0%{opacity:0;transform: translateX(-50px);}100%{opacity: 1;transform: translateX(0px);}}',

            'slide_left_left' => '.slide_left_left_out{ animation-name: slide_left_left_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_left_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(-50px);}} .slide_left_left_in{ animation-name: slide_left_left_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_left_in {0%{opacity:0;transform: translateX(50px);}100%{opacity: 1;transform: translateX(-0px);}}',

            'slide_right_left' => '.slide_right_left_out{ animation-name: slide_right_left_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_left_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(50px);}} .slide_right_left_in{ animation-name: slide_right_left_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_left_in {0%{opacity:0;transform: translateX(50px);}100%{opacity: 1;transform: translateX(0px);}}',

            'slide_right_right' => '.slide_right_right_out{ animation-name: slide_right_right_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_right_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(50px);}} .slide_right_right_in{ animation-name: slide_right_right_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_right_in {0%{opacity:0;transform: translateX(-50px);}100%{opacity: 1;transform: translateX(-0px);}}',
        ];
    }


}
