<?php
namespace App\Models\templates;
///z-index
//header => 120
//popup => 120
class templates_data
{
    public static function transitions(){
        return [
            'no_animation' => '',
            'fade' => '.fade{ animation-name: fade; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade {0%{opacity:0}100%{opacity: 1}}',
            'zoom' => '.zoom{ animation-name: zoom; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes zoom {0%{opacity:0;transform: scale(0.9);}100%{opacity: 1;transform: scale(1);}}',
            'slide_up' => '.slide_up{ animation-name: slide_up; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up {0%{opacity:0;transform: translateY(10px);}100%{opacity: 1;transform: translateY(0px);}}',
            'slide_down' => '.slide_down{ animation-name: slide_down; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down {0%{opacity:0;transform: translateY(-10px);}100%{opacity: 1;transform: translateY(0px);}}',
            'slide_left' => '.slide_left{ animation-name: slide_left; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left {0%{opacity:0;transform: translateX(10px);}100%{opacity: 1;transform: translateX(0px);}}',
            'slide_right' => '.slide_right{ animation-name: slide_right; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right {0%{opacity:0;transform: translateX(-10px);}100%{opacity: 1;transform: translateX(0px);}} ',
        ];
    }

    public static function page_transitions(){
        return [
            'fade' => '.fade_out{ animation-name: fade_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade_out {0%{opacity:1}100%{opacity: 0}} .fade_in{ animation-name: fade_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes fade_in {0%{opacity:0}100%{opacity: 1}}',

            'slide_up_down' => '.slide_up_down_out{ animation-name: slide_up_down_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_down_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(-50px);}} .slide_up_down_in{ animation-name: slide_up_down_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_down_in {0%{opacity:0;transform: translateY(-50px);}100%{opacity: 1;transform: translateY(0px);}}',

            'slide_up_up' => '.slide_up_up_out{ animation-name: slide_up_up_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_up_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(-50px);}} .slide_up_up_in{ animation-name: slide_up_up_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_up_up_in {0%{opacity:0;transform: translateY(50px);}100%{opacity: 1;transform: translateY(-0px);}}',

            'slide_down_up' => '.slide_down_up_out{ animation-name: slide_down_up_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_up_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(50px);}} .slide_down_up_in{ animation-name: slide_down_up_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_up_in {0%{opacity:0;transform: translateY(50px);}100%{opacity: 1;transform: translateY(0px);}}',

            'slide_down_down' => '.slide_down_down_out{ animation-name: slide_down_down_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_down_out {0%{opacity:1;transform: translateY(0px);}100%{opacity: 0;transform: translateY(50px);}} .slide_down_down_in{ animation-name: slide_down_down_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_down_down_in {0%{opacity:0;transform: translateY(-50px);}100%{opacity: 1;transform: translateY(-0px);}}',

            'slide_left_right' => '.slide_left_right_out{ animation-name: slide_left_right_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_right_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(-50px);}} .slide_left_right_in{ animation-name: slide_left_right_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_right_in {0%{opacity:0;transform: translateX(-50px);}100%{opacity: 1;transform: translateX(0px);}}',

            'slide_left_left' => '.slide_left_left_out{ animation-name: slide_left_left_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_left_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(-50px);}} .slide_left_left_in{ animation-name: slide_left_left_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_left_left_in {0%{opacity:0;transform: translateX(50px);}100%{opacity: 1;transform: translateX(-0px);}}',

            'slide_right_left' => '.slide_right_left_out{ animation-name: slide_right_left_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_left_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(50px);}} .slide_right_left_in{ animation-name: slide_right_left_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_left_in {0%{opacity:0;transform: translateX(50px);}100%{opacity: 1;transform: translateX(0px);}}',

            'slide_right_right' => '.slide_right_right_out{ animation-name: slide_right_right_out; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_right_out {0%{opacity:1;transform: translateX(0px);}100%{opacity: 0;transform: translateX(50px);}} .slide_right_right_in{ animation-name: slide_right_right_in; animation-timing-function: ease-in-out; animation-iteration-count: 1; } @keyframes slide_right_right_in {0%{opacity:0;transform: translateX(-50px);}100%{opacity: 1;transform: translateX(-0px);}}',
        ];
    }

    public static function loading_spinners(){
        return [
            '0' => [
                'colors' => 2,
                'elem' => '<div class="loading_spinner_0_:size:"></div>',
                'css' => '.loading_spinner_0_S{ border: 4px solid var(--loading_spinner_c2); border-top: 4px solid var(--loading_spinner_c1); border-radius: 50%; width: 22px; height: 22px; animation: loading_spinner_0 2s linear infinite; } .loading_spinner_0_M{ border: 6px solid var(--loading_spinner_c2); border-top: 6px solid var(--loading_spinner_c1); border-radius: 50%; width: 38px; height: 38px; animation: loading_spinner_0 2s linear infinite; } .loading_spinner_0_L{ border: 8px solid var(--loading_spinner_c2); border-top: 8px solid var(--loading_spinner_c1); border-radius: 50%; width: 54px; height: 54px; animation: loading_spinner_0 2s linear infinite; } @keyframes loading_spinner_0 { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } } ',
            ],
            '1' => [
                'colors' => 1,
                'elem' => '<div class="loading_spinner_1_:size:"><div></div><div></div><div></div><div></div></div>',
                'css' => ' .loading_spinner_1_S { position: relative; width: 30px; height:30px; } .loading_spinner_1_S div { display: block; position: absolute; width: 22px; height: 22px; border: 4px solid var(--loading_spinner_c1); border-radius: 50%; animation: loading_spinner_1 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite; border-color: var(--loading_spinner_c1) transparent transparent transparent; } .loading_spinner_1_S div:nth-child(1) { animation-delay: -0.45s; } .loading_spinner_1_S div:nth-child(2) { animation-delay: -0.3s; } .loading_spinner_1_S div:nth-child(3) { animation-delay: -0.15s; } .loading_spinner_1_M { position: relative; width: 50px; height: 50px; } .loading_spinner_1_M div { display: block; position: absolute; width: 38px; height: 38px; border: 6px solid var(--loading_spinner_c1); border-radius: 50%; animation: loading_spinner_1 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite; border-color: var(--loading_spinner_c1) transparent transparent transparent; } .loading_spinner_1_M div:nth-child(1) { animation-delay: -0.45s; } .loading_spinner_1_M div:nth-child(2) { animation-delay: -0.3s; } .loading_spinner_1_M div:nth-child(3) { animation-delay: -0.15s; } .loading_spinner_1_L { position: relative; width: 70px; height: 70px; } .loading_spinner_1_L div { display: block; position: absolute; width: 54px; height: 54px; border: 8px solid var(--loading_spinner_c1); border-radius: 50%; animation: loading_spinner_1 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite; border-color: var(--loading_spinner_c1) transparent transparent transparent; } .loading_spinner_1_L div:nth-child(1) { animation-delay: -0.45s; } .loading_spinner_1_L div:nth-child(2) { animation-delay: -0.3s; } .loading_spinner_1_L div:nth-child(3) { animation-delay: -0.15s; } @keyframes loading_spinner_1 { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } } ',
            ],
            '2' => [
                'colors' => 2,
                'elem' => '<div class="loading_spinner_2_:size:"><div></div><div></div></div>',
                'css' => ' .loading_spinner_2_S { position: relative; width: 30px; height: 30px; } .loading_spinner_2_S div { position: absolute; border: 2px solid var(--loading_spinner_c1); border-color:var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); opacity: 1; border-radius: 50%; animation: loading_spinner_2_S 1s cubic-bezier(0, 0.2, 0.8, 1) infinite; } .loading_spinner_2_S div:nth-child(2) { animation-delay: -0.5s; } @keyframes loading_spinner_2_S { 0% { top: 13px; left: 13px; width: 0; height: 0; opacity: 1; transform: rotateZ(0deg); } 100% { top: 0; left: 0; width: 26px; height: 26px; opacity: 0; transform: rotateZ(360deg); } } .loading_spinner_2_M { display: block; position: relative; width: 50px; height: 50px; } .loading_spinner_2_M div { position: absolute; border: 3px solid var(--loading_spinner_c1); border-color:var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); opacity: 1; border-radius: 50%; animation: loading_spinner_2_M 1s cubic-bezier(0, 0.2, 0.8, 1) infinite; } .loading_spinner_2_M div:nth-child(2) { animation-delay: -0.5s; } @keyframes loading_spinner_2_M { 0% { top: 22px; left: 22px; width: 0; height: 0; opacity: 1; transform: rotateZ(0deg); } 100% { top: 0; left: 0; width: 44px; height: 44px; opacity: 0; transform: rotateZ(360deg); } } .loading_spinner_2_L { display: block; position: relative; width: 70px; height: 70px; } .loading_spinner_2_L div { position: absolute; border: 4px solid var(--loading_spinner_c1); border-color:var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); opacity: 1; border-radius: 50%; animation: loading_spinner_2_L 1s cubic-bezier(0, 0.2, 0.8, 1) infinite; } .loading_spinner_2_L div:nth-child(2) { animation-delay: -0.5s; } @keyframes loading_spinner_2_L { 0% { top: 31px; left: 31px; width: 0; height: 0; opacity: 1; transform: rotateZ(0deg); } 100% { top: 0; left: 0; width: 62px; height: 62px; opacity: 0; transform: rotateZ(360deg); } } ',
            ],
            '3' => [
                'colors' => 2,
                'elem' => '<div class="loading_spinner_3_:size:"></div>',
                'css' => ".loading_spinner_3_S { position: relative; width: 30px; height: 30px; } .loading_spinner_3_S:after { content: ''; display: block; width: 26px; height: 26px; border-radius: 50%; border: 2px solid var(--loading_spinner_c1); border-color: var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); animation: loading_spinner_3 1.2s linear infinite; } .loading_spinner_3_M { position: relative; width: 50px; height: 50px; } .loading_spinner_3_M:after { content: ''; display: block; width: 42px; height: 42px; border-radius: 50%; border: 4px solid var(--loading_spinner_c1); border-color: var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); animation: loading_spinner_3 1.2s linear infinite; } .loading_spinner_3_L { position: relative; width: 70px; height: 70px; } .loading_spinner_3_L:after { content: ''; display: block; width: 60px; height: 60px; border-radius: 50%; border: 5px solid var(--loading_spinner_c1); border-color: var(--loading_spinner_c1) var(--loading_spinner_c2) var(--loading_spinner_c1) var(--loading_spinner_c2); animation: loading_spinner_3 1.2s linear infinite; } @keyframes loading_spinner_3 { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } } ",
            ],
            '5' => [
                'colors' => 1,
                'elem' => '<div class="loading_spinner_5_:size:"><div class="dot1"></div><div class="dot2"></div><div class="dot3"></div></div>',
                'css' => '.loading_spinner_5_S { position: relative; height:30px; width:30px; } .loading_spinner_5_S div { margin:10px 0; width: 10px; height: 10px; background-color: var(--loading_spinner_c1); border-radius: 100%; display: inline-block; animation: loading_spinner_5 1.2s infinite ease-in-out; } .loading_spinner_5_S .dot2 {animation-delay: -0.3s;} .loading_spinner_5_S .dot3 {animation-delay: -0.6s;} .loading_spinner_5_M { position: relative; height:50px; width:50px; } .loading_spinner_5_M div { margin: 17px 0; width: 16px; height: 16px; background-color: var(--loading_spinner_c1); border-radius: 100%; display: inline-block; animation: loading_spinner_5 1.2s infinite ease-in-out; } .loading_spinner_5_M .dot2 {animation-delay: -0.3s;} .loading_spinner_5_M .dot3 {animation-delay: -0.6s;} .loading_spinner_5_L { position: relative; height:70px; width:70px; } .loading_spinner_5_L div { margin: 25px 0; width: 20px; height: 20px; background-color: var(--loading_spinner_c1); border-radius: 100%; display: inline-block; animation: loading_spinner_5 1.2s infinite ease-in-out; } .loading_spinner_5_L .dot2 {animation-delay: -0.3s;} .loading_spinner_5_L .dot3 {animation-delay: -0.6s;} @keyframes loading_spinner_5 {0%, 100% {transform: scale(0);}50% {transform: scale(1);}} ',
            ],
            '6' => [
                'colors' => 1,
                'elem' => '<div class="loading_spinner_6_:size:"><div></div><div></div><div></div><div></div></div>',
                'css' => ' .loading_spinner_6_S{ position: relative; height:30px; width:30px; } .loading_spinner_6_S div{ margin: 11.5px 1.5px; width: 7px; height: 7px; position: absolute; border-radius: 50%; background: var(--loading_spinner_c1); animation-timing-function: cubic-bezier(0, 1, 1, 0); } .loading_spinner_6_S div:nth-child(1) { left:0px; animation: loading_spinner_6_S_1 0.6s infinite; } .loading_spinner_6_S div:nth-child(2) { left: 0px; animation: loading_spinner_6_S_2 0.6s infinite; } .loading_spinner_6_S div:nth-child(3) { left: 10px; animation: loading_spinner_6_S_2 0.6s infinite; } .loading_spinner_6_S div:nth-child(4) { left: 20px; animation: loading_spinner_6_S_3 0.6s infinite; } @keyframes loading_spinner_6_S_1 {0% {transform: scale(0);}100% {transform: scale(1);}} @keyframes loading_spinner_6_S_3 {0% {transform: scale(1);}100% {transform: scale(0);}} @keyframes loading_spinner_6_S_2 {0% {transform: translate(0, 0);}100% {transform: translate(10px, 0);}} .loading_spinner_6_M{ position: relative; height:50px; width:50px; } .loading_spinner_6_M div{ margin: 17.5px 2px; width: 11px; height: 11px; position: absolute; border-radius: 50%; background: var(--loading_spinner_c1); animation-timing-function: cubic-bezier(0, 1, 1, 0); } .loading_spinner_6_M div:nth-child(1) { left:0px; animation: loading_spinner_6_M_1 0.6s infinite; } .loading_spinner_6_M div:nth-child(2) { left: 0px; animation: loading_spinner_6_M_2 0.6s infinite; } .loading_spinner_6_M div:nth-child(3) { left: 15px; animation: loading_spinner_6_M_2 0.6s infinite; } .loading_spinner_6_M div:nth-child(4) { left: 30px; animation: loading_spinner_6_M_3 0.6s infinite; } @keyframes loading_spinner_6_M_1 {0% {transform: scale(0);}100% {transform: scale(1);}} @keyframes loading_spinner_6_M_3 {0% {transform: scale(1);}100% {transform: scale(0);}} @keyframes loading_spinner_6_M_2 {0% {transform: translate(0, 0);}100% {transform: translate(15px, 0);}} .loading_spinner_6_L{ position: relative; height:70px; width:70px; } .loading_spinner_6_L div{ margin: 26.75px 3px; width: 16.5px; height: 16.5px; position: absolute; border-radius: 50%; background: var(--loading_spinner_c1); animation-timing-function: cubic-bezier(0, 1, 1, 0); } .loading_spinner_6_L div:nth-child(1) { left:0px; animation: loading_spinner_6_L_1 0.6s infinite; } .loading_spinner_6_L div:nth-child(2) { left: 0px; animation: loading_spinner_6_L_2 0.6s infinite; } .loading_spinner_6_L div:nth-child(3) { left: 23px; animation: loading_spinner_6_L_2 0.6s infinite; } .loading_spinner_6_L div:nth-child(4) { left: 46px; animation: loading_spinner_6_L_3 0.6s infinite; } @keyframes loading_spinner_6_L_1 {0% {transform: scale(0);}100% {transform: scale(1);}} @keyframes loading_spinner_6_L_3 {0% {transform: scale(1);}100% {transform: scale(0);}} @keyframes loading_spinner_6_L_2 {0% {transform: translate(0, 0);}100% {transform: translate(23px, 0);}} ',
            ],
        ];
    }


}
