<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use stdClass;

class americanDiner extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $americanDiner = new stdClass();
        $americanDiner->domainName = 'americandiner';
        $americanDiner->template = 2;
        $americanDiner->website_names = [
            'en' => 'American Diner',
            'ar' => 'أمريكان داينر',
            'fr' => 'Dîner américain',
            'de' => 'Amerikanisches Diner',
            'it' => 'Cena americana',
            'es' => 'Restaurante americano',
            'ua' => 'Американська закусочна',
            'ru' => '',
        ];
        $americanDiner->intro = [
            'en' => 'Your classic talk-of-the-town diner',
            'ar' => 'حديثك الكلاسيكي عن عشاء البلدة',
            'fr' => 'Votre restaurant classique qui parle de la ville',
            'de' => 'Ihr klassisches Talk-of-the-town-Diner',
            'it' => 'Il tuo classico ristorante di conversazione della città',
            'es' => 'Tu clásico restaurante de conversación de la ciudad',
            'ua' => 'Ваша класична забігайлівка',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'original-burgers',
                'imgUrl' => 'imgs/demo/americandiner/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/americandiner/cat1_thumbnail.webp',
                'name_en' => 'Original Burgers',
                'name_ar' => 'اوريجينال برجر',
                'name_fr' => 'Burgers originaux',
                'name_it' => 'Hamburger originali',
                'name_de' => 'Ursprüngliche Burger',
                'name_es' => 'Hamburguesas Originales',
                'name_ua' => 'Оригінальні бургери',
                'products' => [
                    [
                        'name' => 'smokehouse-bbq',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/americandiner/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Smokehouse BBQ',
                        'name_ar' => 'سموك هاوس باربكيو',
                        'name_fr' => 'Barbecue fumoir',
                        'name_it' => 'Barbecue all\'affumicatoio',
                        'name_de' => 'Räucherei BBQ',
                        'name_es' => 'barbacoa ahumadero',
                        'name_ua' => 'Коптильня барбекю',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Grande',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheeseburger',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/americandiner/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Cheeseburger',
                        'name_ar' => 'تشيز برجر',
                        'name_fr' => 'Hamburger au fromage',
                        'name_it' => 'Hamburger al formaggio',
                        'name_de' => 'Käseburger',
                        'name_es' => 'Hamburguesa con queso',
                        'name_ua' => 'Чізбургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Grande',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'bacon-cheddar',
                        'price' => 18,
                        'imgUrl' => 'imgs/demo/americandiner/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Bacon Cheddar',
                        'name_ar' => 'شيدر بيكون',
                        'name_fr' => 'Cheddar au bacon',
                        'name_it' => 'Pancetta Cheddar',
                        'name_de' => 'Speck-Cheddar',
                        'name_es' => 'tocino cheddar',
                        'name_ua' => 'Бекон Чеддер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Grande',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'classic-burger',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/americandiner/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Classic Burger',
                        'name_ar' => 'برجر كلاسيك',
                        'name_fr' => 'Hamburger classique',
                        'name_it' => 'Hamburger Classico',
                        'name_de' => 'Klassischer Burger',
                        'name_es' => 'Hamburguesa Clásica',
                        'name_ua' => 'Класичний бургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Grande',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],

                ]
            ],
            [
                'name' => 'breakfast',
                'imgUrl' => 'imgs/demo/americandiner/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/americandiner/cat2_thumbnail.webp',
                'name_en' => 'Breakfast',
                'name_ar' => 'إفطار',
                'name_fr' => 'Déjeuner',
                'name_it' => 'Prima colazione',
                'name_de' => 'Frühstück',
                'name_es' => 'Desayuno',
                'name_ua' => 'Сніданок',
                'products' => [
                    [
                        'name' => 'waffles',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/americandiner/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Waffles',
                        'name_ar' => 'بسكويتات الوفل',
                        'name_fr' => 'Gaufres',
                        'name_it' => 'Waffle',
                        'name_de' => 'Waffeln',
                        'name_es' => 'gofres',
                        'name_ua' => 'Вафлі',
                        'options' => [
                            [
                                'name' => 'syrup',
                                'name_en' => 'Syrup',
                                'name_ar' => 'الشراب',
                                'name_fr' => 'Sirop',
                                'name_it' => 'Sciroppo',
                                'name_de' => 'Sirup',
                                'name_es' => 'Jarabe',
                                'name_ua' => 'Сироп',
                                'selections' => [
                                    [
                                        'name' => 'maple-syrup',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Maple syrup',
                                        'name_ar' => 'شراب القيقب',
                                        'name_fr' => 'sirop d\'érable',
                                        'name_it' => 'sciroppo d\'acero',
                                        'name_de' => 'Ahornsirup',
                                        'name_es' => 'miel de maple',
                                        'name_ua' => 'кленовий сироп',
                                    ],
                                    [
                                        'name' => 'strawberry-syrup',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry syrup',
                                        'name_ar' => 'شراب الفراولة',
                                        'name_fr' => 'Sirop de fraise',
                                        'name_it' => 'Sciroppo di fragole',
                                        'name_de' => 'Erdbeersirup',
                                        'name_es' => 'Jarabe de fresa',
                                        'name_ua' => 'Полуничний сироп',
                                    ],
                                    [
                                        'name' => 'honey-syrup',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Honey syrup',
                                        'name_ar' => 'شراب العسل',
                                        'name_fr' => 'Sirop de miel',
                                        'name_it' => 'Sciroppo di miele',
                                        'name_de' => 'Honigsirup',
                                        'name_es' => 'Jarabe de miel',
                                        'name_ua' => 'Медовий сироп',
                                    ],
                                    [
                                        'name' => 'buttermilk-syrup',
                                        'price' => 0.25,
                                        'isDefault' => false,
                                        'name_en' => 'Buttermilk syrup',
                                        'name_ar' => 'شراب اللبن',
                                        'name_fr' => 'Sirop de babeurre',
                                        'name_it' => 'Sciroppo di latticello',
                                        'name_de' => 'Buttermilchsirup',
                                        'name_es' => 'Jarabe de suero de leche',
                                        'name_ua' => 'Пахта сироп',
                                    ],
                                    [
                                        'name' => 'chocolate-syrup',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Chocolate syrup',
                                        'name_ar' => 'شراب الشوكولاته',
                                        'name_fr' => 'Sirop au chocolat',
                                        'name_it' => 'Sciroppo di cioccolato',
                                        'name_de' => 'Schokoladensirup',
                                        'name_es' => 'Sirope de chocolate',
                                        'name_ua' => 'Шоколадний сироп',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'pancakes',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/americandiner/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Pancakes',
                        'name_ar' => 'بان كيك',
                        'name_fr' => 'Crêpes',
                        'name_it' => 'Pancakes',
                        'name_de' => 'Pfannkuchen',
                        'name_es' => 'Panqueques',
                        'name_ua' => 'млинці',
                        'options' => [
                            [
                                'name' => 'syrup',
                                'name_en' => 'Syrup',
                                'name_ar' => 'الشراب',
                                'name_fr' => 'Sirop',
                                'name_it' => 'Sciroppo',
                                'name_de' => 'Sirup',
                                'name_es' => 'Jarabe',
                                'name_ua' => 'Сироп',
                                'selections' => [
                                    [
                                        'name' => 'maple-syrup',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Maple syrup',
                                        'name_ar' => 'شراب القيقب',
                                        'name_fr' => 'sirop d\'érable',
                                        'name_it' => 'sciroppo d\'acero',
                                        'name_de' => 'Ahornsirup',
                                        'name_es' => 'miel de maple',
                                        'name_ua' => 'кленовий сироп',
                                    ],
                                    [
                                        'name' => 'strawberry-syrup',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry syrup',
                                        'name_ar' => 'شراب الفراولة',
                                        'name_fr' => 'Sirop de fraise',
                                        'name_it' => 'Sciroppo di fragole',
                                        'name_de' => 'Erdbeersirup',
                                        'name_es' => 'Jarabe de fresa',
                                        'name_ua' => 'Полуничний сироп',
                                    ],
                                    [
                                        'name' => 'honey-syrup',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Honey syrup',
                                        'name_ar' => 'شراب العسل',
                                        'name_fr' => 'Sirop de miel',
                                        'name_it' => 'Sciroppo di miele',
                                        'name_de' => 'Honigsirup',
                                        'name_es' => 'Jarabe de miel',
                                        'name_ua' => 'Медовий сироп',
                                    ],
                                    [
                                        'name' => 'buttermilk-syrup',
                                        'price' => 0.25,
                                        'isDefault' => false,
                                        'name_en' => 'Buttermilk syrup',
                                        'name_ar' => 'شراب اللبن',
                                        'name_fr' => 'Sirop de babeurre',
                                        'name_it' => 'Sciroppo di latticello',
                                        'name_de' => 'Buttermilchsirup',
                                        'name_es' => 'Jarabe de suero de leche',
                                        'name_ua' => 'Пахта сироп',
                                    ],
                                    [
                                        'name' => 'chocolate-syrup',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Chocolate syrup',
                                        'name_ar' => 'شراب الشوكولاته',
                                        'name_fr' => 'Sirop au chocolat',
                                        'name_it' => 'Sciroppo di cioccolato',
                                        'name_de' => 'Schokoladensirup',
                                        'name_es' => 'Sirope de chocolate',
                                        'name_ua' => 'Шоколадний сироп',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'eggs',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/americandiner/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Eggs',
                        'name_ar' => 'بيض',
                        'name_fr' => 'Oeufs',
                        'name_it' => 'Uova',
                        'name_de' => 'Eier',
                        'name_es' => 'Huevos',
                        'name_ua' => 'Яйця',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'all-american-breakfast',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/americandiner/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat2_prod4_thumbnail.webp',
                        'name_en' => 'All-american Breakfast',
                        'name_ar' => 'إفطار جميع الأمريكيين',
                        'name_fr' => 'Petit-déjeuner américain',
                        'name_it' => 'Colazione tutta americana',
                        'name_de' => 'All-amerikanisches Frühstück',
                        'name_es' => 'Desayuno americano',
                        'name_ua' => 'Всеамериканський сніданок',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'sandwiches',
                'imgUrl' => 'imgs/demo/americandiner/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/americandiner/cat3_thumbnail.webp',
                'name_en' => 'Sandwiches',
                'name_ar' => 'شطائر',
                'name_fr' => 'Sandwichs',
                'name_it' => 'Panini',
                'name_de' => 'Belegte Brote',
                'name_es' => 'Sándwiches',
                'name_ua' => 'Бутерброди',
                'products' => [
                    [
                        'name' => 'avocado-chicken-sandwich',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/americandiner/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Avocado Chicken Sandwich',
                        'name_ar' => 'ساندوتش دجاج أفوكادو',
                        'name_fr' => 'Sandwich au poulet à l\'avocat',
                        'name_it' => 'Panino di pollo all\'avocado',
                        'name_de' => 'Avocado-Huhn-Sandwich',
                        'name_es' => 'Sándwich De Pollo Con Aguacate',
                        'name_ua' => 'Сендвіч з куркою з авокадо',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'ham-and-cheese',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/americandiner/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Ham and Cheese',
                        'name_ar' => 'لحم وجبن',
                        'name_fr' => 'Jambon et fromage',
                        'name_it' => 'Prosciutto e formaggio',
                        'name_de' => 'Schinken und Käse',
                        'name_es' => 'Jamón y queso',
                        'name_ua' => 'Шинка і сир',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tuna-sandwich',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/americandiner/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Tuna Sandwich',
                        'name_ar' => 'ساندوتش تونة',
                        'name_fr' => 'Sandwich au thon',
                        'name_it' => 'Panino al tonno',
                        'name_de' => 'Thunfisch Sandwich',
                        'name_es' => 'Sandwich de atún',
                        'name_ua' => 'Сендвіч з тунцем',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'classic-hotdog',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/americandiner/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Classic Hotdog',
                        'name_ar' => 'كلاسيك هوت دوج',
                        'name_fr' => 'Hot-dog classique',
                        'name_it' => 'Hot dog classico',
                        'name_de' => 'Klassischer Hotdog',
                        'name_es' => 'Perrito caliente clásico',
                        'name_ua' => 'Класичний хот-дог',
                        'options' => [

                        ]
                    ],
                    [
                        'name' => 'grilled-chicken',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/americandiner/cat3_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat3_prod5_thumbnail.webp',
                        'name_en' => 'Grilled Chicken',
                        'name_ar' => 'دجاج مشوي',
                        'name_fr' => 'Poulet grillé',
                        'name_it' => 'Pollo grigliato',
                        'name_de' => 'Gegrilltes Hühnchen',
                        'name_es' => 'Pollo a la parrilla',
                        'name_ua' => 'Курка-гриль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],

                ]
            ],
            [
                'name' => 'sides',
                'imgUrl' => 'imgs/demo/americandiner/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/americandiner/cat4_thumbnail.webp',
                'name_en' => 'Sides',
                'name_ar' => 'أطباق جانبية',
                'name_fr' => 'accompagnements plats',
                'name_it' => 'contorni',
                'name_de' => 'Beilagen Gerichte',
                'name_es' => 'guarniciones',
                'name_ua' => 'гарніри',
                'products' => [
                    [
                        'name' => 'french-fries',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/americandiner/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat4_prod1_thumbnail.webp',
                        'name_en' => 'French Fries',
                        'name_ar' => 'بطاطس مقلية',
                        'name_fr' => 'Frites',
                        'name_it' => 'Patatine fritte',
                        'name_de' => 'Pommes frittes',
                        'name_es' => 'Papas fritas',
                        'name_ua' => 'Картопля фрі',
                        'options' => [
                            [
                                'name' => 'fries-type',
                                'name_en' => 'Fries type',
                                'name_ar' => 'نوع البطاطس المقلية',
                                'name_fr' => 'Genre frites',
                                'name_it' => 'Tipo di patatine fritte',
                                'name_de' => 'Pommes-Typ',
                                'name_es' => 'Papas tipo',
                                'name_ua' => 'Тип фрі',
                                'selections' => [
                                    [
                                        'name' => 'standard-fries',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Standard fries',
                                        'name_ar' => 'بطاطس عادية',
                                        'name_fr' => 'Frites standards',
                                        'name_it' => 'Patatine standard',
                                        'name_de' => 'Standard Pommes',
                                        'name_es' => 'Papas fritas estándar',
                                        'name_ua' => 'Стандартна картопля фрі',
                                    ],
                                    [
                                        'name' => 'crinkle-cut-fries',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Crinkle-cut fries',
                                        'name_ar' => 'بطاطا مقلية مقرمشة',
                                        'name_fr' => 'Frites coupe ondulée',
                                        'name_it' => 'Patatine fritte',
                                        'name_de' => 'Crinkle-Cut-Pommes',
                                        'name_es' => 'Papas fritas arrugadas',
                                        'name_ua' => 'Нарізана картопля фрі',
                                    ],
                                    [
                                        'name' => 'curly-fries',
                                        'price' => 0.20,
                                        'isDefault' => false,
                                        'name_en' => 'Curly fries',
                                        'name_ar' => 'كيرلي فرايز',
                                        'name_fr' => 'Frites bouclés',
                                        'name_it' => 'Patatine Ricce',
                                        'name_de' => 'Lockige Pommes',
                                        'name_es' => 'Papas fritas rizadas',
                                        'name_ua' => 'Кучерява картопля фрі',
                                    ],
                                    [
                                        'name' => 'steak-fries',
                                        'price' => 0.50,
                                        'isDefault' => false,
                                        'name_en' => 'Steak fries',
                                        'name_ar' => 'بطاطس ستيك',
                                        'name_fr' => 'Steak frites',
                                        'name_it' => 'Patatine fritte',
                                        'name_de' => 'Schnitzel Pommes',
                                        'name_es' => 'bistec papas fritas',
                                        'name_ua' => 'Стейк фрі',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-wings',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/americandiner/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Chicken Wings',
                        'name_ar' => 'أجنحة دجاج',
                        'name_fr' => 'Ailes de poulet',
                        'name_it' => 'Ali di pollo',
                        'name_de' => 'Hühnerflügel',
                        'name_es' => 'Alitas de pollo',
                        'name_ua' => 'Курячі крильця',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'الصوص',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صوص الباربكيو',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صوص الرانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0.00,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صوص ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'mozzarella-sticks',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/americandiner/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Mozzarella Sticks',
                        'name_ar' => 'أصابع موزاريلا',
                        'name_fr' => 'Bâtonnets de mozzarella',
                        'name_it' => 'Bastoncini di mozzarella',
                        'name_de' => 'Mozzarella-Sticks',
                        'name_es' => 'Palos de mozzarella',
                        'name_ua' => 'Палички моцарели',
                        'options' => [

                        ]
                    ],
                    [
                        'name' => 'cheese-nachos',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/americandiner/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Cheese Nachos',
                        'name_ar' => 'ناتشوز بالجبنة',
                        'name_fr' => 'Nachos au fromage',
                        'name_it' => 'Nacho al formaggio',
                        'name_de' => 'Käse-Nachos',
                        'name_es' => 'Nachos De Queso',
                        'name_ua' => 'Сирний начос',
                        'options' => [

                        ]
                    ],
                ]
            ],
            [
                'name' => 'milkshakes',
                'imgUrl' => 'imgs/demo/americandiner/cat5.webp',
                'thumbnailUrl' => 'imgs/demo/americandiner/cat5_thumbnail.webp',
                'name_en' => 'Milkshakes',
                'name_ar' => 'ميلك شيك',
                'name_fr' => 'Laits frappés',
                'name_it' => 'Frappè',
                'name_de' => 'Milchshakes',
                'name_es' => 'Batidos de leche',
                'name_ua' => 'молочні коктейлі',
                'products' => [
                    [
                        'name' => 'vanilla-special-milkshake',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/americandiner/cat5_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat5_prod1_thumbnail.webp',
                        'name_en' => 'Vanilla Special Milkshake',
                        'name_ar' => 'ميلك شيك الفانيليا',
                        'name_fr' => 'Milk-shake à la vanille',
                        'name_it' => 'Frappè alla vaniglia',
                        'name_de' => 'Vanille Milchshake',
                        'name_es' => 'Batido de vainilla',
                        'name_ua' => 'Ванільний молочний коктейль',
                        'options' => [

                        ]
                    ],
                    [
                        'name' => 'chocolate-milkshake',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/americandiner/cat5_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat5_prod2_thumbnail.webp',
                        'name_en' => 'Chocolate Milkshake',
                        'name_ar' => 'ميلك شيك شوكولاتة',
                        'name_fr' => 'Milkshake au chocolat',
                        'name_it' => 'Frappè Al Cioccolato',
                        'name_de' => 'Schokoladen-Milchshake',
                        'name_es' => 'Malteada de chocolate',
                        'name_ua' => 'Шоколадний молочний коктейль',
                        'options' => [

                        ]
                    ],
                    [
                        'name' => 'strawberry-milkshake',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/americandiner/cat5_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat5_prod3_thumbnail.webp',
                        'name_en' => 'Strawberry Milkshake',
                        'name_ar' => 'مخفوق الحليب بالفرواله',
                        'name_fr' => 'Milkshake à la fraise',
                        'name_it' => 'Frullato alla fragola',
                        'name_de' => 'Erdbeer Milchshake',
                        'name_es' => 'Batido de fresa',
                        'name_ua' => 'Полуничний молочний коктейль',
                        'options' => [

                        ]
                    ],
                    [
                        'name' => 'buttermilk-banana-milkshake',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/americandiner/cat5_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/americandiner/cat5_prod4_thumbnail.webp',
                        'name_en' => 'Buttermilk Banana Milkshake',
                        'name_ar' => 'ميلك شيك موز',
                        'name_fr' => 'Milkshake à la banane',
                        'name_it' => 'Frappè alla banana',
                        'name_de' => 'Bananen-Milchshake',
                        'name_es' => 'Batido de plátano',
                        'name_ua' => 'Банановий молочний коктейль',
                        'options' => [

                        ]
                    ],
                ]
            ],
        ];

        demo::website($americanDiner,$categories,900);

    }
}
