<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class burgers extends Seeder
{

    public function run()
    {
        $burgers = new stdClass();
        $burgers->domainName = 'burgers';
        $burgers->website_names = [
            'en' => 'Burgers',
            'ar' => 'برجر',
            'fr' => 'Hamburgers',
            'de' => 'Burger',
            'it' => 'Hamburger',
            'es' => 'Hamburguesas',
            'ua' => 'бургери',
            'ru' => '',
        ];
        $burgers->intro = [
            'en' => 'Most loved Burger in town',
            'ar' => 'أحب برجر في المدينة',
            'fr' => 'Burger le plus aimé de la ville',
            'de' => 'Der beliebteste Burger der Stadt',
            'it' => 'L\'hamburger più amato della città',
            'es' => 'La hamburguesa más querida de la ciudad',
            'ua' => 'Найулюбленіший бургер у місті',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'original-burgers',
                'imgUrl' => 'imgs/demo/burgers/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/burgers/cat1_thumbnail.webp',
                'name_en' => 'Original Burgers',
                'name_ar' => 'اوريجينال برجر',
                'name_fr' => 'Burgers originaux',
                'name_it' => 'Hamburger originali',
                'name_de' => 'Originale Burger',
                'name_es' => 'Hamburguesas Originales',
                'name_ua' => 'Оригінальні бургери',
                'products' => [
                    [
                        'name' => 'smokehouse-bbq',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/burgers/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Smokehouse BBQ',
                        'name_ar' => 'سموك هاوس باربكيو',
                        'name_fr' => 'Barbecue fumoir',
                        'name_it' => 'Barbecue all\'affumicatoio',
                        'name_de' => 'Räucherei BBQ',
                        'name_es' => 'barbacoa ahumadero',
                        'name_ua' => 'Коптильня барбекю',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheeseburger',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/burgers/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Cheeseburger',
                        'name_ar' => 'تشيز برجر',
                        'name_fr' => 'Cheeseburger',
                        'name_it' => 'Cheeseburger',
                        'name_de' => 'Cheeseburger',
                        'name_es' => 'Hamburguesa con queso',
                        'name_ua' => 'Чізбургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'bacon-cheddar',
                        'price' => 9,
                        'imgUrl' => 'imgs/demo/burgers/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Bacon Cheddar',
                        'name_ar' => 'بيكون شيدر',
                        'name_fr' => 'Cheddar au bacon',
                        'name_it' => 'Pancetta Cheddar',
                        'name_de' => 'Speck-Cheddar',
                        'name_es' => 'tocino cheddar',
                        'name_ua' => 'Бекон Чеддер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'classic-burger',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/burgers/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Classic Burger',
                        'name_ar' => 'كلاسيك برجر',
                        'name_fr' => 'Hamburger classique',
                        'name_it' => 'Hamburger Classico',
                        'name_de' => 'Klassischer Burger',
                        'name_es' => 'Hamburguesa Clásica',
                        'name_ua' => 'Класичний бургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'appetizers',
                'imgUrl' => 'imgs/demo/burgers/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/burgers/cat2_thumbnail.webp',
                'name_en' => 'Appetizers',
                'name_ar' => 'المقبلات',
                'name_fr' => 'Apéritifs',
                'name_it' => 'Antipasti',
                'name_de' => 'Vorspeisen',
                'name_es' => 'Aperitivos',
                'name_ua' => 'Закуски',
                'products' => [
                    [
                        'name' => 'french-fries',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/burgers/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat2_prod1_thumbnail.webp',
                        'name_en' => 'French Fries',
                        'name_ar' => 'البطاطس المقلية',
                        'name_fr' => 'Frites',
                        'name_it' => 'Patatine fritte',
                        'name_de' => 'Pommes frittes',
                        'name_es' => 'Papas fritas',
                        'name_ua' => 'Картопля фрі',
                        'options' => [
                            [
                                'name' => 'fries-type',
                                'name_en' => 'Fries type',
                                'name_ar' => 'نوع البطاطس المقلية',
                                'name_fr' => 'Genre frites',
                                'name_it' => 'Tipo di patatine fritte',
                                'name_de' => 'Pommes-Typ',
                                'name_es' => 'Papas tipo',
                                'name_ua' => 'Тип фрі',
                                'selections' => [
                                    [
                                        'name' => 'standard-fries',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Standard fries',
                                        'name_ar' => 'بطاطس عادية',
                                        'name_fr' => 'Frites standards',
                                        'name_it' => 'Patatine standard',
                                        'name_de' => 'Standard Pommes',
                                        'name_es' => 'Papas fritas estándar',
                                        'name_ua' => 'Стандартна картопля фрі',
                                    ],
                                    [
                                        'name' => 'crinkle-cut-fries',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Crinkle-cut fries',
                                        'name_ar' => 'بطاطا مقلية مقرمشة',
                                        'name_fr' => 'Frites coupe ondulée',
                                        'name_it' => 'Patatine fritte',
                                        'name_de' => 'Crinkle-Cut-Pommes',
                                        'name_es' => 'Papas fritas arrugadas',
                                        'name_ua' => 'Нарізана картопля фрі',
                                    ],
                                    [
                                        'name' => 'curly-fries',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Curly fries',
                                        'name_ar' => 'كيرلي فرايز',
                                        'name_fr' => 'Frites bouclés',
                                        'name_it' => 'Patatine Ricce',
                                        'name_de' => 'Lockige Pommes',
                                        'name_es' => 'Papas fritas rizadas',
                                        'name_ua' => 'Кучерява картопля фрі',
                                    ],
                                    [
                                        'name' => 'steak-fries',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Steak fries',
                                        'name_ar' => 'شريحة لحم مقليه',
                                        'name_fr' => 'Steak frites',
                                        'name_it' => 'Patatine fritte',
                                        'name_de' => 'Schnitzel Pommes',
                                        'name_es' => 'bistec papas fritas',
                                        'name_ua' => 'Стейк фрі',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-wings',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/burgers/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Chicken Wings',
                        'name_ar' => 'أجنحة دجاج',
                        'name_fr' => 'Ailes de poulet',
                        'name_it' => 'Ali di pollo',
                        'name_de' => 'Hühnerflügel',
                        'name_es' => 'Alitas de pollo',
                        'name_ua' => 'Курячі крильця',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'mozzarella-sticks',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/burgers/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Mozzarella Sticks',
                        'name_ar' => 'العصي موزاريلا',
                        'name_fr' => 'Bâtonnets de mozzarella',
                        'name_it' => 'Bastoncini di mozzarella',
                        'name_de' => 'Mozzarella-Sticks',
                        'name_es' => 'Palos de mozzarella',
                        'name_ua' => 'Палички моцарели',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheese-nachos',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/burgers/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Cheese Nachos',
                        'name_ar' => 'ناتشوز بالجبنة',
                        'name_fr' => 'Nachos au fromage',
                        'name_it' => 'Nacho al formaggio',
                        'name_de' => 'Käse-Nachos',
                        'name_es' => 'Nachos De Queso',
                        'name_ua' => 'Сирний начос',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/burgers/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/burgers/cat3_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'caesar-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/burgers/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 1,
                        'imgUrl' => 'imgs/demo/burgers/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/burgers/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Pasta salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'tuna-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/burgers/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Tuna Salad',
                        'name_ar' => 'سلطة التونة',
                        'name_fr' => 'Salade de thon',
                        'name_it' => 'Insalata di tonno',
                        'name_de' => 'Thunfischsalat',
                        'name_es' => 'Ensalada de atún',
                        'name_ua' => 'Салат з тунцем',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'drinks',
                'imgUrl' => 'imgs/demo/burgers/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/burgers/cat4_thumbnail.webp',
                'name_en' => 'Drinks',
                'name_ar' => 'مشروبات',
                'name_fr' => 'Boissons',
                'name_it' => 'Bevande',
                'name_de' => 'Getränke',
                'name_es' => 'Bebidas',
                'name_ua' => 'Напої',
                'products' => [
                    [
                        'name' => 'vanilla-special-milkshake',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/burgers/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Vanilla Special Milkshake',
                        'name_ar' => 'ميلك شيك الفانيليا الخاص',
                        'name_fr' => 'Milkshake Spécial Vanille',
                        'name_it' => 'Frappè speciale alla vaniglia',
                        'name_de' => 'Vanille-Spezial-Milchshake',
                        'name_es' => 'Malteada especial de vainilla',
                        'name_ua' => 'Ванільний спеціальний молочний коктейль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chocolate-milkshake',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/burgers/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Chocolate Milkshake',
                        'name_ar' => 'ميلك شيك شوكولاتة',
                        'name_fr' => 'Milkshake au chocolat',
                        'name_it' => 'Frappè Al Cioccolato',
                        'name_de' => 'Schokoladenmilchshake',
                        'name_es' => 'Malteada de chocolate',
                        'name_ua' => 'Шоколадний молочний коктейль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'strawberry-milkshake',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/burgers/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Strawberry Milkshake',
                        'name_ar' => 'مخفوق الحليب بالفرواله',
                        'name_fr' => 'Milkshake à la fraise',
                        'name_it' => 'Frullato alla fragola',
                        'name_de' => 'Erdbeer Milchshake',
                        'name_es' => 'Batido de fresa',
                        'name_ua' => 'Полуничний молочний коктейль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'buttermilk-banana-milkshake',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/burgers/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/burgers/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Buttermilk Banana Milkshake',
                        'name_ar' => 'اللبن والموز ميلك شيك',
                        'name_fr' => 'Milkshake aux bananes et au babeurre',
                        'name_it' => 'Frappè alla banana e latticello',
                        'name_de' => 'Buttermilch-Bananen-Milchshake',
                        'name_es' => 'Batido De Plátano Y Suero De Mantequilla',
                        'name_ua' => 'Пахта банановий молочний коктейль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($burgers,$categories);
    }

}
