<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class casualDining extends Seeder
{

    public function run()
    {
        $casualDining = new stdClass();
        $casualDining->domainName = 'casualdining';
        $casualDining->template = 3;
        $casualDining->website_names = [
            'en' => 'Casual Dining',
            'ar' => 'عشاء غير رسمي',
            'fr' => 'Dîner décontracté',
            'de' => 'Casual Dining',
            'it' => 'Pranzo informale',
            'es' => 'Cena casual',
            'ua' => 'Повсякденна їдальня',
            'ru' => '',
        ];
        $casualDining->intro = [
            'en' => 'Serving great tastes',
            'ar' => 'خدمة الأذواق الرائعة',
            'fr' => 'Servir de bons goûts',
            'de' => 'Großen Geschmack servieren',
            'it' => 'Servire grandi sapori',
            'es' => 'Sirviendo grandes gustos',
            'ua' => 'Подача чудового смаку',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/casualdining/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/casualdining/cat1_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'caesar-salad',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/casualdining/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 2.5,
                        'imgUrl' => 'imgs/demo/casualdining/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/casualdining/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Pasta salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tuna-salad',
                        'price' => 4.5,
                        'imgUrl' => 'imgs/demo/casualdining/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Tuna Salad',
                        'name_ar' => 'سلطة التونة',
                        'name_fr' => 'Salade de thon',
                        'name_it' => 'Insalata di tonno',
                        'name_de' => 'Thunfischsalat',
                        'name_es' => 'Ensalada de atún',
                        'name_ua' => 'Салат з тунцем',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'soups',
                'imgUrl' => 'imgs/demo/casualdining/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/casualdining/cat2_thumbnail.webp',
                'name_en' => 'Soups',
                'name_ar' => 'الحساء',
                'name_fr' => 'Soupes',
                'name_it' => 'Zuppe',
                'name_de' => 'Suppen',
                'name_es' => 'sopas',
                'name_ua' => 'Супи',
                'products' => [
                    [
                        'name' => 'cream-of-chicken-soup',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/casualdining/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Cream of Chicken Soup',
                        'name_ar' => 'شوربة كريمة الدجاج',
                        'name_fr' => 'Velouté de Poulet',
                        'name_it' => 'Crema di zuppa di pollo',
                        'name_de' => 'Hühnercremesuppe',
                        'name_es' => 'Sopa Crema De Pollo',
                        'name_ua' => 'Курячий крем-суп',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tomato-basil-soup',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/casualdining/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Tomato Basil Soup',
                        'name_ar' => 'حساء الطمام والريحان',
                        'name_fr' => 'soupe à la tomate et au basilique',
                        'name_it' => 'zuppa di pomodoro e basilico',
                        'name_de' => 'Tomaten-Basilikum-Suppe',
                        'name_es' => 'Sopa de tomate y albahaca',
                        'name_ua' => 'Томатний суп з базиліком',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cream-of-mushroom-soup',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/casualdining/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Cream of Mushroom Soup',
                        'name_ar' => 'شوربة الفطر',
                        'name_fr' => 'Crème de champignons',
                        'name_it' => 'zuppa di funghi',
                        'name_de' => 'Pilzcremesuppe',
                        'name_es' => 'Crema de Champiñones',
                        'name_ua' => 'Грибний крем-суп',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'broccoli-cheddar-soup',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/casualdining/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Broccoli Cheddar Soup',
                        'name_ar' => 'شوربة بروكلي شيدر',
                        'name_fr' => 'Soupe aux broccolis et au cheddar',
                        'name_it' => 'zuppa di broccoli con cheddar',
                        'name_de' => 'Brokkoli Cheddar Suppe',
                        'name_es' => 'Sopa de Brocoli con Queso Cheddar',
                        'name_ua' => 'Суп з чеддером з брокколі',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'main-dishes',
                'imgUrl' => 'imgs/demo/casualdining/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/casualdining/cat3_thumbnail.webp',
                'name_en' => 'Main dishes',
                'name_ar' => 'الأطباق الرئيسية',
                'name_fr' => 'Plats principaux',
                'name_it' => 'Piatti principali',
                'name_de' => 'Hauptgang',
                'name_es' => 'Platos principales',
                'name_ua' => 'Основні страви',
                'products' => [
                    [
                        'name' => 'grilled-chicken',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/casualdining/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Grilled chicken',
                        'name_ar' => 'دجاج مشوي',
                        'name_fr' => 'Poulet grillé',
                        'name_it' => 'Pollo grigliato',
                        'name_de' => 'Gegrilltes Hühnchen',
                        'name_es' => 'Pollo a la parrilla',
                        'name_ua' => 'Курка-гриль',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'steak-with-mashed-potatoes',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/casualdining/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Steak with mashed potatoes',
                        'name_ar' => 'ستيك مع بطاطا مهروسة',
                        'name_fr' => 'Steak avec purée de pommes de terre',
                        'name_it' => 'Bistecca con purè di patate',
                        'name_de' => 'Steak mit Kartoffelpüree',
                        'name_es' => 'bistec con puré de patatas',
                        'name_ua' => 'Стейк з картопляним пюре',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'grilled-salmon-with-dill-sauce',
                        'price' => 17,
                        'imgUrl' => 'imgs/demo/casualdining/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Grilled Salmon With Dill Sauce',
                        'name_ar' => 'سلمون مشوي بصلصة الشبت',
                        'name_fr' => 'Saumon grillé à la sauce à l\'aneth',
                        'name_it' => 'Salmone Alla Griglia Con Salsa Di Aneto',
                        'name_de' => 'Gegrillter Lachs mit Dillsauce',
                        'name_es' => 'Salmón A La Plancha Con Salsa De Eneldo',
                        'name_ua' => 'Лосось на грилі з кроповим соусом',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'pasta',
                'imgUrl' => 'imgs/demo/casualdining/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/casualdining/cat4_thumbnail.webp',
                'name_en' => 'Pasta',
                'name_ar' => 'معكرونة',
                'name_fr' => 'Pâtes',
                'name_it' => 'Pasta',
                'name_de' => 'Pasta',
                'name_es' => 'Pasta',
                'name_ua' => 'паста',
                'products' => [
                    [
                        'name' => 'lasagna',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/casualdining/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Lasagna',
                        'name_ar' => 'لازانيا',
                        'name_fr' => 'Lasagne',
                        'name_it' => 'Lasagna',
                        'name_de' => 'Lasagne',
                        'name_es' => 'Lasaña',
                        'name_ua' => 'Лазанья',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'fettuccine-alfredo',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/casualdining/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Fettuccine Alfredo',
                        'name_ar' => 'فيتوشيني ألفريدو',
                        'name_fr' => 'Fettucine Alfredo',
                        'name_it' => 'Fettuccine Alfredo',
                        'name_de' => 'Fettuccine Alfredo',
                        'name_es' => 'Fettuccine Alfredo',
                        'name_ua' => 'Фетучіні Альфредо',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'sausage-pasta',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/casualdining/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/casualdining/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Sausage Pasta',
                        'name_ar' => 'باستا سجق',
                        'name_fr' => 'Pâtes à la saucisse',
                        'name_it' => 'Pasta Salsiccia',
                        'name_de' => 'Wurst-Nudeln',
                        'name_es' => 'Pasta De Salchicha',
                        'name_ua' => 'Макарони з ковбасою',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($casualDining,$categories);
    }

}
