<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class fastfood extends Seeder
{

    public function run()
    {
        $fastFood = new stdClass();
        $fastFood->domainName = 'fastfood';
        $fastFood->website_names = [
            'en' => 'Fast Food',
            'ar' => 'الطعام السريع',
            'fr' => 'Fast food',
            'de' => 'Fastfood',
            'it' => 'Fast food',
            'es' => 'Comida rápida',
            'ua' => 'Фастфуд',
            'ru' => '',
        ];
        $fastFood->intro = [
            'en' => 'We cook what you crave',
            'ar' => 'نحن نطبخ ما تشتهيه',
            'fr' => 'Nous cuisinons ce dont vous avez envie',
            'de' => 'Wir kochen worauf Sie Lust haben',
            'it' => 'Cuciniamo ciò che desideri',
            'es' => 'Cocinamos lo que se te antoja',
            'ua' => 'Ми готуємо те, що вам заманеться',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'burgers',
                'imgUrl' => 'imgs/demo/fastfood/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/fastfood/cat1_thumbnail.webp',
                'name_en' => 'Burgers',
                'name_ar' => 'برجر',
                'name_fr' => 'Hamburgers',
                'name_it' => 'Hamburger',
                'name_de' => 'Burger',
                'name_es' => 'Hamburguesas',
                'name_ua' => 'бургери',
                'products' => [
                    [
                        'name' => 'smokehouse-bbq',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/fastfood/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Smokehouse BBQ',
                        'name_ar' => 'سموك هاوس باربكيو',
                        'name_fr' => 'Barbecue fumoir',
                        'name_it' => 'Barbecue all\'affumicatoio',
                        'name_de' => 'Räucherei BBQ',
                        'name_es' => 'barbacoa ahumadero',
                        'name_ua' => 'Коптильня барбекю',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheeseburger',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/fastfood/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Cheeseburger',
                        'name_ar' => 'تشيز برجر',
                        'name_fr' => 'Cheeseburger',
                        'name_it' => 'Cheeseburger',
                        'name_de' => 'Cheeseburger',
                        'name_es' => 'Hamburguesa con queso',
                        'name_ua' => 'Чізбургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 5.8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'bacon-cheddar',
                        'price' => 7.5,
                        'imgUrl' => 'imgs/demo/fastfood/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Bacon Cheddar',
                        'name_ar' => 'بيكون شيدر',
                        'name_fr' => 'Cheddar au bacon',
                        'name_it' => 'Pancetta Cheddar',
                        'name_de' => 'Speck-Cheddar',
                        'name_es' => 'tocino cheddar',
                        'name_ua' => 'Бекон Чеддер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.75,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 5.75,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'classic-burger',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/fastfood/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Classic Burger',
                        'name_ar' => 'كلاسيك برجر',
                        'name_fr' => 'Hamburger classique',
                        'name_it' => 'Hamburger Classico',
                        'name_de' => 'Klassischer Burger',
                        'name_es' => 'Hamburguesa Clásica',
                        'name_ua' => 'Класичний бургер',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'wraps',
                'imgUrl' => 'imgs/demo/fastfood/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/fastfood/cat2_thumbnail.webp',
                'name_en' => 'Wraps',
                'name_ar' => 'يلف',
                'name_fr' => 'Wraps',
                'name_it' => 'Avvolge',
                'name_de' => 'Wraps',
                'name_es' => 'Envolturas',
                'name_ua' => 'обгортання',
                'products' => [
                    [
                        'name' => 'veggie-wrap',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/fastfood/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Veggie Wrap',
                        'name_ar' => 'الخضروات التالفه',
                        'name_fr' => 'Wrap végétarien',
                        'name_it' => 'Involtino vegetariano',
                        'name_de' => 'Veggie Wrap',
                        'name_es' => 'Envoltura de verduras',
                        'name_ua' => 'Овочева упаковка',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'breakfast-wrap',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/fastfood/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Breakfast Wrap',
                        'name_ar' => 'راب الإفطار',
                        'name_fr' => 'Wrap petit-déjeuner',
                        'name_it' => 'Impacco per la colazione',
                        'name_de' => 'Frühstücks-Wrap',
                        'name_es' => 'Envoltura de desayuno',
                        'name_ua' => 'Обгортка для сніданку',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'turkey-wrap',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/fastfood/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Turkey Wrap',
                        'name_ar' => 'راب ديك رومي',
                        'name_fr' => 'Wrap à la dinde',
                        'name_it' => 'Involtino di tacchino',
                        'name_de' => 'Truthahn-Wrap',
                        'name_es' => 'Envoltura de Pavo',
                        'name_ua' => 'Обгортка з індички',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-wrap',
                        'price' => 6.5,
                        'imgUrl' => 'imgs/demo/fastfood/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Chicken Wrap',
                        'name_ar' => 'راب دجاج',
                        'name_fr' => 'Wrap au poulet',
                        'name_it' => 'Involtino di pollo',
                        'name_de' => 'Hühner-Wrap',
                        'name_es' => 'Wrap de pollo',
                        'name_ua' => 'Куряче обгортання',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.75,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 5.75,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'club-wrap',
                        'price' => 7.5,
                        'imgUrl' => 'imgs/demo/fastfood/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Club Wrap',
                        'name_ar' => 'كلوب راب',
                        'name_fr' => 'Enveloppe de club',
                        'name_it' => 'Avvolgere il club',
                        'name_de' => 'Club-Wrap',
                        'name_es' => 'Envoltura de club',
                        'name_ua' => 'Club Wrap',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6.25,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'pizza',
                'imgUrl' => 'imgs/demo/fastfood/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/fastfood/cat3_thumbnail.webp',
                'name_en' => 'Pizza',
                'name_ar' => 'بيتزا',
                'name_fr' => 'Pizza',
                'name_it' => 'Pizza',
                'name_de' => 'Pizza',
                'name_es' => 'Pizza',
                'name_ua' => 'піца',
                'products' => [
                    [
                        'name' => 'bocconcini-salami-pizza',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Bocconcini Salami Pizza',
                        'name_ar' => 'بيتزا بوكونسيني سلامي',
                        'name_fr' => 'Pizza au salami bocconcini',
                        'name_it' => 'Bocconcini Salame Pizza',
                        'name_de' => 'Bocconcini-Salami-Pizza',
                        'name_es' => 'Pizza de Salami Bocconcini',
                        'name_ua' => 'Піца салямі Боккончіні',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ],[
                                'name' => 'extra-salami',
                                'name_en' => 'Extra Salami',
                                'name_ar' => 'إضافة سلامي',
                                'name_fr' => 'Extra Salami',
                                'name_it' => 'Salame Extra',
                                'name_de' => 'Zusätzliche Salami',
                                'name_es' => 'Salame extra',
                                'name_ua' => 'Екстра салямі',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'pizza-carbonara',
                        'price' => 8.50,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Pizza Carbonara',
                        'name_ar' => 'بيتزا كاربونارا',
                        'name_fr' => 'Pizza Carbonara',
                        'name_it' => 'Pizze alla Carbonara',
                        'name_de' => 'Pizza Carbonara',
                        'name_es' => 'pizza carbonara',
                        'name_ua' => 'Піца Карбонара',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'pizza-diavola',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Pizza Diavola',
                        'name_ar' => 'بيتزا ديافولا',
                        'name_fr' => 'Pizza Diavola',
                        'name_it' => 'Pizza Diavolo',
                        'name_de' => 'Pizza Diavola',
                        'name_es' => 'Pizza Diavola',
                        'name_ua' => 'Піца Діавола',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'pizza-marinara',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Pizza Marinara',
                        'name_ar' => 'بيتزا مارينارا',
                        'name_fr' => 'Pizza Marinara',
                        'name_it' => 'Pizza Marinara',
                        'name_de' => 'Pizza Marinara',
                        'name_es' => 'pizza marinera',
                        'name_ua' => 'Піца Маринара',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'veggie-pizza',
                        'price' => 5.50,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod5_thumbnail.webp',
                        'name_en' => 'Veggie Pizza',
                        'name_ar' => 'بيتزا خضار',
                        'name_fr' => 'Pizza Végétarienne',
                        'name_it' => 'Pizza vegetariana',
                        'name_de' => 'Vegetarische Pizza',
                        'name_es' => 'pizza vegetariana',
                        'name_ua' => 'Овочева піца',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ],
                    [
                        'name' => 'cheese-pizza',
                        'price' => 8.50,
                        'imgUrl' => 'imgs/demo/fastfood/cat3_prod6.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat3_prod6_thumbnail.webp',
                        'name_en' => 'Cheese Pizza',
                        'name_ar' => 'بيتزا الجبن',
                        'name_fr' => 'Pizza au fromage',
                        'name_it' => 'Pizza al formaggio',
                        'name_de' => 'Käse-Pizza',
                        'name_es' => 'Pizza de queso',
                        'name_ua' => 'сирна піца',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'الحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeño',
                                        'name_ua' => 'Маленький',
                                    ],[
                                        'name' => 'medium',
                                        'price' => 3.00,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],[
                                        'name' => 'large',
                                        'price' => 5.00,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grand',
                                        'name_it' => 'Larga',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],[
                                'name' => 'extra-cheese',
                                'name_en' => 'Extra Cheese',
                                'name_ar' => 'إضافة جبن',
                                'name_fr' => 'Extra Fromage',
                                'name_it' => 'Formaggio extra',
                                'name_de' => 'Extra Käse',
                                'name_es' => 'Extra queso',
                                'name_ua' => 'Екстра сир',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 1.50,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],[
                                        'name' => 'no',
                                        'price' => 0.00,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Ні',
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ],
            [
                'name' => 'beverages',
                'imgUrl' => 'imgs/demo/fastfood/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/fastfood/cat4_thumbnail.webp',
                'name_en' => 'Beverages',
                'name_ar' => 'المشروبات',
                'name_fr' => 'Breuvages',
                'name_it' => 'Bevande',
                'name_de' => 'Getränke',
                'name_es' => 'Bebidas',
                'name_ua' => 'Напої',
                'products' => [
                    [
                        'name' => 'water',
                        'price' => 2,
                        'imgUrl' => 'imgs/demo/fastfood/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Water',
                        'name_ar' => 'ماء',
                        'name_fr' => 'L\'eau',
                        'name_it' => 'Acqua',
                        'name_de' => 'Wasser',
                        'name_es' => 'Agua',
                        'name_ua' => 'вода',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'soda',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/fastfood/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Soda',
                        'name_ar' => 'مشروب غازي',
                        'name_fr' => 'Un soda',
                        'name_it' => 'Bibita',
                        'name_de' => 'Limonade',
                        'name_es' => 'soda',
                        'name_ua' => 'Сода',
                        'options' => [
                            [
                                'name' => 'coke',
                                'name_en' => 'Coke',
                                'name_ar' => 'فحم الكوك',
                                'name_fr' => 'du Coca',
                                'name_it' => 'Coca Cola',
                                'name_de' => 'Koks',
                                'name_es' => 'Coca',
                                'name_ua' => 'Кокс',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'cherry-coke',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Cherry Coke',
                                        'name_ar' => 'فحم الكوك الكرز',
                                        'name_fr' => 'Coca Cerise',
                                        'name_it' => 'Coca Ciliegia',
                                        'name_de' => 'Kirsch Cola',
                                        'name_es' => 'Coca-Cola de cereza',
                                        'name_ua' => 'Вишнева кола',
                                    ],
                                    [
                                        'name' => 'vanilla-coke',
                                        'price' => 2.25,
                                        'isDefault' => false,
                                        'name_en' => 'Vanilla Coke',
                                        'name_ar' => 'فانيلا كوك',
                                        'name_fr' => 'Coca Vanille',
                                        'name_it' => 'coca cola alla vaniglia',
                                        'name_de' => 'Vanille-Cola',
                                        'name_es' => 'Coca-Cola De Vainilla',
                                        'name_ua' => 'Ванільна кола',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 1.75,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'lemonade',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/fastfood/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Lemonade',
                        'name_ar' => 'عصير الليمون',
                        'name_fr' => 'Limonade',
                        'name_it' => 'Limonata',
                        'name_de' => 'Limonade',
                        'name_es' => 'Limonada',
                        'name_ua' => 'Лимонад',
                        'options' => [
                            [
                                'name' => 'flavor',
                                'name_en' => 'Flavor',
                                'name_ar' => 'نكهة',
                                'name_fr' => 'Saveur',
                                'name_it' => 'Gusto',
                                'name_de' => 'Geschmack',
                                'name_es' => 'Sabor',
                                'name_ua' => 'Смак',
                                'selections' => [
                                    [
                                        'name' => 'plain',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Plain',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'strawberry-lemonade',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry Lemonade',
                                        'name_ar' => 'ليموناضة الفراولة',
                                        'name_fr' => 'Limonade de fraise',
                                        'name_it' => 'Limonata alla fragola',
                                        'name_de' => 'Erdbeerlimonade',
                                        'name_es' => 'Limonada de fresa',
                                        'name_ua' => 'Полуничний лимонад',
                                    ],
                                    [
                                        'name' => 'raspberry-lemonade',
                                        'price' => 4.5,
                                        'isDefault' => false,
                                        'name_en' => 'Raspberry Lemonade',
                                        'name_ar' => 'التوت عصير الليمون',
                                        'name_fr' => 'Limonade à la framboise',
                                        'name_it' => 'Limonata al lampone',
                                        'name_de' => 'Himbeer Limonade',
                                        'name_es' => 'Limonada de frambuesa',
                                        'name_ua' => 'Малиновий лимонад',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'iced-tea',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/fastfood/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/fastfood/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Iced Tea',
                        'name_ar' => 'شاي مثلج',
                        'name_fr' => 'Thé glacé',
                        'name_it' => 'Tè freddo',
                        'name_de' => 'Eistee',
                        'name_es' => 'Te helado',
                        'name_ua' => 'Холодний чай',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($fastFood,$categories);
    }

}
