<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class fineDining extends Seeder
{

    public function run()
    {
        $fineDining = new stdClass();
        $fineDining->domainName = 'finedining';
        $fineDining->template = 4;
        $fineDining->website_names = [
            'en' => 'Fine Dining',
            'ar' => 'طعام ممتاز',
            'fr' => 'Gastronomie',
            'de' => 'Vornehmes Speisen',
            'it' => 'Cucina raffinata',
            'es' => 'Buena cena',
            'ua' => 'Вишукані вечері',
            'ru' => '',
        ];
        $fineDining->intro = [
            'en' => 'Serving a premium dining experience',
            'ar' => 'تقديم تجربة طعام ممتازة',
            'fr' => 'Servir une expérience culinaire haut de gamme',
            'de' => 'Serviert ein erstklassiges kulinarisches Erlebnis',
            'it' => 'Serve un\'esperienza culinaria premium',
            'es' => 'Sirviendo una experiencia gastronómica premium',
            'ua' => 'Обслуговування першокласного ресторану',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'soups',
                'imgUrl' => 'imgs/demo/finedining/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/finedining/cat1_thumbnail.webp',
                'name_en' => 'Soups',
                'name_ar' => 'الحساء',
                'name_fr' => 'Soupes',
                'name_it' => 'Zuppe',
                'name_de' => 'Suppen',
                'name_es' => 'sopas',
                'name_ua' => 'Супи',
                'products' => [
                    [
                        'name' => 'cream-of-chicken-soup',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/finedining/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Cream of Chicken Soup',
                        'name_ar' => 'شوربة كريمة الدجاج',
                        'name_fr' => 'Velouté de Poulet',
                        'name_it' => 'Crema di zuppa di pollo',
                        'name_de' => 'Hühnercremesuppe',
                        'name_es' => 'Sopa Crema De Pollo',
                        'name_ua' => 'Курячий крем-суп',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tomato-basil-soup',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/finedining/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Tomato Basil Soup',
                        'name_ar' => 'حساء الطمام والريحان',
                        'name_fr' => 'soupe à la tomate et au basilique',
                        'name_it' => 'zuppa di pomodoro e basilico',
                        'name_de' => 'Tomaten-Basilikum-Suppe',
                        'name_es' => 'Sopa de tomate y albahaca',
                        'name_ua' => 'Томатний суп з базиліком',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cream-of-mushroom-soup',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/finedining/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Cream of Mushroom Soup',
                        'name_ar' => 'شوربة الفطر',
                        'name_fr' => 'Crème de champignons',
                        'name_it' => 'zuppa di funghi',
                        'name_de' => 'Pilzcremesuppe',
                        'name_es' => 'Crema de Champiñones',
                        'name_ua' => 'Грибний крем-суп',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'broccoli-cheddar-soup',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/finedining/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Broccoli Cheddar Soup',
                        'name_ar' => 'شوربة بروكلي شيدر',
                        'name_fr' => 'Soupe aux broccolis et au cheddar',
                        'name_it' => 'zuppa di broccoli con cheddar',
                        'name_de' => 'Brokkoli Cheddar Suppe',
                        'name_es' => 'Sopa de Brocoli con Queso Cheddar',
                        'name_ua' => 'Суп з чеддером з брокколі',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'main-dishes',
                'imgUrl' => 'imgs/demo/finedining/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/finedining/cat2_thumbnail.webp',
                'name_en' => 'Main dishes',
                'name_ar' => 'الأطباق الرئيسية',
                'name_fr' => 'Plats principaux',
                'name_it' => 'Piatti principali',
                'name_de' => 'Hauptgang',
                'name_es' => 'Platos principales',
                'name_ua' => 'Основні страви',
                'products' => [
                    [
                        'name' => 'grilled-lemon-chicken-breast',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/finedining/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Grilled lemon chicken breast',
                        'name_ar' => 'صدر دجاج مشوي بالليمون',
                        'name_fr' => 'Blanc de poulet grillé au citron',
                        'name_it' => 'Petto di pollo al limone grigliato',
                        'name_de' => 'Gegrillte Hähnchenbrust mit Zitrone',
                        'name_es' => 'Pechuga de pollo al limón a la plancha',
                        'name_ua' => 'Куряча грудка з лимоном на грилі',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'steak-with-mashed-potatoes',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/finedining/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Steak with mashed potatoes',
                        'name_ar' => 'ستيك مع بطاطا مهروسة',
                        'name_fr' => 'Steak avec purée de pommes de terre',
                        'name_it' => 'Bistecca con purè di patate',
                        'name_de' => 'Steak mit Kartoffelpüree',
                        'name_es' => 'bistec con puré de patatas',
                        'name_ua' => 'Стейк з картопляним пюре',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'grilled-salmon-with-honey-lemon-butter-sauce',
                        'price' => 17,
                        'imgUrl' => 'imgs/demo/finedining/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Grilled Salmon With honey lemon butter Sauce',
                        'name_ar' => 'سلمون مشوي مع صلصة زبدة الليمون والعسل',
                        'name_fr' => 'Saumon Grillé Sauce Miel Citron Beurre',
                        'name_it' => 'Salmone alla griglia con salsa di burro al miele e limone',
                        'name_de' => 'Gegrillter Lachs mit Honig-Zitronen-Butter-Sauce',
                        'name_es' => 'Salmón a la plancha con salsa de mantequilla de limón y miel',
                        'name_ua' => 'Лосось на грилі з медово-лимонно-масляним соусом',
                        'options' => [
                            [
                                'name' => 'salmon-pieces',
                                'name_en' => 'Salmon pieces',
                                'name_ar' => 'قطع سمك السلمون',
                                'name_fr' => 'Morceaux de saumon',
                                'name_it' => 'Pezzi di salmone',
                                'name_de' => 'Lachsstücke',
                                'name_es' => 'Trozos de salmón',
                                'name_ua' => 'Шматочки сьомги',
                                'selections' => [
                                    [
                                        'name' => '2-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '2 pieces',
                                        'name_ar' => '2 قطعة',
                                        'name_fr' => '2 pièces',
                                        'name_it' => '2 pezzi',
                                        'name_de' => '2 Stücke',
                                        'name_es' => '2 piezas',
                                        'name_ua' => '2 шт',
                                    ],
                                    [
                                        'name' => '3-pieces',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => '3 pieces',
                                        'name_ar' => '3 قطع',
                                        'name_fr' => '3 pièces',
                                        'name_it' => '3 pezzi',
                                        'name_de' => '3 Stück',
                                        'name_es' => '3 piezas',
                                        'name_ua' => '3 шт',
                                    ],
                                    [
                                        'name' => '4-pieces',
                                        'price' => 14,
                                        'isDefault' => false,
                                        'name_en' => '4 pieces',
                                        'name_ar' => '4 قطع',
                                        'name_fr' => '4 pièces',
                                        'name_it' => '4 pezzi',
                                        'name_de' => '4 Stück',
                                        'name_es' => '4 piezas',
                                        'name_ua' => '4 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'beef-stroganoff',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/finedining/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Beef Stroganoff',
                        'name_ar' => 'ستروجانوف اللحم',
                        'name_fr' => 'Bœuf Stroganoff',
                        'name_it' => 'Manzo alla Stroganoff',
                        'name_de' => 'Stroganoff vom Rind',
                        'name_es' => 'Stroganoff de ternera',
                        'name_ua' => 'Беф Строганов',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'side-dishes',
                'imgUrl' => 'imgs/demo/finedining/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/finedining/cat3_thumbnail.webp',
                'name_en' => 'Side Dishes',
                'name_ar' => 'أطباق جانبية',
                'name_fr' => 'Accompagnements',
                'name_it' => 'Contorni',
                'name_de' => 'Beilagen',
                'name_es' => 'Guarniciones',
                'name_ua' => 'Гарніри',
                'products' => [
                    [
                        'name' => 'ratatouille',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/finedining/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Ratatouille',
                        'name_ar' => 'راتاتوي',
                        'name_fr' => 'Ratatouille',
                        'name_it' => 'Ratatouille',
                        'name_de' => 'Ratatouille',
                        'name_es' => 'Ratatouille',
                        'name_ua' => 'Рататуй',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'garlic-bread',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/finedining/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Garlic Bread',
                        'name_ar' => 'خبز بالثوم',
                        'name_fr' => 'Pain à l\'ail',
                        'name_it' => 'Pane all\'aglio',
                        'name_de' => 'Knoblauchbrot',
                        'name_es' => 'Pan de ajo',
                        'name_ua' => 'Часниковий хліб',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '3-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '3 Pieces',
                                        'name_ar' => '3 قطع',
                                        'name_fr' => '3 pièces',
                                        'name_it' => '3 pezzi',
                                        'name_de' => '3 Stück',
                                        'name_es' => '3 piezas',
                                        'name_ua' => '3 шт',
                                    ],
                                    [
                                        'name' => '5-pieces',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '8-pieces',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => '8 Pieces',
                                        'name_ar' => '8 قطع',
                                        'name_fr' => '8 pièces',
                                        'name_it' => '8 pezzi',
                                        'name_de' => '8 Stück',
                                        'name_es' => '8 piezas',
                                        'name_ua' => '8 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'baked-potato-wedges',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/finedining/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Baked Potato Wedges',
                        'name_ar' => 'أسافين البطاطا المخبوزة',
                        'name_fr' => 'Quartiers de pommes de terre au four',
                        'name_it' => 'Spicchi Di Patate Al Forno',
                        'name_de' => 'Gebackene Kartoffelecken',
                        'name_es' => 'Gajos De Patata Al Horno',
                        'name_ua' => 'Запечені картопляні шматочки',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'ketchup',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Ketchup',
                                        'name_ar' => 'كاتشب',
                                        'name_fr' => 'Ketchup',
                                        'name_it' => 'Ketchup',
                                        'name_de' => 'Ketchup',
                                        'name_es' => 'Salsa de tomate',
                                        'name_ua' => 'Кетчуп',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/finedining/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/finedining/cat4_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'caesar-salad',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/finedining/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 2.5,
                        'imgUrl' => 'imgs/demo/finedining/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/finedining/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Pasta salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tuna-salad',
                        'price' => 4.5,
                        'imgUrl' => 'imgs/demo/finedining/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/finedining/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Tuna Salad',
                        'name_ar' => 'سلطة التونة',
                        'name_fr' => 'Salade de thon',
                        'name_it' => 'Insalata di tonno',
                        'name_de' => 'Thunfischsalat',
                        'name_es' => 'Ensalada de atún',
                        'name_ua' => 'Салат з тунцем',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($fineDining,$categories);
    }

}
