<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class friedChicken extends Seeder
{

    public function run()
    {
        $friedChicken = new stdClass();
        $friedChicken->domainName = 'friedchicken';
        $friedChicken->template = 21;
        $friedChicken->website_names = [
            'en' => 'Fried Chicken',
            'ar' => 'دجاج مقلي',
            'fr' => 'Poulet frit',
            'de' => 'Gebratenes Huhn',
            'it' => 'Pollo fritto',
            'es' => 'Pollo frito',
            'ua' => 'Смажене курча',
            'ru' => '',
        ];
        $friedChicken->intro = [
            'en' => 'The fried chicken spot you’re looking for',
            'ar' => 'بقعة الدجاج المقلي التي تبحث عنها',
            'fr' => 'Le spot de poulet frit que vous recherchez',
            'de' => 'Der Brathähnchen-Spot, den Sie suchen',
            'it' => 'Il pollo fritto che stai cercando',
            'es' => 'El lugar de pollo frito que estás buscando',
            'ua' => 'Місце зі смаженою куркою, яке ви шукаєте',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'chicken-tenders-meals',
                'imgUrl' => 'imgs/demo/friedchicken/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/friedchicken/cat1_thumbnail.webp',
                'name_en' => 'Chicken Tenders Meals',
                'name_ar' => 'وجبات تشيكن تندرز',
                'name_fr' => 'Repas de filets de poulet',
                'name_it' => 'Pasti di offerte di pollo',
                'name_de' => 'Hühnchen-Tender-Mahlzeiten',
                'name_es' => 'Comidas de filetes de pollo',
                'name_ua' => 'Курячі страви',
                'products' => [
                    [
                        'name' => '2-piece-tenders',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/friedchicken/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat1_prod1_thumbnail.webp',
                        'name_en' => '2 piece tenders',
                        'name_ar' => '2 قطعة تندرز',
                        'name_fr' => 'Offres 2 pièces',
                        'name_it' => 'Offerte da 2 pezzi',
                        'name_de' => '2 Stück Tender',
                        'name_es' => 'ofertas de 2 piezas',
                        'name_ua' => 'Тендери 2 шт',
                        'options' => [
                            [
                                'name' => 'drink',
                                'name_en' => 'Drink',
                                'name_ar' => 'يشرب',
                                'name_fr' => 'Boire',
                                'name_it' => 'Bere',
                                'name_de' => 'Getränk',
                                'name_es' => 'Bebida',
                                'name_ua' => 'пити',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'sprite',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Sprite',
                                        'name_ar' => 'شبح',
                                        'name_fr' => 'Lutin',
                                        'name_it' => 'Folletto',
                                        'name_de' => 'Sprit',
                                        'name_es' => 'Duende',
                                        'name_ua' => 'Спрайт',
                                    ],
                                    [
                                        'name' => 'fanta-strawberry',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Strawberry',
                                        'name_ar' => 'فانتا فراولة',
                                        'name_fr' => 'Fanta Fraise',
                                        'name_it' => 'Fanta Fragola',
                                        'name_de' => 'Fanta Erdbeere',
                                        'name_es' => 'Fanta Fresa',
                                        'name_ua' => 'Фанта Полуниця',
                                    ],
                                    [
                                        'name' => 'fanta-orange',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Orange',
                                        'name_ar' => 'فانتا أورانج',
                                        'name_fr' => 'Fanta orange',
                                        'name_it' => 'Fanta arancia',
                                        'name_de' => 'Fanta-Orange',
                                        'name_es' => 'Naranja Fanta',
                                        'name_ua' => 'Фанта Апельсин',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'drink-size',
                                'name_en' => 'Drink size',
                                'name_ar' => 'حجم الشراب',
                                'name_fr' => 'Taille de la boisson',
                                'name_it' => 'Dimensione della bevanda',
                                'name_de' => 'Getränkegröße',
                                'name_es' => 'Tamaño de la bebida',
                                'name_ua' => 'Розмір напою',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'fries-size',
                                'name_en' => 'Fries size',
                                'name_ar' => 'حجم البطاطس',
                                'name_fr' => 'Taille des frites',
                                'name_it' => 'Dimensioni delle patatine fritte',
                                'name_de' => 'Pommes Größe',
                                'name_es' => 'Tamaño de papas fritas',
                                'name_ua' => 'Розмір картоплі фрі',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => '4-piece-tenders',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/friedchicken/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat1_prod2_thumbnail.webp',
                        'name_en' => '4 piece tenders',
                        'name_ar' => '4 قطع تندرز',
                        'name_fr' => '4 pièces d\'offres',
                        'name_it' => 'Offerte da 4 pezzi',
                        'name_de' => '4 Stück Tender',
                        'name_es' => 'licitaciones de 4 piezas',
                        'name_ua' => 'Тендери 4 шт',
                        'options' => [
                            [
                                'name' => 'drink',
                                'name_en' => 'Drink',
                                'name_ar' => 'يشرب',
                                'name_fr' => 'Boire',
                                'name_it' => 'Bere',
                                'name_de' => 'Getränk',
                                'name_es' => 'Bebida',
                                'name_ua' => 'пити',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'sprite',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Sprite',
                                        'name_ar' => 'شبح',
                                        'name_fr' => 'Lutin',
                                        'name_it' => 'Folletto',
                                        'name_de' => 'Sprit',
                                        'name_es' => 'Duende',
                                        'name_ua' => 'Спрайт',
                                    ],
                                    [
                                        'name' => 'fanta-strawberry',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Strawberry',
                                        'name_ar' => 'فانتا فراولة',
                                        'name_fr' => 'Fanta Fraise',
                                        'name_it' => 'Fanta Fragola',
                                        'name_de' => 'Fanta Erdbeere',
                                        'name_es' => 'Fanta Fresa',
                                        'name_ua' => 'Фанта Полуниця',
                                    ],
                                    [
                                        'name' => 'fanta-orange',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Orange',
                                        'name_ar' => 'فانتا أورانج',
                                        'name_fr' => 'Fanta orange',
                                        'name_it' => 'Fanta arancia',
                                        'name_de' => 'Fanta-Orange',
                                        'name_es' => 'Naranja Fanta',
                                        'name_ua' => 'Фанта Апельсин',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'drink-size',
                                'name_en' => 'Drink size',
                                'name_ar' => 'حجم الشراب',
                                'name_fr' => 'Taille de la boisson',
                                'name_it' => 'Dimensione della bevanda',
                                'name_de' => 'Getränkegröße',
                                'name_es' => 'Tamaño de la bebida',
                                'name_ua' => 'Розмір напою',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => true,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'fries-size',
                                'name_en' => 'Fries size',
                                'name_ar' => 'حجم البطاطس',
                                'name_fr' => 'Taille des frites',
                                'name_it' => 'Dimensioni delle patatine fritte',
                                'name_de' => 'Pommes Größe',
                                'name_es' => 'Tamaño de papas fritas',
                                'name_ua' => 'Розмір картоплі фрі',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => '5-piece-tenders',
                        'price' => 18,
                        'imgUrl' => 'imgs/demo/friedchicken/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat1_prod3_thumbnail.webp',
                        'name_en' => '5 piece tenders',
                        'name_ar' => '5 قطع تندرز',
                        'name_fr' => '5 pièces d\'offres',
                        'name_it' => 'Offerte da 5 pezzi',
                        'name_de' => '5 Stück Tender',
                        'name_es' => 'licitaciones de 5 piezas',
                        'name_ua' => 'Тендери 5 шт',
                        'options' => [
                            [
                                'name' => 'drink',
                                'name_en' => 'Drink',
                                'name_ar' => 'يشرب',
                                'name_fr' => 'Boire',
                                'name_it' => 'Bere',
                                'name_de' => 'Getränk',
                                'name_es' => 'Bebida',
                                'name_ua' => 'пити',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'sprite',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Sprite',
                                        'name_ar' => 'شبح',
                                        'name_fr' => 'Lutin',
                                        'name_it' => 'Folletto',
                                        'name_de' => 'Sprit',
                                        'name_es' => 'Duende',
                                        'name_ua' => 'Спрайт',
                                    ],
                                    [
                                        'name' => 'fanta-strawberry',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Strawberry',
                                        'name_ar' => 'فانتا فراولة',
                                        'name_fr' => 'Fanta Fraise',
                                        'name_it' => 'Fanta Fragola',
                                        'name_de' => 'Fanta Erdbeere',
                                        'name_es' => 'Fanta Fresa',
                                        'name_ua' => 'Фанта Полуниця',
                                    ],
                                    [
                                        'name' => 'fanta-orange',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Orange',
                                        'name_ar' => 'فانتا أورانج',
                                        'name_fr' => 'Fanta orange',
                                        'name_it' => 'Fanta arancia',
                                        'name_de' => 'Fanta-Orange',
                                        'name_es' => 'Naranja Fanta',
                                        'name_ua' => 'Фанта Апельсин',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'drink-size',
                                'name_en' => 'Drink size',
                                'name_ar' => 'حجم الشراب',
                                'name_fr' => 'Taille de la boisson',
                                'name_it' => 'Dimensione della bevanda',
                                'name_de' => 'Getränkegröße',
                                'name_es' => 'Tamaño de la bebida',
                                'name_ua' => 'Розмір напою',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'fries-size',
                                'name_en' => 'Fries size',
                                'name_ar' => 'حجم البطاطس',
                                'name_fr' => 'Taille des frites',
                                'name_it' => 'Dimensioni delle patatine fritte',
                                'name_de' => 'Pommes Größe',
                                'name_es' => 'Tamaño de papas fritas',
                                'name_ua' => 'Розмір картоплі фрі',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => '7-piece-tenders',
                        'price' => 25,
                        'imgUrl' => 'imgs/demo/friedchicken/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat1_prod4_thumbnail.webp',
                        'name_en' => '7 piece tenders',
                        'name_ar' => '7 قطع تندرز',
                        'name_fr' => '7 pièces d\'appel d\'offres',
                        'name_it' => 'Offerte da 7 pezzi',
                        'name_de' => '7-teilige Tender',
                        'name_es' => 'ofertas de 7 piezas',
                        'name_ua' => 'Тендери 7 шт',
                        'options' => [
                            [
                                'name' => 'drink',
                                'name_en' => 'Drink',
                                'name_ar' => 'يشرب',
                                'name_fr' => 'Boire',
                                'name_it' => 'Bere',
                                'name_de' => 'Getränk',
                                'name_es' => 'Bebida',
                                'name_ua' => 'пити',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'sprite',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Sprite',
                                        'name_ar' => 'شبح',
                                        'name_fr' => 'Lutin',
                                        'name_it' => 'Folletto',
                                        'name_de' => 'Sprit',
                                        'name_es' => 'Duende',
                                        'name_ua' => 'Спрайт',
                                    ],
                                    [
                                        'name' => 'fanta-strawberry',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Strawberry',
                                        'name_ar' => 'فانتا فراولة',
                                        'name_fr' => 'Fanta Fraise',
                                        'name_it' => 'Fanta Fragola',
                                        'name_de' => 'Fanta Erdbeere',
                                        'name_es' => 'Fanta Fresa',
                                        'name_ua' => 'Фанта Полуниця',
                                    ],
                                    [
                                        'name' => 'fanta-orange',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Fanta Orange',
                                        'name_ar' => 'فانتا أورانج',
                                        'name_fr' => 'Fanta orange',
                                        'name_it' => 'Fanta arancia',
                                        'name_de' => 'Fanta-Orange',
                                        'name_es' => 'Naranja Fanta',
                                        'name_ua' => 'Фанта Апельсин',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'drink-size',
                                'name_en' => 'Drink size',
                                'name_ar' => 'حجم الشراب',
                                'name_fr' => 'Taille de la boisson',
                                'name_it' => 'Dimensione della bevanda',
                                'name_de' => 'Getränkegröße',
                                'name_es' => 'Tamaño de la bebida',
                                'name_ua' => 'Розмір напою',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'fries-size',
                                'name_en' => 'Fries size',
                                'name_ar' => 'حجم البطاطس',
                                'name_fr' => 'Taille des frites',
                                'name_it' => 'Dimensioni delle patatine fritte',
                                'name_de' => 'Pommes Größe',
                                'name_es' => 'Tamaño de papas fritas',
                                'name_ua' => 'Розмір картоплі фрі',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'sandwiches',
                'imgUrl' => 'imgs/demo/friedchicken/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/friedchicken/cat2_thumbnail.webp',
                'name_en' => 'Sandwiches',
                'name_ar' => 'شطائر',
                'name_fr' => 'Sandwichs',
                'name_it' => 'Panini',
                'name_de' => 'Sandwiches',
                'name_es' => 'Sándwiches',
                'name_ua' => 'Бутерброди',
                'products' => [
                    [
                        'name' => 'cajun-filet-sandwich',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/friedchicken/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Cajun Filet Sandwich',
                        'name_ar' => 'ساندوتش كاجون فيليه',
                        'name_fr' => 'Sandwich au filet cajun',
                        'name_it' => 'Panino al filetto di Cajun',
                        'name_de' => 'Cajun-Filet-Sandwich',
                        'name_es' => 'Sándwich de filete cajún',
                        'name_ua' => 'Сендвіч з каджунського філе',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'grilled-chicken-sandwich',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/friedchicken/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Grilled chicken Sandwich',
                        'name_ar' => 'سندويتش دجاج مشوي',
                        'name_fr' => 'Sandwich au poulet grillé',
                        'name_it' => 'Panino di pollo alla griglia',
                        'name_de' => 'Gegrilltes Hähnchen-Sandwich',
                        'name_es' => 'Sándwich de pollo a la parrilla',
                        'name_ua' => 'Сендвіч з куркою гриль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'buffalo-chicken-sandwich',
                        'price' => 9,
                        'imgUrl' => 'imgs/demo/friedchicken/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Buffalo Chicken Sandwich',
                        'name_ar' => 'ساندوتش دجاج بافلو',
                        'name_fr' => 'Sandwich au poulet Buffalo',
                        'name_it' => 'Sandwich di pollo alla bufala',
                        'name_de' => 'Büffel-Hähnchen-Sandwich',
                        'name_es' => 'Sándwich de pollo al búfalo',
                        'name_ua' => 'Сендвіч з куркою Буффало',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 9,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheddar-&-bacon-sandwich',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/friedchicken/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Cheddar & Bacon Sandwich',
                        'name_ar' => 'ساندوتش شيدر وبيكون',
                        'name_fr' => 'Sandwich Cheddar & Bacon',
                        'name_it' => 'Panino al cheddar e pancetta',
                        'name_de' => 'Cheddar-Speck-Sandwich',
                        'name_es' => 'Sándwich de queso cheddar y tocino',
                        'name_ua' => 'Сендвіч з чеддером і беконом',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'chicken-wings',
                'imgUrl' => 'imgs/demo/friedchicken/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/friedchicken/cat3_thumbnail.webp',
                'name_en' => 'Chicken Wings',
                'name_ar' => 'أجنحة دجاج',
                'name_fr' => 'Ailes de poulet',
                'name_it' => 'Ali di pollo',
                'name_de' => 'Hühnerflügel',
                'name_es' => 'Alitas de pollo',
                'name_ua' => 'Курячі крильця',
                'products' => [
                    [
                        'name' => 'buffalo-chicken-wings',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/friedchicken/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Buffalo Chicken Wings',
                        'name_ar' => 'أجنحة دجاج بافلو',
                        'name_fr' => 'Ailes de poulet Buffalo',
                        'name_it' => 'alette di pollo "Buffalo',
                        'name_de' => 'Buffalo Chicken Wings',
                        'name_es' => 'alitas de pollo Buffalo',
                        'name_ua' => 'Курячі крильця Буффало',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'boneless-buffalo-wings',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/friedchicken/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Boneless Buffalo Wings',
                        'name_ar' => 'أجنحة دجاج مخلية',
                        'name_fr' => 'Ailes de bison désossées',
                        'name_it' => 'Ali di bufalo disossate',
                        'name_de' => 'Büffelflügel ohne Knochen',
                        'name_es' => 'Alitas de búfalo deshuesadas',
                        'name_ua' => 'Крила буйвола без кісток',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'crispy-wing',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/friedchicken/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Crispy Wing',
                        'name_ar' => 'جناح مقرمش',
                        'name_fr' => 'Aile croustillante',
                        'name_it' => 'Ala croccante',
                        'name_de' => 'Knuspriger Flügel',
                        'name_es' => 'ala crujiente',
                        'name_ua' => 'Хрусткі крила',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'sides',
                'imgUrl' => 'imgs/demo/friedchicken/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/friedchicken/cat4_thumbnail.webp',
                'name_en' => 'Sides',
                'name_ar' => 'الجانبين',
                'name_fr' => 'Côtés',
                'name_it' => 'Lati',
                'name_de' => 'Seiten',
                'name_es' => 'Lados',
                'name_ua' => 'сторони',
                'products' => [
                    [
                        'name' => 'plain-french-fries',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/friedchicken/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Plain French Fries',
                        'name_ar' => 'بطاطا مقلية سادة',
                        'name_fr' => 'Frites nature',
                        'name_it' => 'Patatine fritte semplici',
                        'name_de' => 'Einfache Pommes Frites',
                        'name_es' => 'Papas Fritas Simples',
                        'name_ua' => 'Звичайна картопля фрі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'cheddar-&-bacon-loaded--fries',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/friedchicken/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Cheddar & Bacon Loaded Fries',
                        'name_ar' => 'بطاطس شيدر وبيكون لودد',
                        'name_fr' => 'Frites garnies de cheddar et de bacon',
                        'name_it' => 'Patatine fritte con formaggio cheddar e pancetta',
                        'name_de' => 'Mit Cheddar & Speck beladene Pommes',
                        'name_es' => 'Papas fritas cargadas de queso cheddar y tocino',
                        'name_ua' => 'Картопля фрі з чеддером і беконом',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'mozzarella-sticks',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/friedchicken/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Mozzarella Sticks',
                        'name_ar' => 'العصي موزاريلا',
                        'name_fr' => 'Bâtonnets de mozzarella',
                        'name_it' => 'Bastoncini di mozzarella',
                        'name_de' => 'Mozzarella-Sticks',
                        'name_es' => 'Palos de mozzarella',
                        'name_ua' => 'Палички моцарели',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'onion-rings',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/friedchicken/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/friedchicken/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Onion Rings',
                        'name_ar' => 'حلقات البصل',
                        'name_fr' => 'Rondelles d\'oignon',
                        'name_it' => 'Anelli di cipolla',
                        'name_de' => 'Zwiebelringe',
                        'name_es' => 'Aros de cebolla',
                        'name_ua' => 'Цибульні кільця',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($friedChicken,$categories);
    }

}
