<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class icecream extends Seeder
{

    public function run()
    {
        $icecream = new stdClass();
        $icecream->domainName = 'icecream';
        $icecream->website_names = [
            'en' => 'Ice cream Shop',
            'ar' => 'محل مثلجات',
            'fr' => 'Glacier',
            'de' => 'Eisdiele',
            'it' => 'Gelateria',
            'es' => 'Heladería',
            'ua' => 'Магазин морозива',
            'ru' => '',
        ];
        $icecream->intro = [
            'en' => 'Bursting flavors made for the sweet-toothed',
            'ar' => 'نكهات متفجرة مصنوعة لذوي الأسنان الحلوة',
            'fr' => 'Des saveurs éclatantes faites pour les gourmands',
            'de' => 'Knallende Aromen für Naschkatzen',
            'it' => 'Sapori esplosivi fatti per i più golosi',
            'es' => 'Explosión de sabores hechos para los golosos.',
            'ua' => 'Вибухові смаки створені для ласунів',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'classic-flavors',
                'imgUrl' => 'imgs/demo/icecream/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/icecream/cat1_thumbnail.webp',
                'name_en' => 'Classic Flavors',
                'name_ar' => 'النكهات الكلاسيكية',
                'name_fr' => 'Saveurs classiques',
                'name_it' => 'Sapori Classici',
                'name_de' => 'Klassische Aromen',
                'name_es' => 'Sabores Clásicos',
                'name_ua' => 'Класичні смаки',
                'products' => [
                    [
                        'name' => 'vanilla',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Vanilla',
                        'name_ar' => 'فانيلا',
                        'name_fr' => 'Vanille',
                        'name_it' => 'Vaniglia',
                        'name_de' => 'Vanille',
                        'name_es' => 'Vainilla',
                        'name_ua' => 'Ваніль',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chocolate',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Chocolate',
                        'name_ar' => 'شوكولاتة',
                        'name_fr' => 'Chocolat',
                        'name_it' => 'Cioccolato',
                        'name_de' => 'Schokolade',
                        'name_es' => 'Chocolate',
                        'name_ua' => 'Шоколад',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'strawberry-sorbet',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Strawberry Sorbet',
                        'name_ar' => 'الفراولة شربات',
                        'name_fr' => 'Sorbet aux fraises',
                        'name_it' => 'sorbetto alla fragola',
                        'name_de' => 'Erdbeersorbet',
                        'name_es' => 'Sorbete de fresa',
                        'name_ua' => 'Полуничний сорбет',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'mango-sorbet',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Mango Sorbet',
                        'name_ar' => 'مانجو سوربيه',
                        'name_fr' => 'sorbet à la mangue',
                        'name_it' => 'sorbetto al mango',
                        'name_de' => 'Mango Sorbet',
                        'name_es' => 'Sorbete de mango',
                        'name_ua' => 'Сорбет з манго',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'lemon',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod5_thumbnail.webp',
                        'name_en' => 'Lemon',
                        'name_ar' => 'ليمون',
                        'name_fr' => 'Citron',
                        'name_it' => 'Limone',
                        'name_de' => 'Zitrone',
                        'name_es' => 'Limón',
                        'name_ua' => 'Лимон',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'kiwi',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat1_prod6.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat1_prod6_thumbnail.webp',
                        'name_en' => 'Kiwi',
                        'name_ar' => 'كيوي',
                        'name_fr' => 'kiwi',
                        'name_it' => 'Kiwi',
                        'name_de' => 'Kiwi',
                        'name_es' => 'kiwi',
                        'name_ua' => 'Ківі',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'special-flavors',
                'imgUrl' => 'imgs/demo/icecream/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/icecream/cat2_thumbnail.webp',
                'name_en' => 'Special Flavors',
                'name_ar' => 'نكهات خاصة',
                'name_fr' => 'Saveurs spéciales',
                'name_it' => 'Sapori Speciali',
                'name_de' => 'Besondere Geschmacksrichtungen',
                'name_es' => 'Sabores Especiales',
                'name_ua' => 'Особливі смаки',
                'products' => [
                    [
                        'name' => 'white-chocolate',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat2_prod1_thumbnail.webp',
                        'name_en' => 'White Chocolate',
                        'name_ar' => 'شوكولاته بيضاء',
                        'name_fr' => 'Chocolat blanc',
                        'name_it' => 'Cioccolato bianco',
                        'name_de' => 'Weiße Schokolade',
                        'name_es' => 'Chocolate blanco',
                        'name_ua' => 'білий шоколад',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1.25,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'strawberry-cheesecake',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Strawberry Cheesecake',
                        'name_ar' => 'تشيز كيك الفراولة',
                        'name_fr' => 'Gâteau au fromage aux fraises',
                        'name_it' => 'Cheesecake alla fragola',
                        'name_de' => 'Erdbeer-Käsekuchen',
                        'name_es' => 'Tarta de queso con fresas',
                        'name_ua' => 'Полуничний чізкейк',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1.25,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cookie-dough',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Cookie Dough',
                        'name_ar' => 'كعكة العجين',
                        'name_fr' => 'Pâte à biscuits',
                        'name_it' => 'Pasta biscotto',
                        'name_de' => 'Plätzchenteig',
                        'name_es' => 'masa para galletas',
                        'name_ua' => 'Тісто для печива',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1.25,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'salted-caramel',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Salted Caramel',
                        'name_ar' => 'الكراميل المملح',
                        'name_fr' => 'Caramel salé',
                        'name_it' => 'Caramello salato',
                        'name_de' => 'Gesalzener Karamell',
                        'name_es' => 'Caramelo salado',
                        'name_ua' => 'Солона карамель',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1.25,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chocolate-fudge',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/icecream/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/icecream/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Chocolate Fudge',
                        'name_ar' => 'حلوى الشوكولاتة',
                        'name_fr' => 'Fondant au chocolat',
                        'name_it' => 'Fondente Al Cioccolato',
                        'name_de' => 'Schokoladen Toffee',
                        'name_es' => 'Dulce de chocolate',
                        'name_ua' => 'Шоколадна помадка',
                        'options' => [
                            [
                                'name' => 'scoops',
                                'name_en' => 'Scoops',
                                'name_ar' => 'المجارف',
                                'name_fr' => 'boules',
                                'name_it' => 'Scoop',
                                'name_de' => 'Schaufeln',
                                'name_es' => 'cucharadas',
                                'name_ua' => 'Совки',
                                'selections' => [
                                    [
                                        'name' => '1-scoop',
                                        'price' => 1.25,
                                        'isDefault' => true,
                                        'name_en' => '1 Scoop',
                                        'name_ar' => '1 مغرفة',
                                        'name_fr' => '1 boule',
                                        'name_it' => '1 misurino',
                                        'name_de' => '1 Schaufel',
                                        'name_es' => '1 cucharada',
                                        'name_ua' => '1 мірна ложка',
                                    ],
                                    [
                                        'name' => '2-scoops',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => '2 Scoops',
                                        'name_ar' => '2 بولة آيس كريم',
                                        'name_fr' => '2 boules',
                                        'name_it' => '2 misurini',
                                        'name_de' => '2 Kugeln',
                                        'name_es' => '2 cucharadas',
                                        'name_ua' => '2 ложки',
                                    ],
                                    [
                                        'name' => '3-scoops',
                                        'price' => 3.25,
                                        'isDefault' => false,
                                        'name_en' => '3 Scoops',
                                        'name_ar' => '3 ملاعق',
                                        'name_fr' => '3 boules',
                                        'name_it' => '3 misurini',
                                        'name_de' => '3 Kugeln',
                                        'name_es' => '3 cucharadas',
                                        'name_ua' => '3 ложки',
                                    ],
                                    [
                                        'name' => '4-scoops',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => '4 Scoops',
                                        'name_ar' => '4 ملاعق',
                                        'name_fr' => '4 boules',
                                        'name_it' => '4 misurini',
                                        'name_de' => '4 Kugeln',
                                        'name_es' => '4 cucharadas',
                                        'name_ua' => '4 ложки',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($icecream,$categories);
    }

}
