<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class indian extends Seeder
{

    public function run()
    {
        $indian = new stdClass();
        $indian->domainName = 'indian';
        $indian->website_names = [
            'en' => 'Indian',
            'ar' => 'هندي',
            'fr' => 'Indien',
            'de' => 'indisch',
            'it' => 'indiano',
            'es' => 'indio',
            'ua' => 'індійський',
            'ru' => '',
        ];
        $indian->intro = [
            'en' => 'A tale of spices and delightful tastes',
            'ar' => 'حكاية بهارات ومذاقات لذيذة',
            'fr' => 'Une histoire d\'épices et de saveurs délicieuses',
            'de' => 'Eine Geschichte von Gewürzen und köstlichen Geschmäckern',
            'it' => 'Una storia di spezie e sapori deliziosi',
            'es' => 'Una historia de especias y deliciosos sabores.',
            'ua' => 'Розповідь про спеції та чудові смаки',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'chicken-dishes',
                'imgUrl' => 'imgs/demo/indian/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/indian/cat1_thumbnail.webp',
                'name_en' => 'Chicken Dishes',
                'name_ar' => 'أطباق الدجاج',
                'name_fr' => 'Plats de poulet',
                'name_it' => 'Piatti Di Pollo',
                'name_de' => 'Hähnchengerichte',
                'name_es' => 'Platos de pollo',
                'name_ua' => 'Страви з курки',
                'products' => [
                    [
                        'name' => 'tandoori-chicken',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/indian/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Tandoori Chicken',
                        'name_ar' => 'دجاج تندوري',
                        'name_fr' => 'Poulet tandoori',
                        'name_it' => 'Pollo tandoori',
                        'name_de' => 'Tandoori Hühnchen',
                        'name_es' => 'Pollo tandoori',
                        'name_ua' => 'Курка тандурі',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'butter-chicken',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/indian/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Butter Chicken',
                        'name_ar' => 'دجاج بالزبدة',
                        'name_fr' => 'Poulet au beurre',
                        'name_it' => 'Pollo al BURRO',
                        'name_de' => 'Butterhuhn',
                        'name_es' => 'Pollo de mantequilla',
                        'name_ua' => 'Масляна курка',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-tikka-masala',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/indian/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Chicken Tikka Masala',
                        'name_ar' => 'دجاج تكا ماسالا',
                        'name_fr' => 'Poulet Tikka Masala',
                        'name_it' => 'Pollo Tikka Masala',
                        'name_de' => 'Chicken Tikka Masala',
                        'name_es' => 'Pollo tikka masala',
                        'name_ua' => 'Курка Тікка Масала',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-65',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/indian/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Chicken 65',
                        'name_ar' => 'الدجاج 65',
                        'name_fr' => 'poulet 65',
                        'name_it' => 'pollo 65',
                        'name_de' => 'Hähnchen 65',
                        'name_es' => 'Pollo 65',
                        'name_ua' => 'Курка 65',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-biryani',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/indian/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat1_prod5_thumbnail.webp',
                        'name_en' => 'Chicken Biryani',
                        'name_ar' => 'برياني دجاج',
                        'name_fr' => 'poulet Biryani',
                        'name_it' => 'pollo Biryani',
                        'name_de' => 'Hühnchen Biryani',
                        'name_es' => 'Pollo biryani',
                        'name_ua' => 'Курка Бір\'яні',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'meat-dishes',
                'imgUrl' => 'imgs/demo/indian/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/indian/cat2_thumbnail.webp',
                'name_en' => 'Meat Dishes',
                'name_ar' => 'أطباق اللحوم',
                'name_fr' => 'Plats de viande',
                'name_it' => 'Piatti di carne',
                'name_de' => 'Fleischgerichte',
                'name_es' => 'Platos con carne',
                'name_ua' => 'М\'ясні страви',
                'products' => [
                    [
                        'name' => 'beef-curry',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/indian/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Beef Curry',
                        'name_ar' => 'لحم البقر بالكاري',
                        'name_fr' => 'Bœuf au curry',
                        'name_it' => 'Manzo al curry',
                        'name_de' => 'Fleisch-Curry',
                        'name_es' => 'Carne estofada',
                        'name_ua' => 'Каррі з яловичини',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'keema',
                        'price' => 17,
                        'imgUrl' => 'imgs/demo/indian/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Keema',
                        'name_ar' => 'كيما',
                        'name_fr' => 'Keema',
                        'name_it' => 'Kema',
                        'name_de' => 'Keema',
                        'name_es' => 'keema',
                        'name_ua' => 'Кіма',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'korma',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/indian/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Korma',
                        'name_ar' => 'كورما',
                        'name_fr' => 'Korma',
                        'name_it' => 'Corma',
                        'name_de' => 'Korma',
                        'name_es' => 'Korma',
                        'name_ua' => 'Корма',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'mutton-curry',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/indian/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Mutton Curry',
                        'name_ar' => 'كاري لحم الضأن',
                        'name_fr' => 'Curry de mouton',
                        'name_it' => 'Curry di montone',
                        'name_de' => 'Hammel-Curry',
                        'name_es' => 'curry de cordero',
                        'name_ua' => 'Каррі з баранини',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'nihari',
                        'price' => 17,
                        'imgUrl' => 'imgs/demo/indian/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Nihari',
                        'name_ar' => 'نيهاري',
                        'name_fr' => 'Nihari',
                        'name_it' => 'Nihari',
                        'name_de' => 'Nihari',
                        'name_es' => 'Nihari',
                        'name_ua' => 'Ніхарі',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'side-dishes',
                'imgUrl' => 'imgs/demo/indian/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/indian/cat3_thumbnail.webp',
                'name_en' => 'Side Dishes',
                'name_ar' => 'أطباق جانبية',
                'name_fr' => 'Accompagnements',
                'name_it' => 'Contorni',
                'name_de' => 'Beilagen',
                'name_es' => 'Guarniciones',
                'name_ua' => 'Гарніри',
                'products' => [
                    [
                        'name' => 'tandoori-chicken-skewers',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/indian/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Tandoori Chicken Skewers',
                        'name_ar' => 'أسياخ دجاج تندوري',
                        'name_fr' => 'Brochettes de poulet tandoori',
                        'name_it' => 'Spiedini di pollo tandoori',
                        'name_de' => 'Tandoori-Hähnchenspieße',
                        'name_es' => 'Brochetas De Pollo Al Tandoori',
                        'name_ua' => 'Курячі шашлики тандурі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'turmeric-rice',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/indian/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Turmeric Rice',
                        'name_ar' => 'أرز الكركم',
                        'name_fr' => 'Riz au curcuma',
                        'name_it' => 'Riso alla curcuma',
                        'name_de' => 'Kurkuma-Reis',
                        'name_es' => 'Arroz con cúrcuma',
                        'name_ua' => 'Рис з куркумою',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'spiced-potatoes',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/indian/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Spiced potatoes',
                        'name_ar' => 'بطاطس متبله',
                        'name_fr' => 'Pommes de terre épicées',
                        'name_it' => 'Patate speziate',
                        'name_de' => 'Gewürzte Kartoffeln',
                        'name_es' => 'papas especiadas',
                        'name_ua' => 'Картопля зі спеціями',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'curry-roasted-cauliflower',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/indian/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Curry Roasted Cauliflower',
                        'name_ar' => 'قرنبيط محمص بالكاري',
                        'name_fr' => 'Chou-fleur rôti au curry',
                        'name_it' => 'Cavolfiore Arrostito Al Curry',
                        'name_de' => 'Curry gebratener Blumenkohl',
                        'name_es' => 'Coliflor asada al curry',
                        'name_ua' => 'Смажена цвітна капуста каррі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'grilled-masala-corn',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/indian/cat3_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat3_prod5_thumbnail.webp',
                        'name_en' => 'Grilled masala Corn',
                        'name_ar' => 'ذرة مسالا مشوية',
                        'name_fr' => 'Maïs masala grillé',
                        'name_it' => 'Mais masala alla griglia',
                        'name_de' => 'Gegrillter Masala-Mais',
                        'name_es' => 'Maíz masala a la parrilla',
                        'name_ua' => 'Кукурудза масала на грилі',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'beverages',
                'imgUrl' => 'imgs/demo/indian/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/indian/cat4_thumbnail.webp',
                'name_en' => 'Beverages',
                'name_ar' => 'المشروبات',
                'name_fr' => 'Breuvages',
                'name_it' => 'Bevande',
                'name_de' => 'Getränke',
                'name_es' => 'Bebidas',
                'name_ua' => 'Напої',
                'products' => [
                    [
                        'name' => 'water',
                        'price' => 1.5,
                        'imgUrl' => 'imgs/demo/indian/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Water',
                        'name_ar' => 'ماء',
                        'name_fr' => 'L\'eau',
                        'name_it' => 'Acqua',
                        'name_de' => 'Wasser',
                        'name_es' => 'Agua',
                        'name_ua' => 'вода',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'soda-',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/indian/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Soda ',
                        'name_ar' => 'مشروب غازي',
                        'name_fr' => 'Un soda',
                        'name_it' => 'Bibita',
                        'name_de' => 'Limonade',
                        'name_es' => 'soda',
                        'name_ua' => 'Сода',
                        'options' => [
                            [
                                'name' => 'soda',
                                'name_en' => 'Soda',
                                'name_ar' => 'مشروب غازي',
                                'name_fr' => 'Un soda',
                                'name_it' => 'Bibita',
                                'name_de' => 'Limonade',
                                'name_es' => 'soda',
                                'name_ua' => 'Сода',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'cherry-coke',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Cherry Coke',
                                        'name_ar' => 'فحم الكوك الكرز',
                                        'name_fr' => 'Coca Cerise',
                                        'name_it' => 'Coca Ciliegia',
                                        'name_de' => 'Kirsch Cola',
                                        'name_es' => 'Coca-Cola de cereza',
                                        'name_ua' => 'Вишнева кола',
                                    ],
                                    [
                                        'name' => 'vanilla-coke',
                                        'price' => 2.25,
                                        'isDefault' => false,
                                        'name_en' => 'Vanilla Coke',
                                        'name_ar' => 'فانيلا كوك',
                                        'name_fr' => 'Coca Vanille',
                                        'name_it' => 'coca cola alla vaniglia',
                                        'name_de' => 'Vanille-Cola',
                                        'name_es' => 'Coca-Cola De Vainilla',
                                        'name_ua' => 'Ванільна кола',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 1.75,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'lemonade',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/indian/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Lemonade',
                        'name_ar' => 'عصير الليمون',
                        'name_fr' => 'Limonade',
                        'name_it' => 'Limonata',
                        'name_de' => 'Limonade',
                        'name_es' => 'Limonada',
                        'name_ua' => 'Лимонад',
                        'options' => [
                            [
                                'name' => 'flavor',
                                'name_en' => 'Flavor',
                                'name_ar' => 'نكهة',
                                'name_fr' => 'Saveur',
                                'name_it' => 'Gusto',
                                'name_de' => 'Geschmack',
                                'name_es' => 'Sabor',
                                'name_ua' => 'Смак',
                                'selections' => [
                                    [
                                        'name' => 'plain',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Plain',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'strawberry-lemonade',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry Lemonade',
                                        'name_ar' => 'ليموناضة الفراولة',
                                        'name_fr' => 'Limonade de fraise',
                                        'name_it' => 'Limonata alla fragola',
                                        'name_de' => 'Erdbeerlimonade',
                                        'name_es' => 'Limonada de fresa',
                                        'name_ua' => 'Полуничний лимонад',
                                    ],
                                    [
                                        'name' => 'raspberry-lemonade',
                                        'price' => 4.5,
                                        'isDefault' => false,
                                        'name_en' => 'Raspberry Lemonade',
                                        'name_ar' => 'التوت عصير الليمون',
                                        'name_fr' => 'Limonade à la framboise',
                                        'name_it' => 'Limonata al lampone',
                                        'name_de' => 'Himbeer Limonade',
                                        'name_es' => 'Limonada de frambuesa',
                                        'name_ua' => 'Малиновий лимонад',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'iced-tea',
                        'price' => 1.5,
                        'imgUrl' => 'imgs/demo/indian/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/indian/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Iced Tea',
                        'name_ar' => 'شاي مثلج',
                        'name_fr' => 'Thé glacé',
                        'name_it' => 'Tè freddo',
                        'name_de' => 'Eistee',
                        'name_es' => 'Te helado',
                        'name_ua' => 'Холодний чай',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($indian,$categories);
    }

}
