<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class italian extends Seeder
{

    public function run()
    {
        $italian = new stdClass();
        $italian->domainName = 'italian';
        $italian->website_names = [
            'en' => 'ITALIAN',
            'ar' => 'الايطالية',
            'fr' => 'ITALIEN',
            'de' => 'ITALIENISCH',
            'it' => 'ITALIANO',
            'es' => 'ITALIANO',
            'ua' => 'ІТАЛІЙСЬКА',
            'ru' => '',
        ];
        $italian->intro = [
            'en' => 'The little eataly in town',
            'ar' => 'الأكل الصغير في المدينة',
            'fr' => 'Le petit resto en ville',
            'de' => 'Das kleine Imbiss in der Stadt',
            'it' => 'Il piccolo ristorante in città',
            'es' => 'El pequeño restaurante de la ciudad',
            'ua' => 'Маленький заклад у місті',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'pasta',
                'imgUrl' => 'imgs/demo/italian/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/italian/cat1_thumbnail.webp',
                'name_en' => 'Pasta',
                'name_ar' => 'معكرونة',
                'name_fr' => 'Pâtes',
                'name_it' => 'Pasta',
                'name_de' => 'Pasta',
                'name_es' => 'Pasta',
                'name_ua' => 'паста',
                'products' => [
                    [
                        'name' => 'spaghetti-bolognese',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Spaghetti Bolognese',
                        'name_ar' => 'فرن السباغيتي',
                        'name_fr' => 'Spaghetti bolognaise',
                        'name_it' => 'Spaghetti alla bolognese',
                        'name_de' => 'Spaghetti Bolognese',
                        'name_es' => 'Spaghetti a la boloñesa',
                        'name_ua' => 'Спагетті болоньєзе',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'parmesan-spinach-mushroom-pasta',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Parmesan Spinach Mushroom Pasta',
                        'name_ar' => 'باستا البارميزان والفطر والسبانخ',
                        'name_fr' => 'Pâtes aux champignons et épinards au parmesan',
                        'name_it' => 'Pasta ai funghi spinaci al parmigiano',
                        'name_de' => 'Parmesan-Spinat-Pilz-Nudeln',
                        'name_es' => 'Pasta De Champiñones, Espinacas Y Parmesano',
                        'name_ua' => 'Грибна паста з пармезаном і шпинатом',
                        'options' => [
                            [
                                'name' => 'extra-parmesan',
                                'name_en' => 'Extra parmesan',
                                'name_ar' => 'إضافة بارميزان',
                                'name_fr' => 'Parmesan supplémentaire',
                                'name_it' => 'parmigiano extra',
                                'name_de' => 'Zusätzlicher Parmesan',
                                'name_es' => 'extra parmesano',
                                'name_ua' => 'Екстра пармезан',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'lasagna',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Lasagna',
                        'name_ar' => 'لازانيا',
                        'name_fr' => 'Lasagne',
                        'name_it' => 'Lasagna',
                        'name_de' => 'Lasagne',
                        'name_es' => 'Lasaña',
                        'name_ua' => 'Лазанья',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'chicken-fettuccine-alfredo',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Chicken Fettuccine Alfredo',
                        'name_ar' => 'دجاج فيتوتشيني الفريدو',
                        'name_fr' => 'Poulet FETTUCCINE Alfredo',
                        'name_it' => 'Fettuccine di pollo Alfredo',
                        'name_de' => 'Hühnchen-Fettucine "Alfredo',
                        'name_es' => 'Fetuccini Alfredo De Pollo',
                        'name_ua' => 'Курячі фетучіні Альфредо',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'chicken-pesto-pasta',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod5_thumbnail.webp',
                        'name_en' => 'Chicken Pesto Pasta',
                        'name_ar' => 'باستا دجاج بالبيستو',
                        'name_fr' => 'Pâte au poulet et au pesto',
                        'name_it' => 'Pasta al pesto e pollo',
                        'name_de' => 'Hähnchen Pesto Pasta',
                        'name_es' => 'Pasta con Pesto de Pollo',
                        'name_ua' => 'Паста Песто з куркою',
                        'options' => [
                            [
                                'name' => 'parmesan',
                                'name_en' => 'parmesan',
                                'name_ar' => 'جبن بارميزان',
                                'name_fr' => 'Parmesan',
                                'name_it' => 'parmigiano',
                                'name_de' => 'Parmesan',
                                'name_es' => 'parmesano',
                                'name_ua' => 'пармезан',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'sausage-pasta',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/italian/cat1_prod6.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat1_prod6_thumbnail.webp',
                        'name_en' => 'Sausage Pasta',
                        'name_ar' => 'باستا سجق',
                        'name_fr' => 'Pâtes à la saucisse',
                        'name_it' => 'Pasta Salsiccia',
                        'name_de' => 'Wurst-Nudeln',
                        'name_es' => 'Pasta De Salchicha',
                        'name_ua' => 'Макарони з ковбасою',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'pizza',
                'imgUrl' => 'imgs/demo/italian/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/italian/cat2_thumbnail.webp',
                'name_en' => 'Pizza',
                'name_ar' => 'بيتزا',
                'name_fr' => 'Pizza',
                'name_it' => 'Pizza',
                'name_de' => 'Pizza',
                'name_es' => 'Pizza',
                'name_ua' => 'піца',
                'products' => [
                    [
                        'name' => 'bocconcini-salami-pizza',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Bocconcini Salami Pizza',
                        'name_ar' => 'بيتزا بوكونسيني سلامي',
                        'name_fr' => 'Pizza au salami bocconcini',
                        'name_it' => 'Bocconcini Salame Pizza',
                        'name_de' => 'Bocconcini-Salami-Pizza',
                        'name_es' => 'Pizza de Salami Bocconcini',
                        'name_ua' => 'Піца салямі Боккончіні',
                        'options' => [
                            [
                                'name' => 'extra-salami',
                                'name_en' => 'Extra Salami',
                                'name_ar' => 'زيادة سلامي',
                                'name_fr' => 'Salami supplémentaire',
                                'name_it' => 'Salame Extra',
                                'name_de' => 'Zusätzliche Salami',
                                'name_es' => 'Salame extra',
                                'name_ua' => 'Екстра салямі',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'pizza-carbonara',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Pizza Carbonara',
                        'name_ar' => 'بيتزا كاربونارا',
                        'name_fr' => 'Pizza Carbonara',
                        'name_it' => 'Pizze alla Carbonara',
                        'name_de' => 'Pizza Carbonara',
                        'name_es' => 'pizza carbonara',
                        'name_ua' => 'Піца Карбонара',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'pizza-diavola',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Pizza Diavola',
                        'name_ar' => 'بيتزا ديافولا',
                        'name_fr' => 'Pizza Diavola',
                        'name_it' => 'Pizza Diavolo',
                        'name_de' => 'Pizza Diavola',
                        'name_es' => 'Pizza Diavola',
                        'name_ua' => 'Піца Діавола',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'pizza-marinara',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Pizza Marinara',
                        'name_ar' => 'بيتزا مارينارا',
                        'name_fr' => 'Pizza Marinara',
                        'name_it' => 'Pizza Marinara',
                        'name_de' => 'Pizza Marinara',
                        'name_es' => 'pizza marinera',
                        'name_ua' => 'Піца Маринара',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'veggie-pizza',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Veggie pizza',
                        'name_ar' => 'بيتزا خضار',
                        'name_fr' => 'Pizza végétarienne',
                        'name_it' => 'Pizza vegetariana',
                        'name_de' => 'Vegetarische Pizza',
                        'name_es' => 'pizza vegetariana',
                        'name_ua' => 'Овочева піца',
                        'options' => [
                            [
                                'name' => 'extra-vegetables',
                                'name_en' => 'Extra Vegetables',
                                'name_ar' => 'خضروات اضافية',
                                'name_fr' => 'Légumes supplémentaires',
                                'name_it' => 'Extra Verdure',
                                'name_de' => 'Zusätzliches Gemüse',
                                'name_es' => 'Verduras adicionales',
                                'name_ua' => 'Додаткові овочі',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cheese-pizza',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/italian/cat2_prod6.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat2_prod6_thumbnail.webp',
                        'name_en' => 'Cheese Pizza',
                        'name_ar' => 'جبن البيتزا',
                        'name_fr' => 'Pizza au fromage',
                        'name_it' => 'Pizza al formaggio',
                        'name_de' => 'Käse-Pizza',
                        'name_es' => 'Pizza de queso',
                        'name_ua' => 'сирна піца',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/italian/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/italian/cat3_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'pumpkin-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/italian/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Pumpkin Salad',
                        'name_ar' => 'سلطة اليقطين',
                        'name_fr' => 'Salade de potiron',
                        'name_it' => 'Insalata Di Zucca',
                        'name_de' => 'Kürbissalat',
                        'name_es' => 'Ensalada De Calabaza',
                        'name_ua' => 'Салат з гарбуза',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'caesar-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/italian/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/italian/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'kale-salad',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/italian/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Kale Salad',
                        'name_ar' => 'سلطة الكرنب',
                        'name_fr' => 'Salade de chou frisé',
                        'name_it' => 'Insalata Di Cavolo',
                        'name_de' => 'Grünkohl Salat',
                        'name_es' => 'Ensalada de col rizada',
                        'name_ua' => 'Салат з капусти',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/italian/cat3_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/italian/cat3_prod5_thumbnail.webp',
                        'name_en' => 'Pasta Salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($italian,$categories);
    }

}
