<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class patisserie extends Seeder
{

    public function run()
    {
        $patisserie = new stdClass();
        $patisserie->domainName = 'patisserie';
        $patisserie->website_names = [
            'en' => 'Patisserie',
            'ar' => 'المعجنات',
            'fr' => 'Pâtisserie',
            'de' => 'Konditorei',
            'it' => 'pasticceria',
            'es' => 'Pastelería',
            'ua' => 'Кондитерська',
            'ru' => '',
        ];
        $patisserie->intro = [
            'en' => 'We are best at what we love most',
            'ar' => 'نحن الأفضل فيما نحب أكثر',
            'fr' => 'Nous sommes meilleurs dans ce que nous aimons le plus',
            'de' => 'Wir sind am besten in dem, was wir am meisten lieben',
            'it' => 'Siamo i migliori in ciò che amiamo di più',
            'es' => 'Somos mejores en lo que más amamos',
            'ua' => 'Ми найкращі в тому, що любимо найбільше',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'pastry',
                'imgUrl' => 'imgs/demo/patisserie/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/patisserie/cat1_thumbnail.webp',
                'name_en' => 'Pastry',
                'name_ar' => 'معجنات',
                'name_fr' => 'Pâtisserie',
                'name_it' => 'Pasticcino',
                'name_de' => 'Gebäck',
                'name_es' => 'Pastelería',
                'name_ua' => 'Кондитерські вироби',
                'products' => [
                    [
                        'name' => 'croissant',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/patisserie/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Croissant',
                        'name_ar' => 'كرواسون',
                        'name_fr' => 'Croissant',
                        'name_it' => 'Brioche',
                        'name_de' => 'Croissant',
                        'name_es' => 'Cuerno',
                        'name_ua' => 'Круасан',
                        'options' => [
                            [
                                'name' => 'croissant',
                                'name_en' => 'Croissant',
                                'name_ar' => 'كرواسون',
                                'name_fr' => 'Croissant',
                                'name_it' => 'Brioche',
                                'name_de' => 'Croissant',
                                'name_es' => 'Cuerno',
                                'name_ua' => 'Круасан',
                                'selections' => [
                                    [
                                        'name' => 'plain',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Plain',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'cheese',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Cheese',
                                        'name_ar' => 'جبنه',
                                        'name_fr' => 'Fromage',
                                        'name_it' => 'Il formaggio',
                                        'name_de' => 'Käse',
                                        'name_es' => 'Queso',
                                        'name_ua' => 'Сир',
                                    ],
                                    [
                                        'name' => 'turkey',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Turkey',
                                        'name_ar' => 'ديك رومى',
                                        'name_fr' => 'Turquie',
                                        'name_it' => 'Tacchino',
                                        'name_de' => 'Truthahn',
                                        'name_es' => 'Pavo',
                                        'name_ua' => 'Туреччина',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'bagel',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Bagel',
                        'name_ar' => 'بيجل',
                        'name_fr' => 'Beignet',
                        'name_it' => 'Bagel',
                        'name_de' => 'Bagel',
                        'name_es' => 'Rosquilla',
                        'name_ua' => 'Бублик',
                        'options' => [
                            [
                                'name' => 'bagel',
                                'name_en' => 'Bagel',
                                'name_ar' => 'بيجل',
                                'name_fr' => 'Beignet',
                                'name_it' => 'Bagel',
                                'name_de' => 'Bagel',
                                'name_es' => 'Rosquilla',
                                'name_ua' => 'Бублик',
                                'selections' => [
                                    [
                                        'name' => 'plain-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Plain ',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'cheese',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Cheese',
                                        'name_ar' => 'جبنه',
                                        'name_fr' => 'Fromage',
                                        'name_it' => 'Il formaggio',
                                        'name_de' => 'Käse',
                                        'name_es' => 'Queso',
                                        'name_ua' => 'Сир',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'danish',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Danish',
                        'name_ar' => 'دانماركي',
                        'name_fr' => 'danois',
                        'name_it' => 'danese',
                        'name_de' => 'dänisch',
                        'name_es' => 'danés',
                        'name_ua' => 'датська',
                        'options' => [
                            [
                                'name' => 'danish',
                                'name_en' => 'Danish',
                                'name_ar' => 'دانماركي',
                                'name_fr' => 'danois',
                                'name_it' => 'danese',
                                'name_de' => 'dänisch',
                                'name_es' => 'danés',
                                'name_ua' => 'датська',
                                'selections' => [
                                    [
                                        'name' => 'plain',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Plain',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'filled-with-jam',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Filled with jam',
                                        'name_ar' => 'مليئة بالمربى',
                                        'name_fr' => 'Rempli de confiture',
                                        'name_it' => 'Ripieno di marmellata',
                                        'name_de' => 'Gefüllt mit Marmelade',
                                        'name_es' => 'relleno de mermelada',
                                        'name_ua' => 'Залито варенням',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'donuts',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/patisserie/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Donuts',
                        'name_ar' => 'دونات',
                        'name_fr' => 'Beignets',
                        'name_it' => 'Ciambelle',
                        'name_de' => 'Donuts',
                        'name_es' => 'donas',
                        'name_ua' => 'Пончики',
                        'options' => [
                            [
                                'name' => 'donuts',
                                'name_en' => 'Donuts',
                                'name_ar' => 'دونات',
                                'name_fr' => 'Beignets',
                                'name_it' => 'Ciambelle',
                                'name_de' => 'Donuts',
                                'name_es' => 'donas',
                                'name_ua' => 'Пончики',
                                'selections' => [
                                    [
                                        'name' => 'chocolate',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Chocolate',
                                        'name_ar' => 'شوكولاتة',
                                        'name_fr' => 'Chocolat',
                                        'name_it' => 'Cioccolato',
                                        'name_de' => 'Schokolade',
                                        'name_es' => 'Chocolate',
                                        'name_ua' => 'Шоколад',
                                    ],
                                    [
                                        'name' => 'glazed',
                                        'price' => 3,
                                        'isDefault' => true,
                                        'name_en' => 'Glazed',
                                        'name_ar' => 'المزجج',
                                        'name_fr' => 'Vitré',
                                        'name_it' => 'Smaltato',
                                        'name_de' => 'Glasiert',
                                        'name_es' => 'Vidriado',
                                        'name_ua' => 'Засклені',
                                    ],
                                    [
                                        'name' => 'crème',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Crème',
                                        'name_ar' => 'كريمة',
                                        'name_fr' => 'Crème',
                                        'name_it' => 'Crema',
                                        'name_de' => 'Creme',
                                        'name_es' => 'crema',
                                        'name_ua' => 'крем',
                                    ],
                                    [
                                        'name' => 'jam',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Jam',
                                        'name_ar' => 'مربى',
                                        'name_fr' => 'Confiture',
                                        'name_it' => 'Marmellata',
                                        'name_de' => 'Marmelade',
                                        'name_es' => 'Mermelada',
                                        'name_ua' => 'Варення',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'pies',
                'imgUrl' => 'imgs/demo/patisserie/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/patisserie/cat2_thumbnail.webp',
                'name_en' => 'Pies',
                'name_ar' => 'الفطائر',
                'name_fr' => 'Tartes',
                'name_it' => 'Torte',
                'name_de' => 'Kuchen',
                'name_es' => 'empanadas',
                'name_ua' => 'Пироги',
                'products' => [
                    [
                        'name' => 'pumpkin-pie',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Pumpkin pie',
                        'name_ar' => 'فطيرة اليقطين',
                        'name_fr' => 'Tarte à la citrouille',
                        'name_it' => 'Torta di zucca',
                        'name_de' => 'Kürbiskuchen',
                        'name_es' => 'Pastel de calabaza',
                        'name_ua' => 'Гарбузовий пиріг',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'apple-pie',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Apple pie',
                        'name_ar' => 'فطيرة تفاح',
                        'name_fr' => 'tarte aux pommes',
                        'name_it' => 'torta di mele',
                        'name_de' => 'Apfelkuchen',
                        'name_es' => 'Tarta de manzana',
                        'name_ua' => 'яблучний пиріг',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'cherry-pie',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/patisserie/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Cherry pie',
                        'name_ar' => 'فطيرة الكرز',
                        'name_fr' => 'Tarte aux cerises',
                        'name_it' => 'torta di ciliegie',
                        'name_de' => 'Kirschkuchen',
                        'name_es' => 'pastel de cerezas',
                        'name_ua' => 'Вишневий пиріг',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'drinks',
                'imgUrl' => 'imgs/demo/patisserie/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/patisserie/cat3_thumbnail.webp',
                'name_en' => 'Drinks',
                'name_ar' => 'مشروبات',
                'name_fr' => 'Boissons',
                'name_it' => 'Bevande',
                'name_de' => 'Getränke',
                'name_es' => 'Bebidas',
                'name_ua' => 'Напої',
                'products' => [
                    [
                        'name' => 'cappuccino',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Cappuccino',
                        'name_ar' => 'كابتشينو',
                        'name_fr' => 'Cappuccino',
                        'name_it' => 'Cappuccino',
                        'name_de' => 'Cappuccino',
                        'name_es' => 'Capuchino',
                        'name_ua' => 'Капучіно',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'latte',
                        'price' => 4.5,
                        'imgUrl' => 'imgs/demo/patisserie/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Latte',
                        'name_ar' => 'لاتيه',
                        'name_fr' => 'Latté',
                        'name_it' => 'Latte macchiato',
                        'name_de' => 'Latté',
                        'name_es' => 'Latté',
                        'name_ua' => 'латте',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2.25,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'hot-chocolate',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/patisserie/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Hot chocolate',
                        'name_ar' => 'شكولاته ساخنة',
                        'name_fr' => 'Chocolat chaud',
                        'name_it' => 'Cioccolata calda',
                        'name_de' => 'Heiße Schokolade',
                        'name_es' => 'Chocolate caliente',
                        'name_ua' => 'Гарячий шоколад',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'large',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'milkshake',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/patisserie/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/patisserie/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Milkshake',
                        'name_ar' => 'اللبن المخفوق',
                        'name_fr' => 'Milk-shake',
                        'name_it' => 'Frappè',
                        'name_de' => 'Milchshake',
                        'name_es' => 'Batido',
                        'name_ua' => 'молочний коктейль',
                        'options' => [
                            [
                                'name' => 'milkshake',
                                'name_en' => 'Milkshake',
                                'name_ar' => 'اللبن المخفوق',
                                'name_fr' => 'Milk-shake',
                                'name_it' => 'Frappè',
                                'name_de' => 'Milchshake',
                                'name_es' => 'Batido',
                                'name_ua' => 'молочний коктейль',
                                'selections' => [
                                    [
                                        'name' => 'vanilla-special-milkshake',
                                        'price' => 7,
                                        'isDefault' => true,
                                        'name_en' => 'Vanilla Special Milkshake',
                                        'name_ar' => 'ميلك شيك الفانيليا الخاص',
                                        'name_fr' => 'Milkshake Spécial Vanille',
                                        'name_it' => 'Frappè speciale alla vaniglia',
                                        'name_de' => 'Vanille-Spezial-Milchshake',
                                        'name_es' => 'Malteada especial de vainilla',
                                        'name_ua' => 'Ванільний спеціальний молочний коктейль',
                                    ],
                                    [
                                        'name' => 'chocolate-milkshake',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => 'Chocolate Milkshake',
                                        'name_ar' => 'ميلك شيك شوكولاتة',
                                        'name_fr' => 'Milkshake au chocolat',
                                        'name_it' => 'Frappè Al Cioccolato',
                                        'name_de' => 'Schokoladenmilchshake',
                                        'name_es' => 'Malteada de chocolate',
                                        'name_ua' => 'Шоколадний молочний коктейль',
                                    ],
                                    [
                                        'name' => 'strawberry-milkshake',
                                        'price' => 6.5,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry Milkshake',
                                        'name_ar' => 'مخفوق الحليب بالفرواله',
                                        'name_fr' => 'Milkshake à la fraise',
                                        'name_it' => 'Frullato alla fragola',
                                        'name_de' => 'Erdbeer Milchshake',
                                        'name_es' => 'Batido de fresa',
                                        'name_ua' => 'Полуничний молочний коктейль',
                                    ],
                                    [
                                        'name' => 'buttermilk-banana-milkshake',
                                        'price' => 7.5,
                                        'isDefault' => false,
                                        'name_en' => 'Buttermilk Banana Milkshake',
                                        'name_ar' => 'اللبن والموز ميلك شيك',
                                        'name_fr' => 'Milkshake aux bananes et au babeurre',
                                        'name_it' => 'Frappè alla banana e latticello',
                                        'name_de' => 'Buttermilch-Bananen-Milchshake',
                                        'name_es' => 'Batido De Plátano Y Suero De Mantequilla',
                                        'name_ua' => 'Пахта банановий молочний коктейль',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($patisserie,$categories);
    }

}
