<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class sandwiches extends Seeder
{

    public function run()
    {
        $sandwiches = new stdClass();
        $sandwiches->domainName = 'sandwiches';
        $sandwiches->website_names = [
            'en' => 'Sandwiches',
            'ar' => 'شطائر',
            'fr' => 'Sandwichs',
            'de' => 'Sandwiches',
            'it' => 'Panini',
            'es' => 'Sándwiches',
            'ua' => 'Бутерброди',
            'ru' => '',
        ];
        $sandwiches->intro = [
            'en' => 'Where freshness meets savoriness',
            'ar' => 'حيث تلتقي النضارة بالطعم',
            'fr' => 'Quand la fraîcheur rencontre la saveur',
            'de' => 'Wo Frische auf Herzlichkeit trifft',
            'it' => 'Dove la freschezza incontra la sapidità',
            'es' => 'Donde la frescura se encuentra con el sabor',
            'ua' => 'Де свіжість зустрічається зі смаком',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'sandwiches',
                'imgUrl' => 'imgs/demo/sandwiches/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_thumbnail.webp',
                'name_en' => 'Sandwiches',
                'name_ar' => 'شطائر',
                'name_fr' => 'Sandwichs',
                'name_it' => 'Panini',
                'name_de' => 'Sandwiches',
                'name_es' => 'Sándwiches',
                'name_ua' => 'Бутерброди',
                'products' => [
                    [
                        'name' => 'avocado-chicken-sandwich-',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/sandwiches/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Avocado Chicken Sandwich ',
                        'name_ar' => 'ساندوتش دجاج أفوكادو',
                        'name_fr' => 'Sandwich au poulet à l\'avocat',
                        'name_it' => 'Panino di pollo all\'avocado',
                        'name_de' => 'Avocado-Huhn-Sandwich',
                        'name_es' => 'Sándwich De Pollo Con Aguacate',
                        'name_ua' => 'Сендвіч з куркою з авокадо',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'ham-and-cheese',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/sandwiches/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Ham and Cheese',
                        'name_ar' => 'لحم خنزير و جبنة',
                        'name_fr' => 'Jambon et fromage',
                        'name_it' => 'Prosciutto e formaggio',
                        'name_de' => 'Schinken und Käse',
                        'name_es' => 'Jamón y queso',
                        'name_ua' => 'Шинка і сир',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'tuna-sandwich',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Tuna Sandwich',
                        'name_ar' => 'ساندوتش تونة',
                        'name_fr' => 'Sandwich au thon',
                        'name_it' => 'Panino al tonno',
                        'name_de' => 'Thunfisch Sandwich',
                        'name_es' => 'Sandwich de atún',
                        'name_ua' => 'Сендвіч з тунцем',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'classic-hotdog',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Classic Hotdog',
                        'name_ar' => 'كلاسيك هوت دوج',
                        'name_fr' => 'Hot-dog classique',
                        'name_it' => 'Hot dog classico',
                        'name_de' => 'Klassischer Hotdog',
                        'name_es' => 'Perrito caliente clásico',
                        'name_ua' => 'Класичний хот-дог',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'grilled-chicken',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/sandwiches/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat1_prod5_thumbnail.webp',
                        'name_en' => 'Grilled Chicken',
                        'name_ar' => 'دجاج مشوي',
                        'name_fr' => 'Poulet grillé',
                        'name_it' => 'Pollo grigliato',
                        'name_de' => 'Gegrilltes Hühnchen',
                        'name_es' => 'Pollo a la parrilla',
                        'name_ua' => 'Курка-гриль',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 3.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'wraps',
                'imgUrl' => 'imgs/demo/sandwiches/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_thumbnail.webp',
                'name_en' => 'Wraps',
                'name_ar' => 'يلف',
                'name_fr' => 'Wraps',
                'name_it' => 'Avvolge',
                'name_de' => 'Wraps',
                'name_es' => 'Envolturas',
                'name_ua' => 'обгортання',
                'products' => [
                    [
                        'name' => 'veggie-wrap',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/sandwiches/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Veggie Wrap',
                        'name_ar' => 'الخضروات التالفه',
                        'name_fr' => 'Wrap végétarien',
                        'name_it' => 'Involtino vegetariano',
                        'name_de' => 'Veggie Wrap',
                        'name_es' => 'Envoltura de verduras',
                        'name_ua' => 'Овочева упаковка',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 1.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 6.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'breakfast-wrap',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/sandwiches/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Breakfast Wrap',
                        'name_ar' => 'راب الإفطار',
                        'name_fr' => 'Wrap petit-déjeuner',
                        'name_it' => 'Impacco per la colazione',
                        'name_de' => 'Frühstücks-Wrap',
                        'name_es' => 'Envoltura de desayuno',
                        'name_ua' => 'Обгортка для сніданку',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'turkey-wrap',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Turkey Wrap',
                        'name_ar' => 'راب ديك رومي',
                        'name_fr' => 'Wrap à la dinde',
                        'name_it' => 'Involtino di tacchino',
                        'name_de' => 'Truthahn-Wrap',
                        'name_es' => 'Envoltura de Pavo',
                        'name_ua' => 'Обгортка з індички',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'chicken-wrap',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/sandwiches/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Chicken Wrap',
                        'name_ar' => 'راب دجاج',
                        'name_fr' => 'Wrap au poulet',
                        'name_it' => 'Involtino di pollo',
                        'name_de' => 'Hühner-Wrap',
                        'name_es' => 'Wrap de pollo',
                        'name_ua' => 'Куряче обгортання',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'club-wrap',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Club Wrap',
                        'name_ar' => 'كلوب راب',
                        'name_fr' => 'Enveloppe de club',
                        'name_it' => 'Avvolgere il club',
                        'name_de' => 'Club-Wrap',
                        'name_es' => 'Envoltura de club',
                        'name_ua' => 'Club Wrap',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular ',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 2.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 7.5,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/sandwiches/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/sandwiches/cat3_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'caesar-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/sandwiches/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/sandwiches/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Pasta salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'tuna-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sandwiches/cat3_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sandwiches/cat3_prod4_thumbnail.webp',
                        'name_en' => 'Tuna Salad',
                        'name_ar' => 'سلطة التونة',
                        'name_fr' => 'Salade de thon',
                        'name_it' => 'Insalata di tonno',
                        'name_de' => 'Thunfischsalat',
                        'name_es' => 'Ensalada de atún',
                        'name_ua' => 'Салат з тунцем',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($sandwiches,$categories);
    }

}
