<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class steakhouse extends Seeder
{

    public function run()
    {
        $steakhouse = new stdClass();
        $steakhouse->domainName = 'steakhouse';
        $steakhouse->template = 18;
        $steakhouse->website_names = [
            'en' => 'Steakhouse',
            'ar' => 'بيت شرائح اللحم',
            'fr' => 'Steak House',
            'de' => 'Steak-House',
            'it' => 'Bisteccheria',
            'es' => 'Asador',
            'ua' => 'Стейк-хаус',
            'ru' => '',
        ];
        $steakhouse->intro = [
            'en' => 'Prime grade steakhouse',
            'ar' => 'مطعم ستيك هاوس من الدرجة الممتازة',
            'fr' => 'Steakhouse de première qualité',
            'de' => 'Erstklassiges Steakhouse',
            'it' => 'Steakhouse di prima qualità',
            'es' => 'Asador de primer nivel',
            'ua' => 'Стейк-хаус вищого сорту',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'steaks-and-ribs',
                'imgUrl' => 'imgs/demo/steakhouse/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/steakhouse/cat1_thumbnail.webp',
                'name_en' => 'Steaks and Ribs',
                'name_ar' => 'ستيك و ريش',
                'name_fr' => 'Steaks et côtes levées',
                'name_it' => 'Bistecche e costolette',
                'name_de' => 'Steaks und Rippchen',
                'name_es' => 'bistecs y costillas',
                'name_ua' => 'Стейки і ребра',
                'products' => [
                    [
                        'name' => 'beef-steak',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/steakhouse/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Beef Steak',
                        'name_ar' => 'شريحة لحم البقر',
                        'name_fr' => 'Steak de bœuf',
                        'name_it' => 'Bistecca di manzo',
                        'name_de' => 'Rindersteak',
                        'name_es' => 'Filete de ternera',
                        'name_ua' => 'Біфштекс',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'beef-brisket',
                        'price' => 16,
                        'imgUrl' => 'imgs/demo/steakhouse/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Beef Brisket',
                        'name_ar' => 'لحم بريسكت',
                        'name_fr' => 'Poitrine de boeuf',
                        'name_it' => 'Petto Di Manzo',
                        'name_de' => 'Rinderbrust',
                        'name_es' => 'Bistec de carne',
                        'name_ua' => 'Яловича грудка',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'prime-rib-roast',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/steakhouse/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Prime Rib Roast',
                        'name_ar' => 'الضلع المحمص',
                        'name_fr' => 'Rôti de côte de bœuf',
                        'name_it' => 'Arrosto di costolette di prima qualità',
                        'name_de' => 'Prime Rib Roast',
                        'name_es' => 'Primer asado de costilla',
                        'name_ua' => 'Перше смажене реберце',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'grilled-steak',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/steakhouse/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Grilled Steak',
                        'name_ar' => 'شريحة لحم مشوية',
                        'name_fr' => 'Steak grillé',
                        'name_it' => 'Bistecca alla griglia',
                        'name_de' => 'Gegrilltes Steak',
                        'name_es' => 'Fillete a la parrilla',
                        'name_ua' => 'Стейк на грилі',
                        'options' => [
                            [
                                'name' => 'sauce',
                                'name_en' => 'Sauce',
                                'name_ar' => 'صلصة',
                                'name_fr' => 'sauce',
                                'name_it' => 'Salsa',
                                'name_de' => 'Soße',
                                'name_es' => 'Salsa',
                                'name_ua' => 'Соус',
                                'selections' => [
                                    [
                                        'name' => 'mayonnaise',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Mayonnaise',
                                        'name_ar' => 'مايونيز',
                                        'name_fr' => 'Mayonnaise',
                                        'name_it' => 'Maionese',
                                        'name_de' => 'Mayonnaise',
                                        'name_es' => 'Mayonesa',
                                        'name_ua' => 'майонез',
                                    ],
                                    [
                                        'name' => 'bbq-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'BBQ sauce',
                                        'name_ar' => 'صلصة شواء',
                                        'name_fr' => 'Sauce barbecue',
                                        'name_it' => 'Salsa barbecue',
                                        'name_de' => 'Grillsoße',
                                        'name_es' => 'salsa BBQ',
                                        'name_ua' => 'соус барбекю',
                                    ],
                                    [
                                        'name' => 'ranch-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Ranch sauce',
                                        'name_ar' => 'صلصة رانش',
                                        'name_fr' => 'sauce ranch',
                                        'name_it' => 'Salsa al ranch',
                                        'name_de' => 'Ranch-Sauce',
                                        'name_es' => 'salsa ranchera',
                                        'name_ua' => 'Соус ранчо',
                                    ],
                                    [
                                        'name' => 'thousand-island-sauce',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Thousand island sauce',
                                        'name_ar' => 'صلصة ثاوزند ايلاند',
                                        'name_fr' => 'Sauce mille îles',
                                        'name_it' => 'Salsa mille isole',
                                        'name_de' => 'Tausend-Insel-Sauce',
                                        'name_es' => 'salsa mil islas',
                                        'name_ua' => 'Соус тисяча островів',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'beef-sandwiches',
                'imgUrl' => 'imgs/demo/steakhouse/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/steakhouse/cat2_thumbnail.webp',
                'name_en' => 'Beef Sandwiches',
                'name_ar' => 'سندويتشات لحم بقري',
                'name_fr' => 'Sandwichs au boeuf',
                'name_it' => 'Panini Di Manzo',
                'name_de' => 'Rindfleisch-Sandwiches',
                'name_es' => 'Sándwiches De Carne',
                'name_ua' => 'Бутерброди з яловичиною',
                'products' => [
                    [
                        'name' => 'pulled-pork-bbq-sandwich',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/steakhouse/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Pulled Pork BBQ sandwich',
                        'name_ar' => 'شطيرة لحم الخنزير المشوي',
                        'name_fr' => 'Sandwich BBQ au porc effiloché',
                        'name_it' => 'Sandwich BBQ di maiale stirato',
                        'name_de' => 'Pulled Pork BBQ-Sandwich',
                        'name_es' => 'Sándwich BBQ de puerco desmenuzado',
                        'name_ua' => 'Бутерброд барбекю зі свинини',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'reuben-sandwich',
                        'price' => 8,
                        'imgUrl' => 'imgs/demo/steakhouse/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Reuben Sandwich',
                        'name_ar' => 'ساندوتش روبن',
                        'name_fr' => 'Ruben Sandwich',
                        'name_it' => 'Ruben Sandwich',
                        'name_de' => 'Reuben Sandwich',
                        'name_es' => 'Sándwich Rubén',
                        'name_ua' => 'Сендвіч Рубен',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'roast-beef-sandwich',
                        'price' => 7.5,
                        'imgUrl' => 'imgs/demo/steakhouse/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Roast beef sandwich',
                        'name_ar' => 'لحم البقر المشوي ساندويتش',
                        'name_fr' => 'Sandwich au bœuf rôti',
                        'name_it' => 'Panino al roast beef',
                        'name_de' => 'Rinderbraten-Sandwich',
                        'name_es' => 'Sándwich de carne asada',
                        'name_ua' => 'Бутерброд з ростбіфом',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combo',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'shredded-meat-sandwich',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/steakhouse/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Shredded meat sandwich',
                        'name_ar' => 'شطيرة لحم مبشور',
                        'name_fr' => 'Sandwich à la viande effilochée',
                        'name_it' => 'Sandwich di carne tritata',
                        'name_de' => 'Sandwich mit zerkleinertem Fleisch',
                        'name_es' => 'Sándwich de carne deshebrada',
                        'name_ua' => 'Сендвіч з подрібненим м\'ясом',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'regular',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Regular',
                                        'name_ar' => 'عادي',
                                        'name_fr' => 'Ordinaire',
                                        'name_it' => 'Regolare',
                                        'name_de' => 'Regulär',
                                        'name_es' => 'Regular',
                                        'name_ua' => 'Регулярний',
                                    ],
                                    [
                                        'name' => 'regular-combo',
                                        'price' => 4,
                                        'isDefault' => false,
                                        'name_en' => 'Regular combo',
                                        'name_ar' => 'كومبو عادي',
                                        'name_fr' => 'Combinaison régulière',
                                        'name_it' => 'Combo regolare',
                                        'name_de' => 'Regelmäßige Kombi',
                                        'name_es' => 'combinación normal',
                                        'name_ua' => 'Звичайне комбо',
                                    ],
                                    [
                                        'name' => 'large-',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => 'Large ',
                                        'name_ar' => 'كبير',
                                        'name_fr' => 'Grande',
                                        'name_it' => 'Di grandi dimensioni',
                                        'name_de' => 'Groß',
                                        'name_es' => 'Largo',
                                        'name_ua' => 'Великий',
                                    ],
                                    [
                                        'name' => 'large-combo',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => 'Large combo',
                                        'name_ar' => 'كومبو كبير',
                                        'name_fr' => 'Grand combiné',
                                        'name_it' => 'Grande combinazione',
                                        'name_de' => 'Große Kombi',
                                        'name_es' => 'combinación grande',
                                        'name_ua' => 'Велике комбо',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'side-dishes',
                'imgUrl' => 'imgs/demo/steakhouse/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/steakhouse/cat3_thumbnail.webp',
                'name_en' => 'Side dishes',
                'name_ar' => 'أطباق جانبية',
                'name_fr' => 'Accompagnements',
                'name_it' => 'Contorni',
                'name_de' => 'Beilagen',
                'name_es' => 'Guarniciones',
                'name_ua' => 'Гарніри',
                'products' => [
                    [
                        'name' => 'ratatouille',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/steakhouse/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Ratatouille',
                        'name_ar' => 'راتاتوي',
                        'name_fr' => 'Ratatouille',
                        'name_it' => 'Ratatouille',
                        'name_de' => 'Ratatouille',
                        'name_es' => 'Ratatouille',
                        'name_ua' => 'Рататуй',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'garlic-bread',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/steakhouse/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Garlic Bread',
                        'name_ar' => 'خبز بالثوم',
                        'name_fr' => 'Pain à l\'ail',
                        'name_it' => 'Pane all\'aglio',
                        'name_de' => 'Knoblauchbrot',
                        'name_es' => 'Pan de ajo',
                        'name_ua' => 'Часниковий хліб',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'baked-potato-wedges',
                        'price' => 3,
                        'imgUrl' => 'imgs/demo/steakhouse/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Baked Potato Wedges',
                        'name_ar' => 'أسافين البطاطا المخبوزة',
                        'name_fr' => 'Quartiers de pommes de terre au four',
                        'name_it' => 'Spicchi Di Patate Al Forno',
                        'name_de' => 'Gebackene Kartoffelecken',
                        'name_es' => 'Gajos De Patata Al Horno',
                        'name_ua' => 'Запечені картопляні шматочки',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'salads',
                'imgUrl' => 'imgs/demo/steakhouse/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_thumbnail.webp',
                'name_en' => 'Salads',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'pumpkin-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/steakhouse/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Pumpkin Salad',
                        'name_ar' => 'سلطة اليقطين',
                        'name_fr' => 'Salade de potiron',
                        'name_it' => 'Insalata Di Zucca',
                        'name_de' => 'Kürbissalat',
                        'name_es' => 'Ensalada De Calabaza',
                        'name_ua' => 'Салат з гарбуза',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'caesar-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/steakhouse/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 3.5,
                        'imgUrl' => 'imgs/demo/steakhouse/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'kale-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/steakhouse/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Kale Salad',
                        'name_ar' => 'سلطة الكرنب',
                        'name_fr' => 'Salade de chou frisé',
                        'name_it' => 'Insalata Di Cavolo',
                        'name_de' => 'Grünkohl Salat',
                        'name_es' => 'Ensalada de col rizada',
                        'name_ua' => 'Салат з капусти',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4.5,
                        'imgUrl' => 'imgs/demo/steakhouse/cat4_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/steakhouse/cat4_prod5_thumbnail.webp',
                        'name_en' => 'Pasta Salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($steakhouse,$categories);
    }

}
