<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class sushiBar extends Seeder
{

    public function run()
    {
        $sushiBar = new stdClass();
        $sushiBar->domainName = 'sushibar';
        $sushiBar->website_names = [
            'en' => 'Sushi Bar',
            'ar' => 'شريط السوشي',
            'fr' => 'Bar à sushi',
            'de' => 'Sushi-Bar',
            'it' => 'Sushibar',
            'es' => 'Barra de sushi',
            'ua' => 'суші бар',
            'ru' => '',
        ];
        $sushiBar->intro = [
            'en' => 'Rolls on rolls',
            'ar' => 'لفات على لفات',
            'fr' => 'Rouleaux sur rouleaux',
            'de' => 'Rollen auf Rollen',
            'it' => 'Rotoli su rotoli',
            'es' => 'rollos en rollos',
            'ua' => 'Рулети на рулетики',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'classic-sushi-rolls',
                'imgUrl' => 'imgs/demo/sushibar/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/sushibar/cat1_thumbnail.webp',
                'name_en' => 'Classic Sushi Rolls',
                'name_ar' => 'كلاسيك سوشي رولز',
                'name_fr' => 'Rouleaux de sushi classiques',
                'name_it' => 'Rotoli di sushi classici',
                'name_de' => 'Klassische Sushi-Rollen',
                'name_es' => 'Rollos de sushi clásicos',
                'name_ua' => 'Класичні суші роли',
                'products' => [
                    [
                        'name' => 'cucumber-roll',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Cucumber roll',
                        'name_ar' => 'لفة الخيار',
                        'name_fr' => 'Rouleau de concombre',
                        'name_it' => 'Rotolo di cetriolo',
                        'name_de' => 'Gurkenrolle',
                        'name_es' => 'rollo de pepino',
                        'name_ua' => 'Огірковий рулет',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '5-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '10-pieces',
                                        'price' => 6,
                                        'isDefault' => false,
                                        'name_en' => '10 Pieces',
                                        'name_ar' => '10 حبات',
                                        'name_fr' => '10 morceaux',
                                        'name_it' => '10 pezzi',
                                        'name_de' => '10 Stück',
                                        'name_es' => '10 piezas',
                                        'name_ua' => '10 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'philadelphia-roll',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Philadelphia Roll',
                        'name_ar' => 'فيلادلفيا رول',
                        'name_fr' => 'Rouleau de Philadelphie',
                        'name_it' => 'Rotolo Filadelfia',
                        'name_de' => 'Philadelphia-Rolle',
                        'name_es' => 'rollo filadelfia',
                        'name_ua' => 'Рол Філадельфія',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '4-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '4 Pieces',
                                        'name_ar' => '4 قطع',
                                        'name_fr' => '4 pièces',
                                        'name_it' => '4 pezzi',
                                        'name_de' => '4 Stück',
                                        'name_es' => '4 piezas',
                                        'name_ua' => '4 шт',
                                    ],
                                    [
                                        'name' => '8-pieces',
                                        'price' => 10,
                                        'isDefault' => false,
                                        'name_en' => '8 Pieces',
                                        'name_ar' => '8 قطع',
                                        'name_fr' => '8 pièces',
                                        'name_it' => '8 pezzi',
                                        'name_de' => '8 Stück',
                                        'name_es' => '8 piezas',
                                        'name_ua' => '8 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'spicy-tuna-roll',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Spicy Tuna Roll',
                        'name_ar' => 'لفة التونة حار',
                        'name_fr' => 'Rouleau de thon épicé',
                        'name_it' => 'Rotolo di tonno piccante',
                        'name_de' => 'Scharfe Thunfischrolle',
                        'name_es' => 'Rollo de atún picante',
                        'name_ua' => 'Пряний рулет з тунця',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '5-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '10-pieces',
                                        'price' => 8,
                                        'isDefault' => false,
                                        'name_en' => '10 Pieces',
                                        'name_ar' => '10 حبات',
                                        'name_fr' => '10 morceaux',
                                        'name_it' => '10 pezzi',
                                        'name_de' => '10 Stück',
                                        'name_es' => '10 piezas',
                                        'name_ua' => '10 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'alaska-roll',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Alaska Roll',
                        'name_ar' => 'رول ألاسكا',
                        'name_fr' => 'Rouleau d\'Alaska',
                        'name_it' => 'Rotolo dell\'Alaska',
                        'name_de' => 'Alaska-Rolle',
                        'name_es' => 'Rollo de Alaska',
                        'name_ua' => 'Ролл Аляска',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '4-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '4 Pieces',
                                        'name_ar' => '4 قطع',
                                        'name_fr' => '4 pièces',
                                        'name_it' => '4 pezzi',
                                        'name_de' => '4 Stück',
                                        'name_es' => '4 piezas',
                                        'name_ua' => '4 шт',
                                    ],
                                    [
                                        'name' => '8-pieces',
                                        'price' => 9,
                                        'isDefault' => false,
                                        'name_en' => '8 Pieces',
                                        'name_ar' => '8 قطع',
                                        'name_fr' => '8 pièces',
                                        'name_it' => '8 pezzi',
                                        'name_de' => '8 Stück',
                                        'name_es' => '8 piezas',
                                        'name_ua' => '8 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'king-crab-roll',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod5_thumbnail.webp',
                        'name_en' => 'King Crab Roll',
                        'name_ar' => 'كينج كراب رول',
                        'name_fr' => 'Rouleau de crabe royal',
                        'name_it' => 'Rotolo di granchio reale',
                        'name_de' => 'Königskrabbenrolle',
                        'name_es' => 'Rollo de cangrejo real',
                        'name_ua' => 'Рулет з королівського краба',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '5-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '10-pieces',
                                        'price' => 12,
                                        'isDefault' => false,
                                        'name_en' => '10 Pieces',
                                        'name_ar' => '10 حبات',
                                        'name_fr' => '10 morceaux',
                                        'name_it' => '10 pezzi',
                                        'name_de' => '10 Stück',
                                        'name_es' => '10 piezas',
                                        'name_ua' => '10 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'dragon-roll',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod6.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod6_thumbnail.webp',
                        'name_en' => 'Dragon Roll',
                        'name_ar' => 'دراجون رول',
                        'name_fr' => 'Rouleau de dragon',
                        'name_it' => 'Rotolo di drago',
                        'name_de' => 'Drachenrolle',
                        'name_es' => 'Rollo de dragón',
                        'name_ua' => 'Дракон Ролл',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '5-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '10-pieces',
                                        'price' => 11,
                                        'isDefault' => false,
                                        'name_en' => '10 Pieces',
                                        'name_ar' => '10 حبات',
                                        'name_fr' => '10 morceaux',
                                        'name_it' => '10 pezzi',
                                        'name_de' => '10 Stück',
                                        'name_es' => '10 piezas',
                                        'name_ua' => '10 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'salmon-roll',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod7.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod7_thumbnail.webp',
                        'name_en' => 'Salmon Roll',
                        'name_ar' => 'رول سلمون',
                        'name_fr' => 'Rouleau de saumon',
                        'name_it' => 'Rotolo di salmone',
                        'name_de' => 'Lachsrolle',
                        'name_es' => 'Rollo de salmón',
                        'name_ua' => 'Рол з лосося',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '4-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '4 Pieces',
                                        'name_ar' => '4 قطع',
                                        'name_fr' => '4 pièces',
                                        'name_it' => '4 pezzi',
                                        'name_de' => '4 Stück',
                                        'name_es' => '4 piezas',
                                        'name_ua' => '4 шт',
                                    ],
                                    [
                                        'name' => '8-pieces',
                                        'price' => 12,
                                        'isDefault' => false,
                                        'name_en' => '8 Pieces',
                                        'name_ar' => '8 قطع',
                                        'name_fr' => '8 pièces',
                                        'name_it' => '8 pezzi',
                                        'name_de' => '8 Stück',
                                        'name_es' => '8 piezas',
                                        'name_ua' => '8 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'california-roll-tempura',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/sushibar/cat1_prod8.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat1_prod8_thumbnail.webp',
                        'name_en' => 'California Roll Tempura',
                        'name_ar' => 'كاليفورنيا رول تيمبورا',
                        'name_fr' => 'Rouleau californien tempura',
                        'name_it' => 'Tempura di rotolo californiano',
                        'name_de' => 'Kalifornische Roll-Tempura',
                        'name_es' => 'Tempura de rollo de California',
                        'name_ua' => 'Каліфорнійський рол темпура',
                        'options' => [
                            [
                                'name' => 'pieces',
                                'name_en' => 'Pieces',
                                'name_ar' => 'قِطَع',
                                'name_fr' => 'Pièces',
                                'name_it' => 'Pezzi',
                                'name_de' => 'Stücke',
                                'name_es' => 'Piezas',
                                'name_ua' => 'штук',
                                'selections' => [
                                    [
                                        'name' => '5-pieces',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => '5 Pieces',
                                        'name_ar' => '5 قطع',
                                        'name_fr' => '5 pièces',
                                        'name_it' => '5 pezzi',
                                        'name_de' => '5 Stücke',
                                        'name_es' => '5 piezas',
                                        'name_ua' => '5 шт',
                                    ],
                                    [
                                        'name' => '10-pieces',
                                        'price' => 5,
                                        'isDefault' => false,
                                        'name_en' => '10 Pieces',
                                        'name_ar' => '10 حبات',
                                        'name_fr' => '10 morceaux',
                                        'name_it' => '10 pezzi',
                                        'name_de' => '10 Stück',
                                        'name_es' => '10 piezas',
                                        'name_ua' => '10 шт',
                                    ],
                                ]
                            ],
                        ]
                    ],

                ]
            ],
            [
                'name' => 'bowls',
                'imgUrl' => 'imgs/demo/sushibar/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/sushibar/cat2_thumbnail.webp',
                'name_en' => 'Bowls',
                'name_ar' => 'الطاسات',
                'name_fr' => 'Boules',
                'name_it' => 'Ciotole',
                'name_de' => 'Schalen',
                'name_es' => 'Bochas',
                'name_ua' => 'миски',
                'products' => [
                    [
                        'name' => 'salmon-teriyaki-bowl',
                        'price' => 15,
                        'imgUrl' => 'imgs/demo/sushibar/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Salmon Teriyaki Bowl',
                        'name_ar' => 'صحن سلمون ترياكي',
                        'name_fr' => 'Bol de saumon teriyaki',
                        'name_it' => 'Ciotola di salmone Teriyaki',
                        'name_de' => 'Lachs-Teriyaki-Schüssel',
                        'name_es' => 'Cuenco Teriyaki De Salmón',
                        'name_ua' => 'Чаша Теріякі з лососем',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'steak-teriyaki-bowl',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/sushibar/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Steak Teriyaki Bowl',
                        'name_ar' => 'طبق ستيك ترياكي',
                        'name_fr' => 'Bol de bifteck teriyaki',
                        'name_it' => 'Ciotola di bistecca Teriyaki',
                        'name_de' => 'Steak-Teriyaki-Schüssel',
                        'name_es' => 'Tazón de bistec teriyaki',
                        'name_ua' => 'Стейк Теріякі Чаша',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'salmon-poke-bowl',
                        'price' => 14,
                        'imgUrl' => 'imgs/demo/sushibar/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Salmon Poke Bowl',
                        'name_ar' => 'سلمون بوك باول',
                        'name_fr' => 'Poke Bowl au saumon',
                        'name_it' => 'Ciotola Di Poke Al Salmone',
                        'name_de' => 'Poke Bowl mit Lachs',
                        'name_es' => 'Poké Bowl de salmón',
                        'name_ua' => 'Чаша з лососем',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'ahi-tuna-poke-bowl',
                        'price' => 13,
                        'imgUrl' => 'imgs/demo/sushibar/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Ahi Tuna Poke Bowl',
                        'name_ar' => 'آهي تونا بوك باول',
                        'name_fr' => 'Poke Bowl au thon Ahi',
                        'name_it' => 'Ciotola di tonno Ahi',
                        'name_de' => 'Ahi Thunfisch Poke Bowl',
                        'name_es' => 'Poke Bowl de atún aleta amarilla',
                        'name_ua' => 'Чаша з тунцем Ahi',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'soups',
                'imgUrl' => 'imgs/demo/sushibar/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/sushibar/cat3_thumbnail.webp',
                'name_en' => 'Soups',
                'name_ar' => 'الحساء',
                'name_fr' => 'Soupes',
                'name_it' => 'Zuppe',
                'name_de' => 'Suppen',
                'name_es' => 'sopas',
                'name_ua' => 'Супи',
                'products' => [
                    [
                        'name' => 'shrimp-soup',
                        'price' => 12,
                        'imgUrl' => 'imgs/demo/sushibar/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Shrimp Soup',
                        'name_ar' => 'شوربة روبيان',
                        'name_fr' => 'Soupe aux crevettes',
                        'name_it' => 'Zuppa Di Gamberi',
                        'name_de' => 'Schrimpsuppe',
                        'name_es' => 'Sopa de camarones',
                        'name_ua' => 'Суп з креветками',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'miso-soup',
                        'price' => 11,
                        'imgUrl' => 'imgs/demo/sushibar/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Miso Soup',
                        'name_ar' => 'حساء ميسو',
                        'name_fr' => 'Soupe miso',
                        'name_it' => 'Zuppa di miso',
                        'name_de' => 'Miso-Suppe',
                        'name_es' => 'Sopa de miso',
                        'name_ua' => 'Суп-місо',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'entrees',
                'imgUrl' => 'imgs/demo/sushibar/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/sushibar/cat4_thumbnail.webp',
                'name_en' => 'Entrees',
                'name_ar' => 'مقبلات',
                'name_fr' => 'Entrées',
                'name_it' => 'Antipasti',
                'name_de' => 'Vorspeisen',
                'name_es' => 'Entradas',
                'name_ua' => 'Перші страви',
                'products' => [
                    [
                        'name' => 'yakisoba-noodles',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/sushibar/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Yakisoba Noodles',
                        'name_ar' => 'نودلز ياكيسوبا',
                        'name_fr' => 'Nouilles Yakisoba',
                        'name_it' => 'Tagliatelle Yakisoba',
                        'name_de' => 'Yakisoba-Nudeln',
                        'name_es' => 'Fideos Yakisoba',
                        'name_ua' => 'Локшина Якісоба',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'wasabi-sauce',
                        'price' => 3.5,
                        'imgUrl' => 'imgs/demo/sushibar/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Wasabi Sauce',
                        'name_ar' => 'صلصة وسابي',
                        'name_fr' => 'Sauce wasabi',
                        'name_it' => 'Salsa Wasabi',
                        'name_de' => 'Wasabi-Sauce',
                        'name_es' => 'Salsa Wasabi',
                        'name_ua' => 'Соус васабі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'chicken-katsu',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/sushibar/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Chicken Katsu',
                        'name_ar' => 'كاتسو دجاج',
                        'name_fr' => 'poulet Katsu',
                        'name_it' => 'pollo Katsu',
                        'name_de' => 'Huhn Katsu',
                        'name_es' => 'Pollo Katsu',
                        'name_ua' => 'Курка кацу',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'teriyaki-udon',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/sushibar/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/sushibar/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Teriyaki Udon',
                        'name_ar' => 'ترياكي أودون',
                        'name_fr' => 'Udon teriyaki',
                        'name_it' => 'Teriyaki Udon',
                        'name_de' => 'Teriyaki-Udon',
                        'name_es' => 'Udón teriyaki',
                        'name_ua' => 'Теріякі Удон',
                        'options' => [
                            [
                                'name' => 'spicy',
                                'name_en' => 'Spicy',
                                'name_ar' => 'حار',
                                'name_fr' => 'Épicé',
                                'name_it' => 'Speziato',
                                'name_de' => 'Würzig',
                                'name_es' => 'Picante',
                                'name_ua' => 'Пряний',
                                'selections' => [
                                    [
                                        'name' => 'yes',
                                        'price' => 0,
                                        'isDefault' => false,
                                        'name_en' => 'Yes',
                                        'name_ar' => 'نعم',
                                        'name_fr' => 'Oui',
                                        'name_it' => 'sì',
                                        'name_de' => 'Ja',
                                        'name_es' => 'Sí',
                                        'name_ua' => 'Так',
                                    ],
                                    [
                                        'name' => 'no',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'No',
                                        'name_ar' => 'لا',
                                        'name_fr' => 'Non',
                                        'name_it' => 'No',
                                        'name_de' => 'Nein',
                                        'name_es' => 'No',
                                        'name_ua' => 'Немає',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
        ];
        demo::website($sushiBar,$categories);
    }

}
