<?php

namespace Database\Seeders\demo;

use App\Models\demo;
use Illuminate\Database\Seeder;
use stdClass;

class vegetarian extends Seeder
{

    public function run()
    {
        $vegetarian = new stdClass();
        $vegetarian->domainName = 'vegetarian';
        $vegetarian->template = 14;
        $vegetarian->website_names = [
            'en' => 'Vegetarian Restaurant',
            'ar' => 'مطعم نباتي',
            'fr' => 'Restaurant végétarien',
            'de' => 'Vegetarisches Restaurant',
            'it' => 'Ristorante vegetariano',
            'es' => 'Restaurante vegetariano',
            'ua' => 'Вегетаріанський ресторан',
            'ru' => '',
        ];
        $vegetarian->intro = [
            'en' => 'The perfect balance between healthy and delicious',
            'ar' => 'التوازن المثالي بين الصحي واللذيذ',
            'fr' => 'L\'équilibre parfait entre sain et délicieux',
            'de' => 'Die perfekte Balance zwischen gesund und lecker',
            'it' => 'Il perfetto equilibrio tra sano e delizioso',
            'es' => 'El equilibrio perfecto entre saludable y delicioso.',
            'ua' => 'Ідеальний баланс між корисним і смачним',
            'ru' => '',
        ];
        $categories = [
            [
                'name' => 'salads-',
                'imgUrl' => 'imgs/demo/vegetarian/cat1.webp',
                'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_thumbnail.webp',
                'name_en' => 'Salads ',
                'name_ar' => 'سلطة',
                'name_fr' => 'Salades',
                'name_it' => 'Insalate',
                'name_de' => 'Salate',
                'name_es' => 'ensaladas',
                'name_ua' => 'Салати',
                'products' => [
                    [
                        'name' => 'pumpkin-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat1_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_prod1_thumbnail.webp',
                        'name_en' => 'Pumpkin Salad',
                        'name_ar' => 'سلطة اليقطين',
                        'name_fr' => 'Salade de potiron',
                        'name_it' => 'Insalata Di Zucca',
                        'name_de' => 'Kürbissalat',
                        'name_es' => 'Ensalada De Calabaza',
                        'name_ua' => 'Салат з гарбуза',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small ',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'caesar-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/vegetarian/cat1_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_prod2_thumbnail.webp',
                        'name_en' => 'Caesar Salad',
                        'name_ar' => 'سلطة سيزر',
                        'name_fr' => 'Salade César',
                        'name_it' => 'Insalata Cesare',
                        'name_de' => 'Caesar Salat',
                        'name_es' => 'Ensalada César',
                        'name_ua' => 'Салат Цезар',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small ',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'greek-salad',
                        'price' => 4,
                        'imgUrl' => 'imgs/demo/vegetarian/cat1_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_prod3_thumbnail.webp',
                        'name_en' => 'Greek salad',
                        'name_ar' => 'سلطة يونانية',
                        'name_fr' => 'salade grecque',
                        'name_it' => 'Insalata greca',
                        'name_de' => 'griechischer Salat',
                        'name_es' => 'ensalada griega',
                        'name_ua' => 'Грецький салат',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small ',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'kale-salad',
                        'price' => 5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat1_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_prod4_thumbnail.webp',
                        'name_en' => 'Kale Salad',
                        'name_ar' => 'سلطة الكرنب',
                        'name_fr' => 'Salade de chou frisé',
                        'name_it' => 'Insalata Di Cavolo',
                        'name_de' => 'Grünkohl Salat',
                        'name_es' => 'Ensalada de col rizada',
                        'name_ua' => 'Салат з капусти',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small ',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'pasta-salad',
                        'price' => 4.5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat1_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat1_prod5_thumbnail.webp',
                        'name_en' => 'Pasta Salad',
                        'name_ar' => 'سلطة الباستا',
                        'name_fr' => 'Salade de pâtes',
                        'name_it' => 'Insalata di pasta',
                        'name_de' => 'Nudelsalat',
                        'name_es' => 'Ensalada de pasta',
                        'name_ua' => 'Салат з макаронів',
                        'options' => [
                            [
                                'name' => 'size',
                                'name_en' => 'Size',
                                'name_ar' => 'بحجم',
                                'name_fr' => 'Taille',
                                'name_it' => 'Taglia',
                                'name_de' => 'Größe',
                                'name_es' => 'Tamaño',
                                'name_ua' => 'Розмір',
                                'selections' => [
                                    [
                                        'name' => 'small-',
                                        'price' => 0,
                                        'isDefault' => true,
                                        'name_en' => 'Small ',
                                        'name_ar' => 'صغير',
                                        'name_fr' => 'Petit',
                                        'name_it' => 'Piccolo',
                                        'name_de' => 'Klein',
                                        'name_es' => 'Pequeña',
                                        'name_ua' => 'Маленький',
                                    ],
                                    [
                                        'name' => 'medium',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Medium',
                                        'name_ar' => 'متوسط',
                                        'name_fr' => 'Moyen',
                                        'name_it' => 'medio',
                                        'name_de' => 'Mittel',
                                        'name_es' => 'Medio',
                                        'name_ua' => 'Середній',
                                    ],
                                ]
                            ],
                        ]
                    ],
                ]
            ],
            [
                'name' => 'main-dishes',
                'imgUrl' => 'imgs/demo/vegetarian/cat2.webp',
                'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_thumbnail.webp',
                'name_en' => 'Main dishes',
                'name_ar' => 'الأطباق الرئيسية',
                'name_fr' => 'Plats principaux',
                'name_it' => 'Piatti principali',
                'name_de' => 'Hauptgang',
                'name_es' => 'Platos principales',
                'name_ua' => 'Основні страви',
                'products' => [
                    [
                        'name' => 'curry-roasted-cauliflower',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/vegetarian/cat2_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_prod1_thumbnail.webp',
                        'name_en' => 'Curry Roasted Cauliflower',
                        'name_ar' => 'قرنبيط محمص بالكاري',
                        'name_fr' => 'Chou-fleur rôti au curry',
                        'name_it' => 'Cavolfiore Arrostito Al Curry',
                        'name_de' => 'Curry gebratener Blumenkohl',
                        'name_es' => 'Coliflor asada al curry',
                        'name_ua' => 'Смажена цвітна капуста каррі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'vegetables-stir-fry',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/vegetarian/cat2_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_prod2_thumbnail.webp',
                        'name_en' => 'Vegetables Stir Fry',
                        'name_ar' => 'خضار مقلي',
                        'name_fr' => 'Sauté de Légumes',
                        'name_it' => 'Verdure saltate in padella',
                        'name_de' => 'Gemüsepfannenbraten',
                        'name_es' => 'Salteado De Verduras',
                        'name_ua' => 'Обсмажити овочі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'veggie-pasta',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/vegetarian/cat2_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_prod3_thumbnail.webp',
                        'name_en' => 'Veggie Pasta',
                        'name_ar' => 'باستا نباتية',
                        'name_fr' => 'Pâtes aux légumes',
                        'name_it' => 'Pasta Vegetale',
                        'name_de' => 'Vegetarische Nudeln',
                        'name_es' => 'Pasta vegetariana',
                        'name_ua' => 'Овочева паста',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'chili-bowl',
                        'price' => 6.5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat2_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_prod4_thumbnail.webp',
                        'name_en' => 'Chili Bowl',
                        'name_ar' => 'وعاء الفلفل الحار',
                        'name_fr' => 'Bol de chili',
                        'name_it' => 'Ciotola di peperoncino',
                        'name_de' => 'Chili-Bowl',
                        'name_es' => 'Tazón de Chile',
                        'name_ua' => 'Чаша чилі',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'black-bean-rice',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/vegetarian/cat2_prod5.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat2_prod5_thumbnail.webp',
                        'name_en' => 'Black Bean Rice',
                        'name_ar' => 'أرز الفاصوليا السوداء',
                        'name_fr' => 'Riz aux haricots noirs',
                        'name_it' => 'Riso ai fagioli neri',
                        'name_de' => 'Reis mit schwarzen Bohnen',
                        'name_es' => 'Arroz De Frijoles Negros',
                        'name_ua' => 'Чорний бобовий рис',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'side-dishes',
                'imgUrl' => 'imgs/demo/vegetarian/cat3.webp',
                'thumbnailUrl' => 'imgs/demo/vegetarian/cat3_thumbnail.webp',
                'name_en' => 'Side dishes',
                'name_ar' => 'أطباق جانبية',
                'name_fr' => 'Accompagnements',
                'name_it' => 'Contorni',
                'name_de' => 'Beilagen',
                'name_es' => 'Guarniciones',
                'name_ua' => 'Гарніри',
                'products' => [
                    [
                        'name' => 'carrot-hummus-dip',
                        'price' => 7,
                        'imgUrl' => 'imgs/demo/vegetarian/cat3_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat3_prod1_thumbnail.webp',
                        'name_en' => 'Carrot Hummus dip',
                        'name_ar' => 'صلصة الحمص والجزر',
                        'name_fr' => 'Trempette aux carottes et houmous',
                        'name_it' => 'Salsa di hummus di carote',
                        'name_de' => 'Karotten-Hummus-Dip',
                        'name_es' => 'Dip de hummus de zanahoria',
                        'name_ua' => 'Морквяний хумус',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'eggplant-caponata-with-bread',
                        'price' => 6,
                        'imgUrl' => 'imgs/demo/vegetarian/cat3_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat3_prod2_thumbnail.webp',
                        'name_en' => 'Eggplant Caponata with bread',
                        'name_ar' => 'كابوناتا الباذنجان مع الخبز',
                        'name_fr' => 'Caponata d\'aubergine avec du pain',
                        'name_it' => 'Caponata di melanzane con pane',
                        'name_de' => 'Auberginen-Caponata mit Brot',
                        'name_es' => 'Caponata de berenjena con pan',
                        'name_ua' => 'Капоната з баклажанів з хлібом',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'cowboy-caviar',
                        'price' => 10,
                        'imgUrl' => 'imgs/demo/vegetarian/cat3_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat3_prod3_thumbnail.webp',
                        'name_en' => 'Cowboy Caviar',
                        'name_ar' => 'كاوبوي كافيار',
                        'name_fr' => 'Caviar de cow-boy',
                        'name_it' => 'Caviale del Cowboy',
                        'name_de' => 'Cowboy Caviar',
                        'name_es' => 'Caviar vaquero',
                        'name_ua' => 'Ковбойська ікра',
                        'options' => [
                        ]
                    ],
                ]
            ],
            [
                'name' => 'beverages',
                'imgUrl' => 'imgs/demo/vegetarian/cat4.webp',
                'thumbnailUrl' => 'imgs/demo/vegetarian/cat4_thumbnail.webp',
                'name_en' => 'Beverages',
                'name_ar' => 'المشروبات',
                'name_fr' => 'Breuvages',
                'name_it' => 'Bevande',
                'name_de' => 'Getränke',
                'name_es' => 'Bebidas',
                'name_ua' => 'Напої',
                'products' => [
                    [
                        'name' => 'water',
                        'price' => 1.5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat4_prod1.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat4_prod1_thumbnail.webp',
                        'name_en' => 'Water',
                        'name_ar' => 'ماء',
                        'name_fr' => 'L\'eau',
                        'name_it' => 'Acqua',
                        'name_de' => 'Wasser',
                        'name_es' => 'Agua',
                        'name_ua' => 'вода',
                        'options' => [
                        ]
                    ],
                    [
                        'name' => 'soda-',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/vegetarian/cat4_prod2.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat4_prod2_thumbnail.webp',
                        'name_en' => 'Soda ',
                        'name_ar' => 'مشروب غازي',
                        'name_fr' => 'Un soda',
                        'name_it' => 'Bibita',
                        'name_de' => 'Limonade',
                        'name_es' => 'soda',
                        'name_ua' => 'Сода',
                        'options' => [
                            [
                                'name' => 'coke',
                                'name_en' => 'Coke',
                                'name_ar' => 'فحم الكوك',
                                'name_fr' => 'du Coca',
                                'name_it' => 'Coca Cola',
                                'name_de' => 'Koks',
                                'name_es' => 'Coca',
                                'name_ua' => 'Кокс',
                                'selections' => [
                                    [
                                        'name' => 'coca-cola',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Coca Cola',
                                        'name_ar' => 'كوكا كولا',
                                        'name_fr' => 'Coca Cola',
                                        'name_it' => 'Coca Cola',
                                        'name_de' => 'Coca Cola',
                                        'name_es' => 'Coca Cola',
                                        'name_ua' => 'Кока-Кола',
                                    ],
                                    [
                                        'name' => 'cherry-coke',
                                        'price' => 2,
                                        'isDefault' => false,
                                        'name_en' => 'Cherry Coke',
                                        'name_ar' => 'فحم الكوك الكرز',
                                        'name_fr' => 'Coca Cerise',
                                        'name_it' => 'Coca Ciliegia',
                                        'name_de' => 'Kirsch Cola',
                                        'name_es' => 'Coca-Cola de cereza',
                                        'name_ua' => 'Вишнева кола',
                                    ],
                                    [
                                        'name' => 'vanilla-coke',
                                        'price' => 2.25,
                                        'isDefault' => false,
                                        'name_en' => 'Vanilla Coke',
                                        'name_ar' => 'فانيلا كوك',
                                        'name_fr' => 'Coca Vanille',
                                        'name_it' => 'coca cola alla vaniglia',
                                        'name_de' => 'Vanille-Cola',
                                        'name_es' => 'Coca-Cola De Vainilla',
                                        'name_ua' => 'Ванільна кола',
                                    ],
                                    [
                                        'name' => 'diet-coke',
                                        'price' => 1.75,
                                        'isDefault' => false,
                                        'name_en' => 'Diet Coke',
                                        'name_ar' => 'كولا للحمية',
                                        'name_fr' => 'Coca light',
                                        'name_it' => 'Diet Coke',
                                        'name_de' => 'Diät-Cola',
                                        'name_es' => 'Coca-Cola Light',
                                        'name_ua' => 'Дієтична кола',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'lemonade',
                        'price' => 0,
                        'imgUrl' => 'imgs/demo/vegetarian/cat4_prod3.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat4_prod3_thumbnail.webp',
                        'name_en' => 'Lemonade',
                        'name_ar' => 'عصير الليمون',
                        'name_fr' => 'Limonade',
                        'name_it' => 'Limonata',
                        'name_de' => 'Limonade',
                        'name_es' => 'Limonada',
                        'name_ua' => 'Лимонад',
                        'options' => [
                            [
                                'name' => 'flavor',
                                'name_en' => 'Flavor',
                                'name_ar' => 'نكهة',
                                'name_fr' => 'Saveur',
                                'name_it' => 'Gusto',
                                'name_de' => 'Geschmack',
                                'name_es' => 'Sabor',
                                'name_ua' => 'Смак',
                                'selections' => [
                                    [
                                        'name' => 'plain',
                                        'price' => 1.5,
                                        'isDefault' => true,
                                        'name_en' => 'Plain',
                                        'name_ar' => 'سهل',
                                        'name_fr' => 'Plaine',
                                        'name_it' => 'Pianura',
                                        'name_de' => 'Schmucklos',
                                        'name_es' => 'Llanura',
                                        'name_ua' => 'Рівнина',
                                    ],
                                    [
                                        'name' => 'strawberry-lemonade',
                                        'price' => 3,
                                        'isDefault' => false,
                                        'name_en' => 'Strawberry Lemonade',
                                        'name_ar' => 'ليموناضة الفراولة',
                                        'name_fr' => 'Limonade de fraise',
                                        'name_it' => 'Limonata alla fragola',
                                        'name_de' => 'Erdbeerlimonade',
                                        'name_es' => 'Limonada de fresa',
                                        'name_ua' => 'Полуничний лимонад',
                                    ],
                                    [
                                        'name' => 'raspberry-lemonade',
                                        'price' => 4.5,
                                        'isDefault' => false,
                                        'name_en' => 'Raspberry Lemonade',
                                        'name_ar' => 'التوت عصير الليمون',
                                        'name_fr' => 'Limonade à la framboise',
                                        'name_it' => 'Limonata al lampone',
                                        'name_de' => 'Himbeer Limonade',
                                        'name_es' => 'Limonada de frambuesa',
                                        'name_ua' => 'Малиновий лимонад',
                                    ],
                                ]
                            ],
                        ]
                    ],
                    [
                        'name' => 'iced-tea',
                        'price' => 2.5,
                        'imgUrl' => 'imgs/demo/vegetarian/cat4_prod4.webp',
                        'thumbnailUrl' => 'imgs/demo/vegetarian/cat4_prod4_thumbnail.webp',
                        'name_en' => 'Iced Tea',
                        'name_ar' => 'شاي مثلج',
                        'name_fr' => 'Thé glacé',
                        'name_it' => 'Tè freddo',
                        'name_de' => 'Eistee',
                        'name_es' => 'Te helado',
                        'name_ua' => 'Холодний чай',
                        'options' => [
                        ]
                    ],
                ]
            ],
        ];
        demo::website($vegetarian,$categories);
    }

}
