hash = function() {
    let result = '';
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const charactersLength = characters.length;
    let counter = 0;
    while (counter < 20) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
      counter += 1;
    }
    return result;
}

window.section_layouts = [
    {
        layout:'0',
        preview_class:'section_layout_0',
        preview_html:`<div layout="0" class="section_layout_0 section_layout_elem"><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'2',
        preview_class:'section_layout_2',
        preview_html:`<div layout="2" class="section_layout_2 section_layout_elem"><div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'14',
        preview_class:'section_layout_14',
        preview_html:`<div layout="14" class="section_layout_14 section_layout_elem"><div><div></div><div></div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem3""elem2 elem3"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'15',
        preview_class:'section_layout_15',
        preview_html:`<div layout="15" class="section_layout_15 section_layout_elem"><div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2""elem1 elem3"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'1',
        preview_class:'section_layout_1',
        preview_html:`<div layout="1" class="section_layout_1 section_layout_elem"><div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1" "elem2"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'3',
        preview_class:'section_layout_3',
        preview_html:`<div layout="3" class="section_layout_3 section_layout_elem"><div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem1" "elem2 elem3"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                }
            }
        },
    },
    {
        layout:'4',
        preview_class:'section_layout_4',
        preview_html:`<div layout="4" class="section_layout_4 section_layout_elem"><div><div></div><div></div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2" "elem3 elem3"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                }
            }
        },
    },
    {
        layout:'5',
        preview_class:'section_layout_5',
        preview_html:`<div layout="5" class="section_layout_5 section_layout_elem"><div><div></div><div></div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2" "elem3 elem4"',
                'grid-template-columns':'repeat(2, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                }
            }
        },
    },
    {
        layout:'6',
        preview_class:'section_layout_6',
        preview_html:`<div layout="6" class="section_layout_6 section_layout_elem"><div></div><div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2 elem3"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'7',
        preview_class:'section_layout_7',
        preview_html:`<div layout="7" class="section_layout_7 section_layout_elem"><div><div></div><div></div></div><div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem3 elem4""elem2 elem3 elem4"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'8',
        preview_class:'section_layout_8',
        preview_html:`<div layout="8" class="section_layout_8 section_layout_elem"><div></div><div><div></div><div></div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2 elem4""elem1 elem3 elem4"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'9',
        preview_class:'section_layout_9',
        preview_html:`<div layout="9" class="section_layout_9 section_layout_elem"><div></div><div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2 elem3""elem1 elem2 elem4"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'10',
        preview_class:'section_layout_10',
        preview_html:`<div layout="10" class="section_layout_10 section_layout_elem"><div><div></div><div></div></div><div><div></div><div></div></div><div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem3 elem5""elem2 elem4 elem5"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4""elem5"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem5',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'11',
        preview_class:'section_layout_11',
        preview_html:`<div layout="11" class="section_layout_11 section_layout_elem"><div><div></div><div></div></div><div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem3 elem4""elem2 elem3 elem5"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4""elem5"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem5',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'12',
        preview_class:'section_layout_12',
        preview_html:`<div layout="12" class="section_layout_12 section_layout_elem"><div></div><div><div></div><div></div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem2 elem4""elem1 elem3 elem5"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4""elem5"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem5',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
    {
        layout:'13',
        preview_class:'section_layout_13',
        preview_html:`<div layout="13" class="section_layout_13 section_layout_elem"><div><div></div><div></div></div><div><div></div><div></div></div><div><div></div><div></div></div></div>`,
        section_container:{
            tag:'div',
            type:'section_container',
            class:'section_container',
            style_class:`section_container_${hash()}`,
            style:{
                'min-height':'500px',
                display:'grid',
                'grid-template-areas':'"elem1 elem3 elem5""elem2 elem4 elem6"',
                'grid-template-columns':'repeat(3, 1fr)',
            },
            style_mobile:{
                'grid-template-areas':'"elem1""elem2""elem3""elem4""elem5""elem6"',
                'grid-template-columns':'repeat(1, 1fr)',
            },
            children:{
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem1',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem2',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem3',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem4',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem5',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
                [`element_container_${hash()}`]:{
                    tag:'div',
                    type:'element_container',
                    color_theme:'transparent',
                    class:'element_container',
                    style_class : `element_container_${hash()}`,
                    style:{
                        'grid-area' : 'elem6',
                        'display' : 'flex',
                        'flex-direction' : 'row',
                        'flex-wrap' : 'nowrap',
                        'align-items' : 'center',
                        'justify-content' : 'center',
                    },
                    style_mobile:{},
                },
            }
        },
    },
]
