draw_editor_popup_section_spacing = function(){
    if(!accessibility_check(window.selected,'section_spacing')){return;}
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            draw_editors_container({
                is_responsive:true,
                editors:[
                    $('<div/>',{class:`editor_popup_col editor_popup_brdrT_none`}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.margin_top}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.section_wrapper`,
                            variable_key:'css',
                            key:'margin-top',
                            units:['px','em','%'],
                        }),
                    ),
                    $('<div/>',{class:`editor_popup_col`}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.margin_bottom}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.section_wrapper`,
                            variable_key:'css',
                            key:'margin-bottom',
                            units:['px','em','%'],
                        }),
                    ),
                    $('<div/>',{class:`editor_popup_col`}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.padding_top}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.section_wrapper`,
                            variable_key:'css',
                            key:'padding-top',
                            units:['px','em','%'],
                        }),
                    ),
                    $('<div/>',{class:`editor_popup_col`}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.padding_bottom}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.section_wrapper`,
                            variable_key:'css',
                            key:'padding-bottom',
                            units:['px','em','%'],
                        }),
                    ),
                    $('<div/>',{class:`editor_popup_col`}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.blocks_gap}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.section_wrapper`,
                            variable_key:'css',
                            key:'grid-gap',
                            units:['px','em','%'],
                        }),
                    ),
                    
                ]
            })
        )
        setTimeout(()=>{
            $('.editor_popup_title2').text(texts.spacing)
            $(`.editor_popup_body_shortcut.editor_section_spacing`).addClass('editor_popup_body_shortcut_selected')
        });

    });
}
$('body').on('click','.editor_section_spacing',function(e){
    draw_editor_popup_section_spacing();
})