<script>
    let account = {!! $account !!};
    let website = {!! $website !!};
    let settings = {!! $settings !!};
    let foodMenuData = {!! $foodMenuData !!};
    let texts = {!! $texts !!};
    let autoHelp_text = {!! $autoHelp_text !!}
    texts = {
        cpanel:{!! json_encode(trans('cpanel/cpanel')) !!},
        support:{!! json_encode(trans('cpanel/support/texts')) !!},
        settings:{!! json_encode(trans('cpanel/settings/texts')) !!},
        users:{!! json_encode(trans('cpanel/users/texts')) !!},
        staff:{!! json_encode(trans('cpanel/staff/texts')) !!},
        products:{!! json_encode(trans('cpanel/products/texts')) !!},
        design:{!! json_encode(trans('cpanel/design/texts')) !!},

        statistics:{

            "noAvailableData":"{!! trans('cpanel/dashboard/statistics.noAvailableData') !!}",
            "smallScreen":"{!! trans('cpanel/dashboard/statistics.smallScreen') !!}",

            "deliveredOrders":"{!! trans('cpanel/dashboard/statistics.deliveredOrders') !!}",
            "deliveredOrder":"{!! trans('cpanel/dashboard/statistics.deliveredOrder') !!}",
            "minute":"{!! trans('cpanel/dashboard/statistics.minute') !!}",
            "minutes":"{!! trans('cpanel/dashboard/statistics.minutes') !!}",
            "hour":"{!! trans('cpanel/dashboard/statistics.hour') !!}",
            "hours":"{!! trans('cpanel/dashboard/statistics.hours') !!}",
            "in":"{!! trans('cpanel/dashboard/statistics.in') !!}",
            "and":"{!! trans('cpanel/dashboard/statistics.and') !!}",
            "avg":"{!! trans('cpanel/dashboard/statistics.avg') !!}",
            "perOrder":"{!! trans('cpanel/dashboard/statistics.perOrder') !!}",
            ///////////////////
            "periodSelectedHasNoArchive":"{!! trans('cpanel/dashboard/statistics.periodSelectedHasNoArchive') !!}",
            "periodSelectedHasNoArchive2":"{!! trans('cpanel/dashboard/statistics.periodSelectedHasNoArchive2') !!}",
            "dataloaded":"{!! trans('cpanel/dashboard/statistics.dataloaded') !!}",

            "completeOrders":"{!! trans('cpanel/dashboard/statistics.completeOrders') !!}",
            "successfulIncom":"{!! trans('cpanel/dashboard/statistics.successfulIncom') !!}",
            "successfulOrders":"{!! trans('cpanel/dashboard/statistics.successfulOrders') !!}",
            "canceledOrders":"{!! trans('cpanel/dashboard/statistics.canceledOrders') !!}",


            "totalIncome":"{!! trans('cpanel/dashboard/statistics.totalIncome') !!}",
            "itemsTotal":"{!! trans('cpanel/dashboard/statistics.itemsTotal') !!}",
            "deliveryCost":"{!! trans('cpanel/dashboard/statistics.deliveryCost') !!}",
            "tax":"{!! trans('cpanel/dashboard/statistics.tax') !!}",
            "service":"{!! trans('cpanel/dashboard/statistics.service') !!}",
            "total":"{!! trans('cpanel/dashboard/statistics.total') !!}",
            "income":"{!! trans('cpanel/dashboard/statistics.income') !!}",
            "orderedByUsers":"{!! trans('cpanel/dashboard/statistics.orderedByUsers') !!}",
            "orderedByGuests":"{!! trans('cpanel/dashboard/statistics.orderedByGuests') !!}",

            "delivery":"{!! trans('cpanel/dashboard/statistics.delivery') !!}",
            "pickup":"{!! trans('cpanel/dashboard/statistics.pickup') !!}",
            "dineIn":"{!! trans('cpanel/dashboard/statistics.dineIn') !!}",

            "deliveryOrders":"{!! trans('cpanel/dashboard/statistics.deliveryOrders') !!}",
            "pickupOrders":"{!! trans('cpanel/dashboard/statistics.pickupOrders') !!}",
            "dineInOrders":"{!! trans('cpanel/dashboard/statistics.dineInOrders') !!}",

            "successfulOrdersGraph":"{!! trans('cpanel/dashboard/statistics.successfulOrdersGraph') !!}",
            "canceledOrdersGraph":"{!! trans('cpanel/dashboard/statistics.canceledOrdersGraph') !!}",
            "deliveriedOrdersGraph":"{!! trans('cpanel/dashboard/statistics.deliveriedOrdersGraph') !!}",
            "pickedupOrdersGraph":"{!! trans('cpanel/dashboard/statistics.pickedupOrdersGraph') !!}",
            "dineinOrdersGraph":"{!! trans('cpanel/dashboard/statistics.dineinOrdersGraph') !!}",

            "successfulOrdersIncomeGraph":"{!! trans('cpanel/dashboard/statistics.successfulOrdersIncomeGraph') !!}",
            "canceledOrdersIncomeGraph":"{!! trans('cpanel/dashboard/statistics.canceledOrdersIncomeGraph') !!}",
            "deliveriedOrdersIncomeGraph":"{!! trans('cpanel/dashboard/statistics.deliveriedOrdersIncomeGraph') !!}",
            "pickedupOrdersIncomeGraph":"{!! trans('cpanel/dashboard/statistics.pickedupOrdersIncomeGraph') !!}",
            "dineinOrdersIncomeGraph":"{!! trans('cpanel/dashboard/statistics.dineinOrdersIncomeGraph') !!}",

            "successfulOrdersIncomeGraph_users":"{!! trans('cpanel/dashboard/statistics.successfulOrdersIncomeGraph_users') !!}",
            "canceledOrdersIncomeGraph_users":"{!! trans('cpanel/dashboard/statistics.canceledOrdersIncomeGraph_users') !!}",
            "deliveriedOrdersIncomeGraph_users":"{!! trans('cpanel/dashboard/statistics.deliveriedOrdersIncomeGraph_users') !!}",
            "pickedupOrdersIncomeGraph_users":"{!! trans('cpanel/dashboard/statistics.pickedupOrdersIncomeGraph_users') !!}",
            "dineinOrdersIncomeGraph_users":"{!! trans('cpanel/dashboard/statistics.dineinOrdersIncomeGraph_users') !!}",

            "topOrderedProduct":"{!! trans('cpanel/dashboard/statistics.topOrderedProduct') !!}",
            "topProfitableProduct":"{!! trans('cpanel/dashboard/statistics.topProfitableProduct') !!}",
            "topProfitableProducts":"{!! trans('cpanel/dashboard/statistics.topProfitableProducts') !!}",
            "topProfitableUser":"{!! trans('cpanel/dashboard/statistics.topProfitableUser') !!}",
            "topProfitableUsers":"{!! trans('cpanel/dashboard/statistics.topProfitableUsers') !!}",
            "topProfitableUser":"{!! trans('cpanel/dashboard/statistics.topProfitableUser') !!}",

            "times":"{!! trans('cpanel/dashboard/statistics.times') !!}",
            "time":"{!! trans('cpanel/dashboard/statistics.time') !!}",
            "ordered":"{!! trans('cpanel/dashboard/statistics.ordered') !!}",
            "profites":"{!! trans('cpanel/dashboard/statistics.profites') !!}",

            "reviews":"{!! trans('cpanel/dashboard/statistics.reviews') !!}",


            "orders":"{!! trans('cpanel/dashboard/statistics.orders') !!}",
            "dataloaded":"{!! trans('cpanel/dashboard/statistics.dataloaded') !!}",


        },
        servicesSettings:{
            "workingHoursCopied" : "{!! trans('cpanel/settings/dineIn.workingHoursCopied') !!}",
            "scheduledDiscountCopied" : "{!! trans('cpanel/settings/dineIn.scheduledDiscountCopied') !!}",
            "dayChangedNotSaved" : "{!! trans('cpanel/settings/dineIn.dayChangedNotSaved') !!}",

        },
        // imgs:{
        //     "imgNotFound" : "{!! trans('cpanel/design/imgs.imgNotFound') !!}",
        //     "imgTooBig" : "{!! trans('cpanel/design/imgs.imgTooBig') !!}",
        //     "imgWrongType" : "{!! trans('cpanel/design/imgs.imgWrongType') !!}",
        //     "noUploads" :"{!! trans('cpanel/design/imgs.noUploads') !!}",
        //     "copyed":"{!! trans('cpanel/design/imgs.copyed') !!}",
        //     "mb":"{!! trans('cpanel/design/imgs.mb') !!}",
        //     "noimg":"{!! trans('cpanel/design/imgs.noimg') !!}",
        //     "imgType":"{!! trans('cpanel/design/imgs.imgType') !!}",
        //     "png":"{!! trans('cpanel/design/imgs.png') !!}",
        //     "jpg":"{!! trans('cpanel/design/imgs.jpg') !!}",
        //     "jpeg":"{!! trans('cpanel/design/imgs.jpeg') !!}",
        //     "jfif":"{!! trans('cpanel/design/imgs.jfif') !!}",
        //     "pjpeg":"{!! trans('cpanel/design/imgs.pjpeg') !!}",
        //     "pjp":"{!! trans('cpanel/design/imgs.pjp') !!}",
        //     "gif":"{!! trans('cpanel/design/imgs.gif') !!}",
        //     "bmp":"{!! trans('cpanel/design/imgs.bmp') !!}",
        //     "webp":"{!! trans('cpanel/design/imgs.webp') !!}",
        //     "imgSize":"{!! trans('cpanel/design/imgs.imgSize') !!}",
        //     "dimensions":"{!! trans('cpanel/design/imgs.dimensions') !!}",
        //     "imgName":"{!! trans('cpanel/design/imgs.imgName') !!}",
        //     "uploadedAt":"{!! trans('cpanel/design/imgs.uploadedAt') !!}",
        //     "imgDeleteConfirm":"{!! trans('cpanel/design/imgs.imgDeleteConfirm') !!}",
        //     "deleteFailImgInUse":"{!! trans('cpanel/design/imgs.deleteFailImgInUse') !!}",
        //     "deleteFailLogo":"{!! trans('cpanel/design/imgs.deleteFailLogo') !!}",
        //     "deleteFailIcon":"{!! trans('cpanel/design/imgs.deleteFailIcon') !!}",
        //     "deleteFailIntro":"{!! trans('cpanel/design/imgs.deleteFailIntro') !!}",
        //     "deleteFailInfo":"{!! trans('cpanel/design/imgs.deleteFailInfo') !!}",
        //     "deleteFailOurStory":"{!! trans('cpanel/design/imgs.deleteFailOurStory') !!}",
        //     "deleteFailGallery":"{!! trans('cpanel/design/imgs.deleteFailGallery') !!}",
        //     "deleteFailslideShow":"{!! trans('cpanel/design/imgs.deleteFailslideShow') !!}",
        //     "deleteFailProduct":"{!! trans('cpanel/design/imgs.deleteFailProduct') !!}",
        //     "deleteFailCategory":"{!! trans('cpanel/design/imgs.deleteFailCategory') !!}",
        // },

        // products:{
        //     "manageOptions":"{!! trans('cpanel/products/products.manageOptions') !!}",
        //     "unsortProduct":"{!! trans('cpanel/products/products.unsortProduct') !!}",
        //     "productAvailability":"{{ trans('cpanel/products/products.productAvailability') }}",
        //     "createNewProduct":"{!! trans('cpanel/products/products.createNewProduct') !!}",
        //     "productNameRequired":"{!! trans('cpanel/products/products.productNameRequired') !!}",
        //     "productNameRegex":"{!! trans('cpanel/products/products.productNameRegex') !!}",
        //     "productNameUnique":"{!! trans('cpanel/products/products.productNameUnique') !!}",
        //     "createFailPlanLimit":"{!! trans('cpanel/products/products.createFailPlanLimit') !!}",
        //     "selectProductImg":"{!! trans('cpanel/products/products.selectProductImg') !!}",
        //     "planProductOptionsLimitError":"{!! trans('cpanel/products/products.planProductOptionsLimitError') !!}",
        //     "setAsdefaultSelection":"{!! trans('cpanel/products/products.setAsdefaultSelection') !!}",
        //     "optionNameUnique":"{!! trans('cpanel/products/products.optionNameUnique') !!}",
        //     "optionNameRegex":"{!! trans('cpanel/products/products.optionNameRegex') !!}",
        //     "optionNameRequired":"{!! trans('cpanel/products/products.optionNameRequired') !!}",
        //     "selectionNameUnique":"{!! trans('cpanel/products/products.selectionNameUnique') !!}",
        //     "selectionNameRegex":"{!! trans('cpanel/products/products.selectionNameRegex') !!}",
        //     "selectionNameRequired":"{!! trans('cpanel/products/products.selectionNameRequired') !!}",
        //     "allProducts":"{!! trans('cpanel/products/products.allProducts') !!}",
        //     "noProductsInCategory":"{!! trans('cpanel/products/products.noProductsInCategory') !!}",
        //     "uncategorizedProduct":"{!! trans('cpanel/products/products.uncategorizedProduct') !!}",
        //     "productDeleteConfirm":"{!! trans('cpanel/products/products.productDeleteConfirm') !!}",
        //     "optionDeleteConfirm1":"{!! trans('cpanel/products/products.optionDeleteConfirm1') !!}",
        //     "optionDeleteConfirm2":"{!! trans('cpanel/products/products.optionDeleteConfirm2') !!}",
        //     "selectionDeleteConfirm1":"{!! trans('cpanel/products/products.selectionDeleteConfirm1') !!}",
        //     "selectionDeleteConfirm2":"{!! trans('cpanel/products/products.selectionDeleteConfirm2') !!}",
        //     "selectionDeleteConfirm3":"{!! trans('cpanel/products/products.selectionDeleteConfirm3') !!}",
        //     "productReview":"{!! trans('cpanel/products/products.productReview') !!}",
        //     "noProducts":"{!! trans('cpanel/products/products.noProducts') !!}",
        //     "noUnsortedProduct":"{!! trans('cpanel/products/products.noUnsortedProduct') !!}",
        //     "time":"{!! trans('cpanel/products/products.time') !!}",
        //     "times":"{!! trans('cpanel/products/products.times') !!}",
        //     "noReviews":"{!! trans('cpanel/products/productReviews.noReviews') !!}",
        //     "confirmDeleteReview":"{!! trans('cpanel/products/productReviews.confirmDeleteReview') !!}",
        //     "reviews":"{!! trans('cpanel/products/productReviews.reviews') !!}",
        //     "review":"{!! trans('cpanel/products/productReviews.review') !!}",
        //     "lastUpdate":"{!! trans('cpanel/products/productReviews.lastUpdate') !!}",
        //     "moreFilters":"{!! trans('cpanel/products/productReviews.moreFilters') !!}",
        //     "lessFilters":"{!! trans('cpanel/products/productReviews.lessFilters') !!}",
        //     "reviewNotFound":"{!! trans('cpanel/products/productReviews.reviewNotFound') !!}",
        // },
        // categories:{
        //     "categoryNameRequired":"{!! trans('cpanel/categories/createNewCategory.categoryNameRequired') !!}",
        //     "categoryNameRegex":"{!! trans('cpanel/categories/createNewCategory.categoryNameRegex') !!}",
        //     "categoryNameUnique":"{!! trans('cpanel/categories/createNewCategory.categoryNameUnique') !!}",
        //     "categoryNameNotAllowed":"{!! trans('cpanel/categories/createNewCategory.categoryNameNotAllowed') !!}",
        //     "createFailPlanLimit":"{!! trans('cpanel/categories/createNewCategory.createFailPlanLimit') !!}",
        //     "selectCategoryImg":"{!! trans('cpanel/categories/createNewCategory.selectCategoryImg') !!}",
        //     "noCategoriesCreated":"{!! trans('cpanel/categories/categoriesList.noCategoriesCreated') !!}",
        //     "categoryDeleteConfirm":"{!! trans('cpanel/categories/categoriesList.categoryDeleteConfirm') !!}",
        //     "createNewCategory":"{!! trans('cpanel/categories/categoriesList.createNewCategory') !!}",
        // },
        orders:{
            "viewOrder":"{!! trans('cpanel/orders/orders.viewOrder') !!}",
            "printReceipt":"{!! trans('cpanel/orders/orders.printReceipt') !!}",
            "modifiedBy":"{!! trans('cpanel/orders/orders.modifiedBy') !!}",
            "itemsLastModified":"{!! trans('cpanel/orders/orders.itemsLastModified') !!}",
            "addedBy":"{!! trans('cpanel/orders/orders.addedBy') !!}",
            "addByScheduledDiscounts":"{!! trans('cpanel/orders/orders.addByScheduledDiscounts') !!}",
            "addByPromocode":"{!! trans('cpanel/orders/orders.addByPromocode') !!}",
            "status":"{!! trans('cpanel/orders/orders.status') !!}",
            "items":"{!! trans('cpanel/orders/orders.items') !!}",
            "customer":"{!! trans('cpanel/orders/orders.customer') !!}",
            "price":"{!! trans('cpanel/orders/orders.price') !!}",
            "order":"{!! trans('cpanel/orders/orders.order') !!}",
            "noIncompleteOrders":"{!! trans('cpanel/orders/orders.noIncompleteOrders') !!}",
            "noPendingOrders":"{!! trans('cpanel/orders/orders.noPendingOrders') !!}",
            "noAcceptedOrdes":"{!! trans('cpanel/orders/orders.noAcceptedOrdes') !!}",
            "noOutForDeliveryOrders":"{!! trans('cpanel/orders/orders.noOutForDeliveryOrders') !!}",
            "noReadyForPickupOrders":"{!! trans('cpanel/orders/orders.noReadyForPickupOrders') !!}",
            "noDiningInOrders":"{!! trans('cpanel/orders/orders.noDiningInOrders') !!}",

            "pickup":"{!! trans('cpanel/orders/orders.pickup') !!}",
            "delivery":"{!! trans('cpanel/orders/orders.delivery') !!}",
            "dineIn":"{!! trans('cpanel/orders/orders.dineIn') !!}",

            "pending":"{!! trans('cpanel/orders/orders.pending') !!}",
            "accepted":"{!! trans('cpanel/orders/orders.accepted') !!}",
            "withDelivery":"{!! trans('cpanel/orders/orders.withDelivery') !!}",
            "outForDeliveryWith":"{!! trans('cpanel/orders/orders.outForDeliveryWith') !!}",
            "readyForPickup":"{!! trans('cpanel/orders/orders.readyForPickup') !!}",
            "diningIn":"{!! trans('cpanel/orders/orders.diningIn') !!}",
            "delivered":"{!! trans('cpanel/orders/orders.delivered') !!}",
            "pickedUp":"{!! trans('cpanel/orders/orders.pickedUp') !!}",
            "dinedIn":"{!! trans('cpanel/orders/orders.dinedIn') !!}",
            "canceled":"{!! trans('cpanel/orders/orders.canceled') !!}",

            "orderPlaced":"{!! trans('cpanel/orders/orders.orderPlaced') !!}",
            "orderDineIn":"{!! trans('cpanel/orders/orders.orderDineIn') !!}",
            "orderDiningIn":"{!! trans('cpanel/orders/orders.orderDiningIn') !!}",
            "orderAccepted":"{!! trans('cpanel/orders/orders.orderAccepted') !!}",
            "orderDelivered":"{!! trans('cpanel/orders/orders.orderDelivered') !!}",
            "orderPickedup":"{!! trans('cpanel/orders/orders.orderPickedup') !!}",
            "orderWithDelivery":"{!! trans('cpanel/orders/orders.orderWithDelivery') !!}",
            "orderreadyForPickup":"{!! trans('cpanel/orders/orders.orderreadyForPickup') !!}",
            "orderCanceled":"{!! trans('cpanel/orders/orders.orderCanceled') !!}",

            "markAsDiningin":"{!! trans('cpanel/orders/orders.markAsDiningin') !!}",
            "markAsDinein":"{!! trans('cpanel/orders/orders.markAsDinein') !!}",
            "acceptOrder":"{!! trans('cpanel/orders/orders.acceptOrder') !!}",
            "markAsreadyForPickup":"{!! trans('cpanel/orders/orders.markAsreadyForPickup') !!}",
            "markAsPickedUp":"{!! trans('cpanel/orders/orders.markAsPickedUp') !!}",
            "markAsWithDelivery":"{!! trans('cpanel/orders/orders.markAsWithDelivery') !!}",
            "markAsDelivered":"{!! trans('cpanel/orders/orders.markAsDelivered') !!}",
            "giveToDelivery":"{!! trans('cpanel/orders/orders.giveToDelivery') !!}",
            "cancelOrder":"{!! trans('cpanel/orders/orders.cancelOrder') !!}",

            "qty":"{!! trans('cpanel/orders/orders.qty') !!}",
            "addItemUnavailable":"{!! trans('cpanel/orders/orders.addItemUnavailable') !!}",
            "removeItem":"{!! trans('cpanel/orders/orders.removeItem') !!}",
            "specialRequest":"{!! trans('cpanel/orders/orders.specialRequest') !!}",
            "addSpecialRequest":"{!! trans('cpanel/orders/orders.addSpecialRequest') !!}",

            "discount":"{!! trans('cpanel/orders/orders.discount') !!}",
            "scheduledDiscount":"{!! trans('cpanel/orders/orders.scheduledDiscount') !!}",
            "scheduledDiscountAlert1":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert1') !!}",
            "scheduledDiscountAlert2":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert2') !!}",
            "scheduledDiscountAlert3":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert3') !!}",
            "scheduledDiscountAlert_dineIn":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert_dineIn') !!}",
            "scheduledDiscountAlert_delivery":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert_delivery') !!}",
            "scheduledDiscountAlert_pickup":"{!! trans('cpanel/orders/orders.scheduledDiscountAlert_pickup') !!}",

            "placeOrderErrorNoItems":"{!! trans('cpanel/orders/orders.placeOrderErrorNoItems') !!}",
            "placeOrderErrorSelectUser":"{!! trans('cpanel/orders/orders.placeOrderErrorSelectUser') !!}",
            "placeOrderErrorPhoneNumberRequired":"{!! trans('cpanel/orders/orders.placeOrderErrorPhoneNumberRequired') !!}",
            "placeOrderErrorAddressRequired":"{!! trans('cpanel/orders/orders.placeOrderErrorAddressRequired') !!}",

            "addLocation":"{!! trans('cpanel/orders/orders.addLocation') !!}",
            "removeLocation":"{!! trans('cpanel/orders/orders.removeLocation') !!}",

            "moreFilters":"{!! trans('cpanel/orders/orders.moreFilters') !!}",
            "lessFilters":"{!! trans('cpanel/orders/orders.lessFilters') !!}",

            "orderInfo":"{!! trans('cpanel/orders/orders.orderInfo') !!}",
            "orderNumber":"{!! trans('cpanel/orders/orders.orderNumber') !!}",
            "type":"{!! trans('cpanel/orders/orders.type') !!}",
            "paymentMethod":"{!! trans('cpanel/orders/orders.paymentMethod') !!}",
            "collectReviewsSeen":"{!! trans('cpanel/orders/orders.collectReviewsSeen') !!}",
            "orderNotice":"{!! trans('cpanel/orders/orders.orderNotice') !!}",
            "noticePlaceholder":"{!! trans('cpanel/orders/orders.noticePlaceholder') !!}",
            "phoneNumber":"{!! trans('cpanel/orders/orders.phoneNumber') !!}",
            "address":"{!! trans('cpanel/orders/orders.address') !!}",


            "seen":"{!! trans('cpanel/orders/orders.seen') !!}",
            "unSeen":"{!! trans('cpanel/orders/orders.unSeen') !!}",

            "cashOnDelivery":"{!! trans('cpanel/orders/orders.cashOnDelivery') !!}",
            "cardOnDelivery":"{!! trans('cpanel/orders/orders.cardOnDelivery') !!}",
            "cashOnPickup":"{!! trans('cpanel/orders/orders.cashOnPickup') !!}",
            "cardOnPickup":"{!! trans('cpanel/orders/orders.cardOnPickup') !!}",

            "orderLifecycle":"{!! trans('cpanel/orders/orders.orderLifecycle') !!}",
            "by":"{!! trans('cpanel/orders/orders.by') !!}",
            "waitingAction":"{!! trans('cpanel/orders/orders.waitingAction') !!}",
            "orderActions":"{!! trans('cpanel/orders/orders.orderActions') !!}",
            "takeAction":"{!! trans('cpanel/orders/orders.takeAction') !!}",
            "giveTo":"{!! trans('cpanel/orders/orders.giveTo') !!}",
            "cantRemoveLastItem":"{!! trans('cpanel/orders/orders.cantRemoveLastItem') !!}",

            "qty2":"{!! trans('cpanel/orders/orders.qty2') !!}",
            "item":"{!! trans('cpanel/orders/orders.item') !!}",
            "subTotal":"{!! trans('cpanel/orders/orders.subTotal') !!}",
            "tax":"{!! trans('cpanel/orders/orders.tax') !!}",
            "service":"{!! trans('cpanel/orders/orders.service') !!}",
            "deliveryCost":"{!! trans('cpanel/orders/orders.deliveryCost') !!}",
            "total":"{!! trans('cpanel/orders/orders.total') !!}",

            "chatOrderWorngUser":"{!! trans('cpanel/orders/orders.chatOrderWorngUser') !!}",
            "wrongOrderNumber":"{!! trans('cpanel/orders/orders.wrongOrderNumber') !!}",
            "changeTypeToDeliveryWarning":"{!! trans('cpanel/orders/orders.changeTypeToDeliveryWarning') !!}",


        },
        security:{
            "deleteConfirm1" : "{!! trans('cpanel/security/subAccounts.deleteConfirm1') !!}",
            "deleteConfirm2" : "{!! trans('cpanel/security/subAccounts.deleteConfirm2') !!}",
            "subAccountBlocked" : "{!! trans('cpanel/security/subAccounts.subAccountBlocked') !!}",
            "unblockSubAccount" : "{!! trans('cpanel/security/subAccounts.unblockSubAccount') !!}",
            "forceLogout":"{!! trans('cpanel/security/subAccounts.forceLogout') !!}",
            "resendCode":"{!! trans('cpanel/security/email.resend') !!}",
            "resendCode2":"{!! trans('cpanel/security/email.resend2') !!}",
            "phoneRequired":"{!! trans('cpanel/security/phone.phoneRequired') !!}",
        },
        restaurantExpenses:{
            "expenseNameRequired":"{{ trans('cpanel/dashboard/restaurantExpenses.expenseNameRequired') }}",
            "expenseAmountRequired":"{{ trans('cpanel/dashboard/restaurantExpenses.expenseAmountRequired') }}",
            "total":"{{ trans('cpanel/dashboard/restaurantExpenses.total') }}",
        },
        financialReports:{
            "deleteConfirmMsg":"{{ trans('cpanel/dashboard/financialReports.deleteConfirmMsg') }}",
            "financialReport":"{{ trans('cpanel/dashboard/financialReports.financialReport') }}",
            "noReports":"{{ trans('cpanel/dashboard/financialReports.noReports') }}",
        },
        activityLogs:{
            "dayNotSelected":"{!! trans('cpanel/dashboard/activityLog.dayNotSelected') !!}",
            "activity_component":"{!! trans('cpanel/dashboard/activityLog.activity_component') !!}",
            "activity_component2":"{!! trans('cpanel/dashboard/activityLog.activity_component2') !!}",
            "activity_user":"{!! trans('cpanel/dashboard/activityLog.activity_user') !!}",
            "activity_user2":"{!! trans('cpanel/dashboard/activityLog.activity_user2') !!}",
            "activity_guest":"{!! trans('cpanel/dashboard/activityLog.activity_guest') !!}",
            "activity_guest2":"{!! trans('cpanel/dashboard/activityLog.activity_guest2') !!}",
            "from":"{!! trans('cpanel/dashboard/activityLog.from') !!}",
            "to":"{!! trans('cpanel/dashboard/activityLog.to') !!}",
            "by":"{!! trans('cpanel/dashboard/activityLog.by') !!}",
            "moreSimilarActivity":"{!! trans('cpanel/dashboard/activityLog.moreSimilarActivity') !!}",
            "moreSimilarActivitys":"{!! trans('cpanel/dashboard/activityLog.moreSimilarActivitys') !!}",
            "deleteActivityLogConfirmTxt":"{!! trans('cpanel/dashboard/activityLog.deleteActivityLogConfirmTxt') !!}",
            "activity0_1":"{!! trans('cpanel/dashboard/activityLog.activity0_1') !!}",
            "activity1_1":"{!! trans('cpanel/dashboard/activityLog.activity1_1') !!}",
            "activity2_1":"{!! trans('cpanel/dashboard/activityLog.activity2_1') !!}",
            "activity3_1":"{!! trans('cpanel/dashboard/activityLog.activity3_1') !!}",
            "activity4_1":"{!! trans('cpanel/dashboard/activityLog.activity4_1') !!}",
            "activity6_1":"{!! trans('cpanel/dashboard/activityLog.activity6_1') !!}",
            "activity6_2":"{!! trans('cpanel/dashboard/activityLog.activity6_2') !!}",
            "activity7_1":"{!! trans('cpanel/dashboard/activityLog.activity7_1') !!}",
            "activity7_2":"{!! trans('cpanel/dashboard/activityLog.activity7_2') !!}",
            "activity7_3":"{!! trans('cpanel/dashboard/activityLog.activity7_3') !!}",
            "activity8_1":"{!! trans('cpanel/dashboard/activityLog.activity8_1') !!}",
            "activity8_2":"{!! trans('cpanel/dashboard/activityLog.activity8_2') !!}",
            "activity9_1":"{!! trans('cpanel/dashboard/activityLog.activity9_1') !!}",
            "activity10_1":"{!! trans('cpanel/dashboard/activityLog.activity10_1') !!}",
            "activity11_1":"{!! trans('cpanel/dashboard/activityLog.activity11_1') !!}",
            "activity12_1":"{!! trans('cpanel/dashboard/activityLog.activity12_1') !!}",
            "activity13_1":"{!! trans('cpanel/dashboard/activityLog.activity13_1') !!}",
            "activity14_1":"{!! trans('cpanel/dashboard/activityLog.activity14_1') !!}",

            "activity15_1":"{!! trans('cpanel/dashboard/activityLog.activity15_1') !!}",
            "activity15_2":"{!! trans('cpanel/dashboard/activityLog.activity15_2') !!}",

            "activity1501_1":"{!! trans('cpanel/dashboard/activityLog.activity1501_1') !!}",
            "activity1501_2":"{!! trans('cpanel/dashboard/activityLog.activity1501_2') !!}",
            "activity1501_3":"{!! trans('cpanel/dashboard/activityLog.activity1501_3') !!}",

            "activity1502_1":"{!! trans('cpanel/dashboard/activityLog.activity1502_1') !!}",
            "activity1502_2":"{!! trans('cpanel/dashboard/activityLog.activity1502_2') !!}",
            "activity1502_3":"{!! trans('cpanel/dashboard/activityLog.activity1502_3') !!}",

            "activity1503_1":"{!! trans('cpanel/dashboard/activityLog.activity1503_1') !!}",
            "activity1503_2":"{!! trans('cpanel/dashboard/activityLog.activity1503_2') !!}",
            "activity1503_3":"{!! trans('cpanel/dashboard/activityLog.activity1503_3') !!}",
            "activity1503_4":"{!! trans('cpanel/dashboard/activityLog.activity1503_4') !!}",

            "activity1504_1":"{!! trans('cpanel/dashboard/activityLog.activity1504_1') !!}",
            "activity1504_2":"{!! trans('cpanel/dashboard/activityLog.activity1504_2') !!}",
            "activity1504_3":"{!! trans('cpanel/dashboard/activityLog.activity1504_3') !!}",
            "activity1504_4":"{!! trans('cpanel/dashboard/activityLog.activity1504_4') !!}",

            "activity1505_1":"{!! trans('cpanel/dashboard/activityLog.activity1505_1') !!}",
            "activity1505_2":"{!! trans('cpanel/dashboard/activityLog.activity1505_2') !!}",
            "activity1505_3":"{!! trans('cpanel/dashboard/activityLog.activity1505_3') !!}",
            "activity1505_4":"{!! trans('cpanel/dashboard/activityLog.activity1505_4') !!}",

            "activity1506_1":"{!! trans('cpanel/dashboard/activityLog.activity1506_1') !!}",
            "activity1506_2":"{!! trans('cpanel/dashboard/activityLog.activity1506_2') !!}",
            "activity1506_3":"{!! trans('cpanel/dashboard/activityLog.activity1506_3') !!}",
            "activity1506_4":"{!! trans('cpanel/dashboard/activityLog.activity1506_4') !!}",

            "activity16_1":"{!! trans('cpanel/dashboard/activityLog.activity16_1') !!}",
            "activity16_2":"{!! trans('cpanel/dashboard/activityLog.activity16_2') !!}",
            "activity17_1":"{!! trans('cpanel/dashboard/activityLog.activity17_1') !!}",
            "activity17_2":"{!! trans('cpanel/dashboard/activityLog.activity17_2') !!}",
            "activity18_1":"{!! trans('cpanel/dashboard/activityLog.activity18_1') !!}",
            "activity18_2":"{!! trans('cpanel/dashboard/activityLog.activity18_2') !!}",
            "activity19_1":"{!! trans('cpanel/dashboard/activityLog.activity19_1') !!}",
            "activity19_2":"{!! trans('cpanel/dashboard/activityLog.activity19_2') !!}",
            "activity20_1":"{!! trans('cpanel/dashboard/activityLog.activity20_1') !!}",
            "activity20_2":"{!! trans('cpanel/dashboard/activityLog.activity20_2') !!}",
            "activity21_1":"{!! trans('cpanel/dashboard/activityLog.activity21_1') !!}",
            "activity22_1":"{!! trans('cpanel/dashboard/activityLog.activity22_1') !!}",
            "activity23_1":"{!! trans('cpanel/dashboard/activityLog.activity23_1') !!}",
            "activity23_2":"{!! trans('cpanel/dashboard/activityLog.activity23_2') !!}",
            "activity24_1":"{!! trans('cpanel/dashboard/activityLog.activity24_1') !!}",
            "activity24_2":"{!! trans('cpanel/dashboard/activityLog.activity24_2') !!}",
            "activity25_1":"{!! trans('cpanel/dashboard/activityLog.activity25_1') !!}",
            "activity25_2":"{!! trans('cpanel/dashboard/activityLog.activity25_2') !!}",
            "activity2505_1":"{!! trans('cpanel/dashboard/activityLog.activity2505_1') !!}",
            "activity2505_2":"{!! trans('cpanel/dashboard/activityLog.activity2505_2') !!}",
            "activity2506_1":"{!! trans('cpanel/dashboard/activityLog.activity2506_1') !!}",
            "activity2506_2":"{!! trans('cpanel/dashboard/activityLog.activity2506_2') !!}",
            "activity26_1":"{!! trans('cpanel/dashboard/activityLog.activity26_1') !!}",
            "activity26_2":"{!! trans('cpanel/dashboard/activityLog.activity26_2') !!}",
            "activity27_1":"{!! trans('cpanel/dashboard/activityLog.activity27_1') !!}",
            "activity27_2":"{!! trans('cpanel/dashboard/activityLog.activity27_2') !!}",
            "activity28_1":"{!! trans('cpanel/dashboard/activityLog.activity28_1') !!}",
            "activity28_2":"{!! trans('cpanel/dashboard/activityLog.activity28_2') !!}",
            "activity29_1":"{!! trans('cpanel/dashboard/activityLog.activity29_1') !!}",
            "activity29_2":"{!! trans('cpanel/dashboard/activityLog.activity29_2') !!}",
            "activity30_1":"{!! trans('cpanel/dashboard/activityLog.activity30_1') !!}",
            "activity30_2":"{!! trans('cpanel/dashboard/activityLog.activity30_2') !!}",
            "activity31_1":"{!! trans('cpanel/dashboard/activityLog.activity31_1') !!}",
            "activity31_2":"{!! trans('cpanel/dashboard/activityLog.activity31_2') !!}",
            "activity32_1":"{!! trans('cpanel/dashboard/activityLog.activity32_1') !!}",
            "activity33_1":"{!! trans('cpanel/dashboard/activityLog.activity33_1') !!}",
            "activity3305_1":"{!! trans('cpanel/dashboard/activityLog.activity3305_1') !!}",
            "activity3305_2":"{!! trans('cpanel/dashboard/activityLog.activity3305_2') !!}",
            "activity3306_1":"{!! trans('cpanel/dashboard/activityLog.activity3306_1') !!}",
            "activity3306_2":"{!! trans('cpanel/dashboard/activityLog.activity3306_2') !!}",
            "activity34_1":"{!! trans('cpanel/dashboard/activityLog.activity34_1') !!}",
            "activity34_2":"{!! trans('cpanel/dashboard/activityLog.activity34_2') !!}",
            "activity35_1":"{!! trans('cpanel/dashboard/activityLog.activity35_1') !!}",
            "activity35_2":"{!! trans('cpanel/dashboard/activityLog.activity35_2') !!}",
            "activity35_3":"{!! trans('cpanel/dashboard/activityLog.activity35_3') !!}",
            "activity35_4":"{!! trans('cpanel/dashboard/activityLog.activity35_4') !!}",

            "activity36_1":"{!! trans('cpanel/dashboard/activityLog.activity36_1') !!}",
            "activity36_2":"{!! trans('cpanel/dashboard/activityLog.activity36_2') !!}",
            "activity3601_1":"{!! trans('cpanel/dashboard/activityLog.activity3601_1') !!}",
            "activity3601_2":"{!! trans('cpanel/dashboard/activityLog.activity3601_2') !!}",
            "activity3602_1":"{!! trans('cpanel/dashboard/activityLog.activity3602_1') !!}",
            "activity3602_2":"{!! trans('cpanel/dashboard/activityLog.activity3602_2') !!}",
            "activity3603_1":"{!! trans('cpanel/dashboard/activityLog.activity3603_1') !!}",
            "activity3603_2":"{!! trans('cpanel/dashboard/activityLog.activity3603_2') !!}",
            "activity3604_1":"{!! trans('cpanel/dashboard/activityLog.activity3604_1') !!}",
            "activity3604_2":"{!! trans('cpanel/dashboard/activityLog.activity3604_2') !!}",
            "activity3604_3":"{!! trans('cpanel/dashboard/activityLog.activity3604_3') !!}",
            "activity3604_4":"{!! trans('cpanel/dashboard/activityLog.activity3604_4') !!}",
            "activity3604_5":"{!! trans('cpanel/dashboard/activityLog.activity3604_5') !!}",
            "activity3605_1":"{!! trans('cpanel/dashboard/activityLog.activity3605_1') !!}",
            "activity3605_2":"{!! trans('cpanel/dashboard/activityLog.activity3605_2') !!}",
            "activity3606_1":"{!! trans('cpanel/dashboard/activityLog.activity3606_1') !!}",
            "activity3606_2":"{!! trans('cpanel/dashboard/activityLog.activity3606_2') !!}",

            "activity37_1":"{!! trans('cpanel/dashboard/activityLog.activity37_1') !!}",
            "activity37_2":"{!! trans('cpanel/dashboard/activityLog.activity37_2') !!}",
            "activity37_3":"{!! trans('cpanel/dashboard/activityLog.activity37_3') !!}",
            "activity38_1":"{!! trans('cpanel/dashboard/activityLog.activity38_1') !!}",
            "activity38_2":"{!! trans('cpanel/dashboard/activityLog.activity38_2') !!}",
            "activity38_3":"{!! trans('cpanel/dashboard/activityLog.activity38_3') !!}",
            "activity39_1":"{!! trans('cpanel/dashboard/activityLog.activity39_1') !!}",
            "activity39_2":"{!! trans('cpanel/dashboard/activityLog.activity39_2') !!}",
            "activity39_3":"{!! trans('cpanel/dashboard/activityLog.activity39_3') !!}",
            "activity40_1":"{!! trans('cpanel/dashboard/activityLog.activity40_1') !!}",
            "activity40_2":"{!! trans('cpanel/dashboard/activityLog.activity40_2') !!}",
            "activity4001_1":"{!! trans('cpanel/dashboard/activityLog.activity4001_1') !!}",
            "activity4001_2":"{!! trans('cpanel/dashboard/activityLog.activity4001_2') !!}",
            "activity41_1":"{!! trans('cpanel/dashboard/activityLog.activity41_1') !!}",
            "activity41_2":"{!! trans('cpanel/dashboard/activityLog.activity41_2') !!}",
            "activity42_1":"{!! trans('cpanel/dashboard/activityLog.activity42_1') !!}",
            "activity42_2":"{!! trans('cpanel/dashboard/activityLog.activity42_2') !!}",
            "activity43_1":"{!! trans('cpanel/dashboard/activityLog.activity43_1') !!}",
            "activity43_2":"{!! trans('cpanel/dashboard/activityLog.activity43_2') !!}",
            "activity44_1":"{!! trans('cpanel/dashboard/activityLog.activity44_1') !!}",
            "activity44_2":"{!! trans('cpanel/dashboard/activityLog.activity44_2') !!}",
            "activity45_1":"{!! trans('cpanel/dashboard/activityLog.activity45_1') !!}",
            "activity45_2":"{!! trans('cpanel/dashboard/activityLog.activity45_2') !!}",
            "activity45_3":"{!! trans('cpanel/dashboard/activityLog.activity45_3') !!}",
            "activity46_1":"{!! trans('cpanel/dashboard/activityLog.activity46_1') !!}",
            "activity46_2":"{!! trans('cpanel/dashboard/activityLog.activity46_2') !!}",
            "activity46_3":"{!! trans('cpanel/dashboard/activityLog.activity46_3') !!}",
            "activity47_1":"{!! trans('cpanel/dashboard/activityLog.activity47_1') !!}",
            "activity47_2":"{!! trans('cpanel/dashboard/activityLog.activity47_2') !!}",
            "activity48_1":"{!! trans('cpanel/dashboard/activityLog.activity48_1') !!}",
            "activity48_2":"{!! trans('cpanel/dashboard/activityLog.activity48_2') !!}",
            "activity49_1":"{!! trans('cpanel/dashboard/activityLog.activity49_1') !!}",
            "activity49_2":"{!! trans('cpanel/dashboard/activityLog.activity49_2') !!}",
            "activity49_3":"{!! trans('cpanel/dashboard/activityLog.activity49_3') !!}",
            "activity50_1":"{!! trans('cpanel/dashboard/activityLog.activity50_1') !!}",
            "activity50_2":"{!! trans('cpanel/dashboard/activityLog.activity50_2') !!}",
            "activity50_3":"{!! trans('cpanel/dashboard/activityLog.activity50_3') !!}",
            "activity51_1":"{!! trans('cpanel/dashboard/activityLog.activity51_1') !!}",
            "activity51_2":"{!! trans('cpanel/dashboard/activityLog.activity51_2') !!}",
            "activity51_3":"{!! trans('cpanel/dashboard/activityLog.activity51_3') !!}",
            "activity52_1":"{!! trans('cpanel/dashboard/activityLog.activity52_1') !!}",
            "activity52_2":"{!! trans('cpanel/dashboard/activityLog.activity52_2') !!}",
            "activity52_3":"{!! trans('cpanel/dashboard/activityLog.activity52_3') !!}",
            "activity53_1":"{!! trans('cpanel/dashboard/activityLog.activity53_1') !!}",
            "activity53_2":"{!! trans('cpanel/dashboard/activityLog.activity53_2') !!}",
            "activity53_3":"{!! trans('cpanel/dashboard/activityLog.activity53_3') !!}",
            "activity54_1":"{!! trans('cpanel/dashboard/activityLog.activity54_1') !!}",
            "activity54_2":"{!! trans('cpanel/dashboard/activityLog.activity54_2') !!}",
            "activity54_3":"{!! trans('cpanel/dashboard/activityLog.activity54_3') !!}",
            "activity55_1":"{!! trans('cpanel/dashboard/activityLog.activity55_1') !!}",
            "activity55_2":"{!! trans('cpanel/dashboard/activityLog.activity55_2') !!}",
            "activity55_3":"{!! trans('cpanel/dashboard/activityLog.activity55_3') !!}",
            "activity56_1":"{!! trans('cpanel/dashboard/activityLog.activity56_1') !!}",
            "activity56_2":"{!! trans('cpanel/dashboard/activityLog.activity56_2') !!}",
            "activity56_3":"{!! trans('cpanel/dashboard/activityLog.activity56_3') !!}",
            "activity57_1":"{!! trans('cpanel/dashboard/activityLog.activity57_1') !!}",
            "activity57_2":"{!! trans('cpanel/dashboard/activityLog.activity57_2') !!}",
            "activity57_3":"{!! trans('cpanel/dashboard/activityLog.activity57_3') !!}",
            "activity58_1":"{!! trans('cpanel/dashboard/activityLog.activity58_1') !!}",
            "activity58_2":"{!! trans('cpanel/dashboard/activityLog.activity58_2') !!}",
            "activity58_3":"{!! trans('cpanel/dashboard/activityLog.activity58_3') !!}",
            "activity59_1":"{!! trans('cpanel/dashboard/activityLog.activity59_1') !!}",
            "activity59_2":"{!! trans('cpanel/dashboard/activityLog.activity59_2') !!}",
            "activity59_3":"{!! trans('cpanel/dashboard/activityLog.activity59_3') !!}",
            "activity60_1":"{!! trans('cpanel/dashboard/activityLog.activity60_1') !!}",
            "activity60_2":"{!! trans('cpanel/dashboard/activityLog.activity60_2') !!}",
            "activity60_3":"{!! trans('cpanel/dashboard/activityLog.activity60_3') !!}",

            "activity61_1":"{!! trans('cpanel/dashboard/activityLog.activity61_1') !!}",
            "activity61_2":"{!! trans('cpanel/dashboard/activityLog.activity61_2') !!}",
            "activity61_3":"{!! trans('cpanel/dashboard/activityLog.activity61_3') !!}",
            "activity62_1":"{!! trans('cpanel/dashboard/activityLog.activity62_1') !!}",
            "activity62_2":"{!! trans('cpanel/dashboard/activityLog.activity62_2') !!}",
            "activity62_3":"{!! trans('cpanel/dashboard/activityLog.activity62_3') !!}",
            "activity63_1":"{!! trans('cpanel/dashboard/activityLog.activity63_1') !!}",
            "activity63_2":"{!! trans('cpanel/dashboard/activityLog.activity63_2') !!}",
            "activity63_3":"{!! trans('cpanel/dashboard/activityLog.activity63_3') !!}",
            "activity64_1":"{!! trans('cpanel/dashboard/activityLog.activity64_1') !!}",
            "activity64_2":"{!! trans('cpanel/dashboard/activityLog.activity64_2') !!}",
            "activity65_1":"{!! trans('cpanel/dashboard/activityLog.activity65_1') !!}",
            "activity65_2":"{!! trans('cpanel/dashboard/activityLog.activity65_2') !!}",
            "activity65_3":"{!! trans('cpanel/dashboard/activityLog.activity65_3') !!}",
            "activity66_1":"{!! trans('cpanel/dashboard/activityLog.activity66_1') !!}",
            "activity66_2":"{!! trans('cpanel/dashboard/activityLog.activity66_2') !!}",
            "activity66_3":"{!! trans('cpanel/dashboard/activityLog.activity66_3') !!}",
        },
        home:{
            "welcome":"{!! trans('cpanel/dashboard/home.welcome') !!}",
            "noProducts1":"{!! trans('cpanel/dashboard/home.noProducts1') !!}",
            "noProducts2":"{!! trans('cpanel/dashboard/home.noProducts2') !!}",
            "product":"{!! trans('cpanel/dashboard/home.product') !!}",
            "ordered":"{!! trans('cpanel/dashboard/home.ordered') !!}",
            "income":"{!! trans('cpanel/dashboard/home.income') !!}",
            "delivered":"{!! trans('cpanel/dashboard/home.delivered') !!}",
            "orderToday":"{!! trans('cpanel/dashboard/home.orderToday') !!}",
            "ordersToday":"{!! trans('cpanel/dashboard/home.ordersToday') !!}",
            "noNotOrderedProducts":"{!! trans('cpanel/dashboard/home.noNotOrderedProducts') !!}",

        },
        // design:{
        //     "colorCodeCopyed":"{!! trans('cpanel/design/websiteStyle.colorCodeCopyed') !!}",
        //     "uploadNew":"{!! trans('cpanel/design/imgs.uploadNew') !!}",
        // },
        templates:{
            "apply":"{!! trans('cpanel/design/Templates.apply') !!}",
            "livePreview":"{!! trans('cpanel/design/Templates.livePreview') !!}",
            "imgsTrans":"{!! trans('cpanel/design/Templates.imgsTrans') !!}",

            "pizzeria":"{!! trans('cpanel/design/Templates.pizzeria') !!}",
            "americanDiner":"{!! trans('cpanel/design/Templates.americanDiner') !!}",
            "casualDining":"{!! trans('cpanel/design/Templates.casualDining') !!}",
            "fineDining":"{!! trans('cpanel/design/Templates.fineDining') !!}",
            "italian":"{!! trans('cpanel/design/Templates.italian') !!}",
            "burgers":"{!! trans('cpanel/design/Templates.burgers') !!}",
            "sandwiches":"{!! trans('cpanel/design/Templates.sandwiches') !!}",
            "donuts":"{!! trans('cpanel/design/Templates.donuts') !!}",
            "patisserie":"{!! trans('cpanel/design/Templates.patisserie') !!}",
            "desserts":"{!! trans('cpanel/design/Templates.desserts') !!}",
            "fastFood":"{!! trans('cpanel/design/Templates.fastFood') !!}",
            "vegan":"{!! trans('cpanel/design/Templates.vegan') !!}",
            "mexican":"{!! trans('cpanel/design/Templates.mexican') !!}",
            "vegetarian":"{!! trans('cpanel/design/Templates.vegetarian') !!}",
            "mediterranean":"{!! trans('cpanel/design/Templates.mediterranean') !!}",
            "asian":"{!! trans('cpanel/design/Templates.asian') !!}",
            "indian":"{!! trans('cpanel/design/Templates.indian') !!}",
            "steakhouse":"{!! trans('cpanel/design/Templates.steakhouse') !!}",
            "chinese":"{!! trans('cpanel/design/Templates.chinese') !!}",
            "sushiBar":"{!! trans('cpanel/design/Templates.sushiBar') !!}",
            "friedChicken":"{!! trans('cpanel/design/Templates.friedChicken') !!}",
            "seafood":"{!! trans('cpanel/design/Templates.seafood') !!}",
            "icecream":"{!! trans('cpanel/design/Templates.icecream') !!}",
        },
        homePageSections:{
            "intro":"{!! trans('cpanel/design/homePageSections.intro') !!}",
            "info":"{!! trans('cpanel/design/homePageSections.info') !!}",
            "ourStory":"{!! trans('cpanel/design/homePageSections.ourStory') !!}",
            "slideShow":"{!! trans('cpanel/design/homePageSections.slideShow') !!}",
            "gallery":"{!! trans('cpanel/design/homePageSections.gallery') !!}",

            "galleryNoImgs":"{!! trans('cpanel/design/homePageSections.galleryNoImgs') !!}",

            "selectImg":"{!! trans('cpanel/design/homePageSections.selectImg') !!}",

            "slideShowNoContent":"{!! trans('cpanel/design/homePageSections.slideShowNoContent') !!}",
            "openInNewTab":"{!! trans('cpanel/design/homePageSections.openInNewTab') !!}",
            "openInSameTab":"{!! trans('cpanel/design/homePageSections.openInSameTab') !!}",
            "slideShow":"{!! trans('cpanel/design/homePageSections.slideShow') !!}",
            "slideShowNoImg":"{!! trans('cpanel/design/homePageSections.slideShowNoImg') !!}",
            "slideShowTitle":"{!! trans('cpanel/design/homePageSections.slideShowTitle') !!}",
            "slideShowDes":"{!! trans('cpanel/design/homePageSections.slideShowDes') !!}",
            "slideShowLink":"{!! trans('cpanel/design/homePageSections.slideShowLink') !!}",
            "slideShowImgInfoChanged":"{!! trans('cpanel/design/homePageSections.slideShowImgInfoChanged') !!}",

            "intro":"{!! trans('cpanel/design/homePageSections.intro') !!}",
            "selectHomePageIntroImgImg":"{!! trans('cpanel/design/homePageSections.selectHomePageIntroImgImg') !!}",
            "templateIntroImg":"{!! trans('cpanel/design/homePageSections.templateIntroImg') !!}",

            "ourStory":"{!! trans('cpanel/design/homePageSections.ourStory') !!}",
            "selectHomePageInfoImgImg":"{!! trans('cpanel/design/homePageSections.selectHomePageInfoImgImg') !!}",
            "templateInfoImg":"{!! trans('cpanel/design/homePageSections.templateInfoImg') !!}",

            "info":"{!! trans('cpanel/design/homePageSections.info') !!}",
            "selectHomePageOurStoryImgImg":"{!! trans('cpanel/design/homePageSections.selectHomePageOurStoryImgImg') !!}",
            "templateOurStoryImg":"{!! trans('cpanel/design/homePageSections.templateOurStoryImg') !!}",
        },
    }

    </script>




