require('./general/alignment.js')
require('./general/padding.js')
require('./general/margin.js')
require('./general/border.js')
require('./general/border_radius.js')
require('./general/box_shadow.js')
require('./general/width.js')
require('./general/height.js')
require('./general/text.js')
require('./general/background.js')
require('./general/filter.js')

require('./general/hover_settings.js')
require('./general/transform.js')
require('./general/animation.js')