require('./general/rename.js')
require('./general/alignment.js')//
require('./general/display.js')//
require('./general/padding.js')
require('./general/margin.js')
require('./general/border.js')//
require('./general/border_radius.js')//
require('./general/box_shadow.js')//
require('./general/width.js')
require('./general/height.js')
require('./general/text.js')
require('./general/background.js')//
require('./general/filter.js')//
require('./general/image.js')
require('./general/button.js')//
require('./general/png_icon.js')
require('./general/arrange.js')
require('./general/transform.js')//
require('./general/animation.js')
require('./general/transition.js')
require('./general/interactions.js')//