@extends('home.layout')

@section('title'){{ trans('home/home.homeTitle') }}@endsection
@section('description'){{ trans('home/home.homeDescription') }}@endsection
@section('body')
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
    <div>7arakat</div>
@endsection
