draw_editor_popup_section_block_alignment = function(){
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            draw_select_box({
                keys_arr:[{key:'flex-direction',key_tree:`${window.selected}.css`}],
                name:texts.styling.elements_direction,
                selections:[
                    {text:texts.select_elems.column,key:'column'},
                    {text:texts.select_elems.row,key:'row'},
                ],
                is_responsive:true,
            }),
            draw_select_box({
                keys_arr:[{key:'flex-wrap',key_tree:`${window.selected}.css`}],
                name:texts.styling.wrap_elements,
                selections:[
                    {text:texts.select_elems.wrap,key:'wrap'},
                    {text:texts.select_elems.no_wrap,key:'nowrap'},
                ],
                is_responsive:true,
            }),
            draw_select_box({
                keys_arr:[{key:'align-items',key_tree:`${window.selected}.css`}],
                name:texts.styling.align_elems,
                selections:[
                    {text:texts.select_elems.start,key:'flex-start'},
                    {text:texts.select_elems.center,key:'center'},
                    {text:texts.select_elems.end,key:'flex-end'},
                ],
                is_responsive:true,
            }),
            draw_select_box({
                keys_arr:[{key:'justify-content',key_tree:`${window.selected}.css`}],
                name:texts.styling.justify_elems,
                selections:[
                    {text:texts.select_elems.start,key:'flex-start'},
                    {text:texts.select_elems.center,key:'center'},
                    {text:texts.select_elems.end,key:'flex-end'},
                ],
                is_responsive:true,
            }),
        )
        $(`.editor_popup_body_shortcut.editor_alignment`).addClass('editor_popup_body_shortcut_selected')
    });
}
$('body').on('click','.editor_alignment',function(e){
    draw_editor_popup_section_block_alignment();
})