draw_editor_popup_border_radius = function(){
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            draw_editors_container({
                is_responsive:true,
                editors:[
                    draw_four_number_pickers({
                        key_tree:window.selected,
                        variable_key:'css',
                        key:'border-radius',
                        units:['px','em','%'],
                        step:1,
                        names:[texts.styling.border_radius,texts.styling.top_left_corner,texts.styling.top_right_corner,texts.styling.bottom_right_corner,texts.styling.bottom_left_corner]
                    })
                ]
            })
        )
        $(`.editor_popup_body_shortcut.editor_border_radius`).addClass('editor_popup_body_shortcut_selected')
    });
}
$('body').on('click','.editor_border_radius',function(e){
    draw_editor_popup_border_radius();
})