draw_editor_popup_box_shadow = function(){
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            draw_editors_container({
                is_responsive:true,
                interactions:['hover','click','focus','disabled'],
                editors:[
                    draw_box_shadow_editor({
                        key_tree:window.selected,
                        variable_key:'css',
                        key:'box-shadow',
                    })
                ]
            }),
        )
        $(`.editor_popup_body_shortcut.editor_box_shadow`).addClass('editor_popup_body_shortcut_selected')
        $(`.editor_popup_body_shortcut.editor_box_shadow`).closest('.editor_popup_body_shortcut_group').find('.editor_popup_body_shortcut_open_group').addClass('editor_popup_body_shortcut_open_group_selected')
    });
}
$('body').on('click','.editor_box_shadow',function(e){
    draw_editor_popup_box_shadow();
})