draw_editor_popup_check_box = function(){
    if(!accessibility_check(window.selected,'check_box')){return;}
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            draw_editors_container({
                is_responsive:false,
                editors:[
                    $('<div/>',{class:'editor_popup_row editor_popup_brdrT_none'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.check_mark}),
                        draw_svg_icon_picker({
                            key_tree:`${window.selected}.children`,
                            render:`${window.selected}.children.icon`,
                            variable_key:null,
                            key:'icon',
                            icon_type:'check',
                        })
                    ),
                    $('<div/>',{class:'editor_popup_row'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.check_mark_color}),
                        draw_color_picker({
                            key_tree:`${window.selected}.children.icon`,
                            variable_key:'css',
                            key:'fill'
                        })
                    ),
                    $('<div/>',{class:'editor_popup_row'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.border_color}),
                        draw_color_picker({
                            key_tree:`${window.selected}.children.icon`,
                            variable_key:'css',
                            key:'border-color'
                        })
                    ),
                    $('<div/>',{class:'editor_popup_col'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.size}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.icon`,
                            variable_key:'css',
                            key:'width',
                            units:['px'],
                            step:1,
                        })
                    ),
                    $('<div/>',{class:'editor_popup_col'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.border_radius}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.icon`,
                            variable_key:'css',
                            key:'border-radius',
                            units:['px'],
                            step:1,
                        })
                    ),
                    $('<div/>',{class:'editor_popup_col'}).append(
                        $('<div/>',{class:'fs09',text:texts.styling.padding}),
                        draw_number_picker({
                            key_tree:`${window.selected}.children.icon`,
                            variable_key:'css',
                            key:'padding',
                            units:['px'],
                            step:1,
                        })
                    ),
                ]
            })
        )
        setTimeout(()=>{
            $('.editor_popup_title2').text(texts.styling.check_box)
            $(`.editor_popup_body_shortcut.editor_check_box`).addClass('editor_popup_body_shortcut_selected')
        });
    })
}
$('body').on('click','.editor_check_box',function(){
    draw_editor_popup_check_box();
})