draw_editor_popup_text = function(){
    show_editor_popup('editor',function(){
        $('#editor').find('.editor_popup_body').text('').append(
            $('<div/>',{class:'editor_popup_container w100p',key:'editor_text'}).append(
            draw_editors_container({
                is_responsive:true,
                editors:[
                        $('<div/>',{class:'editor_popup_row editor_popup_brdrT_none'}).append(
                            $('<div/>',{class:'fs09',text:texts.styling.color}),
                            draw_color_picker({
                                key_tree:window.selected,
                                variable_key:'css',
                                key:'color',
                            })
                        ),
                        draw_editor_show_container({
                            key:'text_font_style',
                            name:texts.styling.font_style,
                            row_class:true,
                        }),
                        $('<div/>',{class:'editor_popup_col'}).append(
                            $('<div/>',{class:'fs09',text:texts.styling.text_align}),
                            draw_select_box({
                                editor_class:'editor_text_align',
                                key_tree:window.selected,
                                variable_key:'css',
                                key:'text-align',
                                selections:[
                                    {text:texts.styling.start,key:'start'},
                                    {text:texts.styling.center,key:'center'},
                                    {text:texts.styling.end,key:'end'},
                                ]
                            })
                        ),
                        $('<div/>',{class:'editor_popup_col'}).append(
                            $('<div/>',{class:'fs09',text:texts.styling.font_size}),
                            draw_number_picker({
                                key_tree:window.selected,
                                variable_key:'css',
                                key:'font-size',
                                units:['px','em'],
                                step:1,
                            }),
                        ),
                        $('<div/>',{class:'editor_popup_col'}).append(
                            $('<div/>',{class:'fs09',text:texts.styling.line_height}),
                            draw_number_picker({
                                key_tree:window.selected,
                                variable_key:'css',
                                key:'line-height',
                                units:['px','em'],
                                step:1,
                            }),
                        ),
                        $('<div/>',{class:'editor_popup_col'}).append(
                            $('<div/>',{class:'fs09',text:texts.styling.letter_spacing}),
                            draw_number_picker({
                                key_tree:window.selected,
                                variable_key:'css',
                                key:'letter-spacing',
                                units:['px','em'],
                                step:1,
                            }),
                        )
                    ]
                }),
            ),
            $('<div/>',{class:'editor_popup_container none w100p',key:'text_font_style',parent_key:'editor_text'}).append(
            draw_editors_container({
                is_responsive:false,
                editors:[
                        draw_font_style_picker({
                            key_tree:`${window.selected}`,
                            variable_key:'font_style',
                        })
                    ]
                })
            ),
 
        )
    })
    setTimeout(()=>{
        $('.editor_popup_title2').text(texts.styling.text)
        $(`.editor_popup_body_shortcut.editor_text`).addClass('editor_popup_body_shortcut_selected')
    });
}
$('body').on('click','.editor_text',function(e){
    draw_editor_popup_text();
})
